### ISSUE TITLE
Drilldown not supported?

### ISSUE THREAD

**Issue by vaibhav276** [pablojim/highcharts-ng#112]
I was trying to use highcharts drilldown feature via this directive, but seems like it is not supported. So I applied the code change mentioned here: http://stackoverflow.com/questions/22195266/highcharts-ng-with-drilldown

After this, the drilldown event seems to be firing, but I ran into following issues while completing the drilldown task:
**1. I am unable to update the x-axis labels**
As per this example(http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/async/), x-axis labels should be configurable via `chart.series.data[i].name`. But when using this directive, they can be only configured via `chart.categories[i]`. Is there a way I can update the x-axis labels via `chart.series.data[i].name` because `chart.categories` is undefined when I drill down?

**2. I am unable to get the level of drilldown**
Is there some way I can find out at any given point what is the level till which the user has drilled down?

**3. Is there a way I can get a event callback when user moves back up from drilldown?**

Any examples on drilldown to multiple levels? Any new fixes in pipeline related to this?

**Comment by nibblesnbits** [comment]
[Here](http://plnkr.co/edit/9ZQX3u?p=preview) is a working plunk.  What caught me was the format Highcharts wants the data in.

**Comment by kumarabrol** [comment]
Is it possible that we can apply auto-refresh on the main highchart and stop autorefresh when that drill down and when we click back to main chart then resume the auto-refresh functionality.
Current code for auto-refresh on main highchart works good.here is the implementation
$scope.intervalFunction = function(){
$timeout(function() {
init(1,11);
$scope.rand=gettodayDateTime();
$scope.intervalFunction();
}, 30000)
}

$scope.intervalFunction();

Please advice how can i stop autorefresh on drill down page and then resume it back when i am back on main highchrt.

**Comment by wfairclough** [comment]
My issue just turned out to be that I was not including the `drilldown.js` module:

`<script src="https://code.highcharts.com/modules/drilldown.js"></script>`

**Comment by suggy75** [comment]
I got this working by putting the drilldown data in options, not underneath the series data, like the highcharts example shows.
