### ISSUE TITLE
Add 'solidgauge' example

### ISSUE THREAD

**Issue by reustonium** [pablojim/highcharts-ng#115]
Overall this module is fantastic, but I'm having some trouble getting a 'solidgauge' chart type to work.

I have included each of the 'extra' highcharts js files

```
<script type='text/javascript' src='http://code.highcharts.com/highcharts.js'></script>
<script type='text/jacascript' src="http://code.highcharts.com/highcharts-more.js"></script>
<script type='text/jacascript' src="http://code.highcharts.com/modules/solid-gauge.src.js"></script>
<script type='text/javascript' src='./javascripts/highcharts-ng/dist/highcharts-ng.min.js'></script>
```

and have several other chart types working, but when I try to create a 'solidgauge' I get [an error](http://www.highcharts.com/errors/17)

Could you please add an example to the README.MD for how to add this chart type?

**Comment by lmatheus** [comment]
I'm Having Trouble removing the box around the value in the middle, like on the http://jsfiddle.net/6hxaB/3/  example. Does anyone know how to do this?

Also, when I render this chart with the native jquery library that box doesnt appear.

**Comment by pablojim** [comment]
@lmatheus please don't comment on closed issues. Maybe ask a question on stackoverflow/the mailing list. Include a jsfiddle demonstrating the problem.

**Comment by mluis** [comment]
I'm having a problem that might be related to this. The gauges's pointer doesn't seem to appear.
