### ISSUE TITLE
Highcharts.setOptions method

### ISSUE THREAD

**Issue by olaznog10** [pablojim/highcharts-ng#119]
Hi,

Trying to set the timezone using global: {setUtC:false}, I realized that it is not called to Highcharts.setOptions method. Hence, the chart timezone is not set because Highchart API does not support timezone configuration inside the chart object (http://jsfiddle.net/me3ry/133/). I also opened an issue to HC in order to solve this situation (https://github.com/highslide-software/highcharts.com/issues/2993)

A possible solition to this "issue" is to call  

Highcharts.setOptions(config.options); in 193 line 
before  
chart = config.useHighStocks ? new Highcharts.StockChart(mergedOptions) : new Highcharts.Chart(mergedOptions);

Regards and good luck with HC4.0

**Comment by Measy** [comment]
it was a huge pain ==#
