### ISSUE TITLE
what workaround for tooltips inside div?

### ISSUE THREAD

**Issue by c0debreaker** [pablojim/highcharts-ng#120]
Hi,

How can I make the tooltip appear outside the div so that the whole/full tooltip gets displayed properly? I tried adding z-index with no luck. Please see screenshot to see what's going on on what I'm experiencing.

![screen shot 2014-04-30 at 9 27 39 am](https://cloud.githubusercontent.com/assets/3783931/2842381/f6f7b960-d073-11e3-9e39-cad1edb77069.png)

Thanks

**Comment by oriko** [comment]
Hi 

I have the same problem with tooltip z-index. Do you have any solutions for it ?
