### ISSUE TITLE
Drop jQuery dependency in favour of standalone highcharts

### ISSUE THREAD

**Issue by tutts** [pablojim/highcharts-ng#121]
Hey,

HighCharts offer a jQuery independent version http://code.highcharts.com/adapters/standalone-framework.js

For my project (and I'm guessing this will apply to others too), we don't use jQuery so its a big framework to include just for charting. the standalone version is only 2kb where as jQuery is ~70kb

Any future plans to drop the jQuery version in favour of the standalone?

Thanks,
tutts

**Comment by ragefuljoe** [comment]
I finally reworked my app to not use jquery, but when using standalone-framework I get weird chart sizing issue. It overflows parent container a bit, but on resize will grow height a tiny bit, but never shrinks back down. So if I resize back and forth a bit, the charts all start getting realllllly tall. I dropped jquery back in, and the problem went away.
