### ISSUE TITLE
Update visibility in chartConfig of 1 serie

### ISSUE THREAD

**Issue by dennisboonk** [pablojim/highcharts-ng#122]
Currently the visible attribute of a serie isn't updated when you toggle the serie on/of.

**Comment by sweco-seprst** [comment]
Got the same issue. Fiddle: http://jsfiddle.net/vtworpuy/

**Comment by pablojim** [comment]
I presume you mean when you click on the series in the chart to toggle it?

If so, no this is not supported currently. It should be a fairly simple fix though if highcharts has the appropriate hooks.

**Comment by sweco-seprst** [comment]
Yes when you click on a series to toggle it the visible value is not updated.

**Comment by pablojim** [comment]
Sorry this is not supported at the moment. I'll consider including it in a future release.
