### ISSUE TITLE
Can't disable the legend

### ISSUE THREAD

**Issue by dennisboonk** [pablojim/highcharts-ng#126]
If i try to disable the legend of a highcharts with this option
        legend: {
            enabled: false
        },
it doesn't work.

**Comment by calvinKG** [comment]
Hi, 

It those not work on my side i have 

 function tdSalesCharts()
         {
             $scope.tdSales = [
                 {data: [1, 2, 4, 7, 3]}
             ];

             $scope.chartConfigTdSales = {
                 options: {
                     chart: {
                         type: 'line'
                     },
                     plotOptions: {
                         series: {
                             stacking: ''
                         }
                     }
                 },
                 series: $scope.tdSales,
                 title: {
                     text: ''
                 },

                 loading: false,
                 size: {width: 350,
                     height: 230},
                 legend: {
                     enabled: false
                 }
             };
         }

**Comment by jmurret** [comment]
@calvinKG , is it showing your series data in the legend?  There is also "showInLegend" in the series configuration. You might try:
series: [{
                data: $scope.tdSales,
                showInLegend:false
            }] 

This is what was occuring for me.

**Comment by antonioaltamura** [comment]
I had the same problem the @jmurret tip solved
`series: [{
data: $scope.tdSales,
showInLegend:false
}]`

**Comment by narasimha694** [comment]
@dennisboonk 
instead of using legend : { enabled : false } , you can try legend : { display : false }.
make sure that legend property should be in options object

**Comment by silentFred** [comment]
@narasimha694 does not work for me...
