### ISSUE TITLE
Highstock rangeSelector and navigator?

### ISSUE THREAD

**Issue by andrewboni** [pablojim/highcharts-ng#136]
I've got a basic [HighStock chart](http://www.highcharts.com/stock/demo/column) working with `highcharts-ng`, but am not seeing either the daterange selector above it or the navigator down below. Is there anything special I need to be doing?

HTML:

``` html
<highchart config="columnChartConfig"></highchart>
```

Coffeescript:

``` coffeescript
    $scope.columnChartConfig =
      options:
        chart:
          alignTicks: false
          height: 600
        title:
          text: "Stats over time"
        xAxis:
          type: 'datetime'
        yAxis:
          type: 'logarithmic'
      useHighStock: true
      series: dataSource
```

My `dataSource` array:

``` json
[{"name":"Prices","data":[[1401465600000,803],[1401469200000,557],[1401472800000,193],[1401476400000,259],[1401480000000,308],[1401483600000,415], ...
```

Any input is appreciated!

**Comment by RPGillespie6** [comment]
@larssondaniel Thanks! That worked for me as well, but why is navigator disabled by default? According to [the API](http://api.highcharts.com/highstock#navigator.enabled) it should be enabled by default.

**Comment by dash-** [comment]
I vote to close this issue, or someone should patch the documentation. Navigator is enabled by default with HighStocks, but useHighStocks: true doesn't make the library create HighStocks objects, it just allows you to use HighStocks options.
