### ISSUE TITLE
Unable to get 'shared' ToolTip working.

### ISSUE THREAD

**Issue by rhys-vdw** [pablojim/highcharts-ng#153]
Hi,

I'm making a stacked column chart, and have the following configuration:

```coffee
  .controller 'ClientMetricsCtrl', ($scope, npsRaw, npsProcessor) ->

    # Chart configuartion object to be revealed in scope.
    chartConfig = {
      options:
        chart: type: 'column'
        plotOptions: column: stacking: 'percent'
        toolTip:
          pointFormat: '''
            <span style="color:{series.color}">{series.name}</span>:
              <b>{point.y}</b> ({point.percentage:.0f}%)<br/>
            '''
          shared: true
      title: text: ''
      xAxis:
        categories: []
        title: text: 'Loading...'
      yAxis:
        min: 0
        max: 100
        title:
          text: 'Percentage of total respondants'
      series: []
    }
```

(Series are fed in programmatically after this code block)

The code is based on [this example](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-stacked-percent/) from the Highcharts website.

Currently everything works as expected, except the `toolTip.shared` flag is being ignored. Any idea what's going on here?

**Comment by vikramk0901** [comment]
If I am not wrong, I think its tooltip not "toolTip".

**Comment by rhys-vdw** [comment]
Oh, wow. Thanks for the response. Looking at the example I cited, I think that you're correct. I'll try this out next time I work on the project.

**Comment by vikramk0901** [comment]
np happy to help.
