### ISSUE TITLE
Pie chart unable to display legend

### ISSUE THREAD

**Issue by Reiji87** [pablojim/highcharts-ng#157]
Hi,

I've tried http://www.highcharts.com/demo/pie-legend demo using the highchart angular library, however the result is different from the one in the demo page.

The actual result should be:
![screen shot 2014-07-18 at 3 10 39 pm](https://cloud.githubusercontent.com/assets/8175305/3623290/a7b2d35c-0e4a-11e4-99f4-635a637b9107.png)
However I am getting:
![screen shot 2014-07-18 at 3 10 24 pm](https://cloud.githubusercontent.com/assets/8175305/3623288/9c532412-0e4a-11e4-99f3-8954ec78092e.png)

What happen here is the legend is missing and instead it is showing a label pointing to the pie chart. is there anyway to fix the problem? Im using exactly the same code as the one shown in high chart demo page.

Thanks :)

**Comment by Reiji87** [comment]
I think i got it! 
THanks! :)

**Comment by OzanKurt** [comment]
@Reiji87 So what was it?
