### ISSUE TITLE
Print or export from external buttons?

### ISSUE THREAD

**Issue by sdawson26** [pablojim/highcharts-ng#185]
I've been looking everywhere through your documentation on this and I'm finding nothing.

Basically i want to put ng-click="exportChart()" or ng-click="printChart()" as firing function from UI elements around the chart.

However, obviously, neither of these examples work.

$scope.exportChart=function(){
  $scope.chartCfg.exportChart({type: 'image/svg+xml', filename: 'my-svg'}, {subtitle: {text:''}});
});

$scope.printChart=function(){
  $scope.chartCfg.print();
});

Is there something I'm missing here? How can I programatically print or export or both?

**Comment by neuzebe** [comment]
Is there a way to export the chart to a PNG (for e.g) but embed it back into the current page instead of a file download?

**Comment by BrainCrumbz** [comment]
I'd say yes, but not through the server export feature offered by highcharts.  
Instead you'd rather work at that locally, fully remaining within JS client code. Basically the flow would be (from top of my head):

1. Create (or provide) a canvas on page, possibily initially hidden
1. Export the chart SVG to the canvas. This is the trickiest part, if you search for that on the net. You will see that one of the hardest part is to recreate the styles applied to the original SVG (both inline ones and those from included CSS files). If I recall correctly, you first create a SVG clone in the canves, then you extract all styles applied to the original SVG and apply them (inline) to the SVG clone. At that point you can take a *virtual screenshot* of the canvas, the HTML object has a method for that, and store the picture into an Image var.
1. Encode the Image into Base64 (that's easy actually, not a real encoding), and attach that to the src attribute of your final img element. If you want to be notified when the picture is actually showing, provide a listener of the Image load event.

Sorry if some of those might be obvious to you.

**Comment by neuzebe** [comment]
Ha! Yes, that's exactly what I did in the end. Exported the chart to a canvas, encoded as base 64 and attached to an image element. I didn't have to do any style manipulation but maybe it will be helpful to future readers. 

Thanks a lot for the response!

**Comment by mauriceharshaw** [comment]
THANK GOD! I've been looking all over for this!!

**Comment by wiseeker** [comment]
@pablojim Your [fiddle](http://jsfiddle.net/a9cse5pt/) exports exactly once. 2nd time onwards, it throws an error saying `TypeError: Cannot read property 'exporting' of undefined`. I can't seem to find why.

I followed your pattern and implemented export in my angularjs app and I'm experiencing exactly the same issue. Any help you can provide in fixing this would be awesome. Thank you for your contribution.
