### ISSUE TITLE
Highcharts Sparkline usage?

### ISSUE THREAD

**Issue by andrewboni** [pablojim/highcharts-ng#195]
I'm trying to generate [sparkline graphs](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/sparkline/) using `highcharts-ng`, but don't see documentation for it. Looks like generating a sparkline graph with highcharts is a little different than a regular chart or even a stockChart.

Has anyone done this before?

**Comment by seiyria** [comment]
Any progress on this?

**Comment by larssondaniel** [comment]
+1

**Comment by Noxville** [comment]
+1

**Comment by mydearxym** [comment]
+1

**Comment by jhiemer** [comment]
+1

**Comment by jaimeguaman** [comment]
+1

anyway, simple sparklines can be easily generated with line charts

![captura de pantalla 2015-04-30 a las 14 35 04](https://cloud.githubusercontent.com/assets/1824920/7418696/26aa3984-ef46-11e4-8464-ddc8484deaf2.png)

**Comment by jhiemer** [comment]
@jaimeguaman having a fiddle with a small sample?

**Comment by kiwina** [comment]
http://jsfiddle.net/cnzvtzpm/
