### ISSUE TITLE
how to use  highchats option chart{event:load:function(){}}?

### ISSUE THREAD

**Issue by zhangmengpl** [pablojim/highcharts-ng#199]
how to use? please help me!
thank you 
zhanglypl@gmail.com

**Comment by ewong97** [comment]
is this planning to be fixed?  We are running into this issue as well.  I also saw a reference to this issue in this posting - http://stackoverflow.com/questions/24233173/explanation-of-why-i-need-to-wrap-a-highcharts-jquery-event-in-an-angular-timeo

**Comment by SushantKadam008** [comment]
HI,
Is there any solution on the above issue ? 

I am trying to achieve the below functionality using highcharts-ng but to no avail.

http://jsfiddle.net/LHSey/129/ 

All events are fired before the chart is drawn. But if I use a timeout with 0 sec it works.
Please help.

**Comment by Fitz3012** [comment]
Hi,

I found a "trick" for this issue few months ago, using redraw event
```javascript
chart: {
    events: {
        redraw: this.completeGrowthGraph
    }
}
```
I create a variable for each graph
```javascript
var growthRendered = false;
```
and I test the variable in the completeGrowthGraph preventing the function to execute twice
```javascript
this.completeGrowthGraph = function() {
    if (growthRendered) {
    } else {
        growthRendered = true;
        // your load function code here
    }
}
```
Hope it helps.
