### ISSUE TITLE
Navigation button doesn't exist and can't be added

### ISSUE THREAD

**Issue by marioot** [pablojim/highcharts-ng#200]
Hi,

It seems that the navigation button (upper right corner in the chart) that is used for chart download can't be added or manipulated in highcharts-ng. Usually, this button is active by default.
The desired behavior can be seen here:
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/navigation/buttonoptions-height/

The behavior with using highcharts-ng can be seen here:
http://jsfiddle.net/vvenLywv/

The example configuration used:
navigation: {
            buttonOptions: {
                height: 40,
                width: 48,
                symbolSize: 24,
                symbolX: 23,
                symbolY: 21,
                symbolStrokeWidth: 2
            }
}

**Comment by Joao-Martins** [comment]
+1

**Comment by wileam** [comment]
+1

**Comment by TwanVermeulen** [comment]
+1
