### ISSUE TITLE
Chart size doesn't auto-fit when using with ui-bootstrap

### ISSUE THREAD

**Issue by iven** [pablojim/highcharts-ng#211]
See: http://jsfiddle.net/156sycv1/

Chart size is 600x400 until you change the browser size.

**Comment by schris12** [comment]
Hey, @pablojim I tried your solution but it doesn't work when I have charts inside an ng-repeat
```
<div class="row row-clear">
     <div class="col-md-6" ng-repeat='item in chart'>
          <highchart config="item"></highchart>
     </div>
</div>
```

**Comment by PDSBGreg** [comment]
To work around the ng-repeat issue, you can add something like 
<code>
$timeout(function() {
  $scope.$broadcast('highchartsng.reflow');
}, 10);
</code>
to your controller in a place after your charts would have been drawn.

**Comment by mdedetrich** [comment]
Are there any updates on this issue? Experiencing the same problem, and I don't want to kill animations just so the chart can resize properly. Note in my case I am using zurb foundation, but its the exact same issue

**Comment by spademan** [comment]
i fix this problem basely as i set  
 chart: {
     events: {
                load: function(chart) {
                     $timeout(function() {
                          chart.target.reflow();   
                     );
              }
          }
};

but i think it's not the true answer cuz there are two phenomenon of the chart 
1.when i click tab to get diff charts,sometime it's width  is the width of parent's element witdh but sometime  not 
2.we can see the reflow action of the  chart by our eyes ,this is uncomfortable for  user~~ 

so i still wait for the robuts solution

**Comment by kumarabrol** [comment]
I did used latest solution provided by spademan.
Please do suggest if there is any other robust solution.

**Comment by joshuadmatthews** [comment]
still an issue for me as well. Is there a reason this isn't getting resolved?

**Comment by git4sun** [comment]
Same issue here. reflow doesn't help. Related to bootstrap I guess.

**Comment by arafiu-rpx** [comment]
this solution helped me when the wrapper is under ng-hide or display:none case

func: function (chart) {
                $scope.$evalAsync(function () {
                  let viewEle = $(chart.container).parents('.ng-hide').first();
                      viewEle.css({"visibility": 'hidden', "display": 'block'}).removeClass('ng-hide');
                      chart.reflow();
                      viewEle.addClass('ng-hide').css({"visibility": '', "display": ''});
                });
              }

hope it helps someone who might banging head to solve this width issue.

**Comment by sirishbitra** [comment]
this solution helped me when the wrapper is under ng-hide or display:none
<pre><code class="markdown">  func: function (chart) {
     $scope.$evalAsync(function () {
       let viewEle = $(chart.container).parents('.ng-hide').first();
            viewEle.css({"visibility": 'hidden', "display": 'block'}).removeClass('ng-hide');
            chart.reflow();
            viewEle.addClass('ng-hide').css({"visibility": '', "display": ''});
       });
  }</code></pre>

**Comment by billyaraujo** [comment]
+1

**Comment by danwild** [comment]
along the same vein as @sirishbitra, I found the simplest approach was to just make my own `.visibility-hide` class to show/hide, which helped highcharts from struggling with the fluid layout.

**Comment by CaledoniaProject** [comment]
None of the solutions above works for me, 

```
%> bower install highcharts
bower highcharts#*              cached https://github.com/highcharts/highcharts-dist.git#5.0.7
bower highcharts#*            validate 5.0.7 against https://github.com/highcharts/highcharts-dist.git#*
[PWD: ~/web]
%> bower install highcharts-ng
bower highcharts-ng#*           cached https://github.com/pablojim/highcharts-ng.git#1.0.1
bower highcharts-ng#*         validate 1.0.1 against https://github.com/pablojim/highcharts-ng.git#*
```

**Comment by CaledoniaProject** [comment]
http://codepen.io/DeividasK/pen/NpKZjN?editors=1010

**Comment by pablojim** [comment]
@CaledoniaProject please see #550

**Comment by CaledoniaProject** [comment]
@pablojim the css solution worked for me, thank you!
