### ISSUE TITLE
Unable to create Master-Detail charts

### ISSUE THREAD

**Issue by shehzadali** [pablojim/highcharts-ng#215]
Hi,

I am unable to find a way to create Master-Detail charts (http://www.highcharts.com/demo/dynamic-master-detail) using highcharts-ng.

I have posted the problem on stackoverflow as well. Pleae check :
http://stackoverflow.com/questions/27019858/how-to-create-master-detail-charts-in-highcharts-ng

Please have a look and suggest if there is any possibility to create master-detail charts in highcharts-ng. Your help will be highly appreciated.

Thanks.

**Comment by seiyria** [comment]
Any progress on this?

**Comment by seiyria** [comment]
We got a working master detail chart by using two highcharts-ng objects based on the same set of data. It works, but it's not pretty.

**Comment by levipadre** [comment]
Hi,
How's going with Master-Detail chart?

**Comment by danyim** [comment]
@seiyria Could you show us an example on a jsfiddle? I too am having difficulties getting this particular set-up to work with highcharts-ng. Thanks!

**Comment by seiyria** [comment]
Hi, sorry, I actually am not working with this anymore. /cc @smithk58

**Comment by smithk58** [comment]
I'll create a JSFiddle when I have time later tonight for this. For the moment though you should be able to do it pretty easily without one.

All we're really doing is:
- Two separate highcharts charts are created. Both are loaded with the same data at the start, but the master one has some extra aesthetic changes (e.g. smaller size, legend removed, etc.).

- On the master chart we override 'options.chart.events.selection' with a custom function. This function adds plot bands to the master chart on the area selected. It then empties the detail charts series data and pushes all of the series data from the master chart in the area that was selected into the details data.

**Comment by danyim** [comment]
Figured it out. Here's the important part:
        events: {
                        selection: function(event) {
                            if(event.xAxis != null) {
                                var min = event.xAxis[0].min;
                                var max = event.xAxis[0].max;
                                var detailData = [];
                                var xAxis = this.xAxis[0];

                                $.each(this.series[0].data, function () {
                                    if (this.x > min && this.x < max) {
                                        detailData.push([this.x, this.y]);
                                    }
                                });
                                $scope.demandDetailChartConfig.series[0].data = detailData;

                                xAxis.removePlotBand('mask-before');
                                xAxis.addPlotBand({
                                    id: 'mask-before',
                                    from: seriesData[0][0],
                                    to: min,
                                    color: 'rgba(0, 0, 0, 0.3)'
                                });

                                xAxis.removePlotBand('mask-after');
                                xAxis.addPlotBand({
                                    id: 'mask-after',
                                    from: max,
                                    to: seriesData[seriesData.length - 1][0],
                                    color: 'rgba(0, 0, 0, 0.3)'
                                });
                                $scope.$apply();
                                return false; // Returning false prevents the zoom from happening
                            }
                        }
                    }
