### ISSUE TITLE
Slow generation for big datasets

### ISSUE THREAD

**Issue by blacksonic** [pablojim/highcharts-ng#217]
When generating circa 1k points on the chart in ```processSeries``` the method ```angular.copy``` extremely slows down rendering

**Comment by sylvainbannier** [comment]
same issue. Seems like there is heavy digest cycle going on when rendering big datasets

**Comment by pablojim** [comment]
There is disableDataWatch option which may help performance in some scenarios.

**Comment by seadour** [comment]
I've enabled the `disableDataWatch` option but I haven't seen a performance increase with it.

In my case, I'm noticing slow rendering via `angular.copy` method when trying to hide/show a series with many data points (over 8000).

**Comment by seadour** [comment]
@pablojim Just to make sure I am using the `disableDataWatch` option correctly, can you give us a quick example of how to correctly enable it?

**Comment by seadour** [comment]
Update: I added `disable-data-watch="true"` to my `<highchart>` HTML element, and it seems to work. Unfortunately, when this is enabled, I can no longer add or remove a series.

**Comment by bwyss** [comment]
I have the same, very poor performance where by the browser locks up as the chart is rendering. I switched back to rendering the charts the jQuery way and it's resolved.
