### ISSUE TITLE
HighCharts-ng with ng-repeat

### ISSUE THREAD

**Issue by mketevi** [pablojim/highcharts-ng#222]
Hello i am working with your plugin but i have some issues with the series. I am actually using the current versions of the plugin in an ng-repeat.
You said that : <highchart id="chart1" series="chart.series" title="chart.title" options="chart.options"></highchart> is no more compatible with the current version of the plugin. So I do not how to pass my series directly in the <highchart id="chart1" config="chartConfig"></highchart>.

**Comment by GowrishankarGeek** [comment]
Hello, i am working with your plugin but face following issues, 1. General Drawing shown as blank 2. Column chart displayed as line chart. I would like to know, is possible to do with this plugin? If so, Help me out here for integration.
