### ISSUE TITLE
chart.options undefined after exportChart

### ISSUE THREAD

**Issue by BrainCrumbz** [pablojim/highcharts-ng#224]
Inside a controller we are saving a reference to the chart object as in the following:

```
var _chart;
// ...
$scope.chartConfig = {
  // ...
  func: function (chart) {
    _chart = chart;
  },
};
```

After updating the series with data, we export the diagram as in the following:

```
_chart.exportChart(someExportOptions);
```

The next time we have to access the chart object, we find that the object is _somehow different_. What we mean is that the object is still an instance of `Chart` but loses all of its public attributes. In particular it loses `options`, but many others as well (see pasted pictures below).  
After exporting, the object only contains some jQueryNNNNNNNN property and then a bunch of functions are to be found in the prototype, and those functions do not seem to be the same functions as before.

Chart object _before_:
![image](https://cloud.githubusercontent.com/assets/3185573/5220665/ea9feef8-7668-11e4-88fe-3e324084beb0.png)

Chart object _after_:
![image](https://cloud.githubusercontent.com/assets/3185573/5220645/9ad3c64c-7668-11e4-9875-5b42c1ad0513.png)

**Comment by ragefuljoe** [comment]
This is exactly the issue I've been banging my head against last few days. I run my export once and it's fine, and the second time it errors. 

I'm adding the charts into an array in a service at the end of chartconfig, in the func: callback. Should I be using that getHighcharts funciton there?
