### ISSUE TITLE
Updating categories on x-axis doesn't work

### ISSUE THREAD

**Issue by grrtbrtr** [pablojim/highcharts-ng#226]
Hi,

I have a directive in which I use highcharts-ng.

We use the $watch to wait for data to be available.
Given that the data is dynamic and comes from the server, I can't know the categories upon setting the initial chart config.

This is the code inside the constructor for the directive.

Notice that the labels are never set to 'after' and 'after2'.

```javascript
var that = this;
var parsedData;

// Set initial chart config
this.$scope.chartConfig = {
    options: {
        chart: {
            type: that.$scope.chartType,
            zoomType: 'x'
        }
    },
    series: ["before", "before2"],
    loading: false,
    size: {},
    credits: { enabled: false },
    xAxis: {
        categories: []
    },
    yAxis: { min: 0 },
    title: { text: "" },
    subtitle: { text: "" }
};

this.$scope.$watch('chartData', function()
{
    if (that.$scope.chartData)
    {
        // Sort the data by x-axis
        if (that.$scope.columnSort)
        {
            that.$scope.chartData.items.sort(that.sortByProperty(that.$scope.columnSort));
        }
        that.$scope.title = $scope.chartData.name;

        if (that.$scope.columnGroup)
        {
            parsedData = that.parseDataMultiple(that.$scope.chartData, that.$scope.columnX, that.$scope.columnY, that.$scope.columnGroup);

        }
        else
        {
            parsedData = that.parseData(that.$scope.chartData, that.$scope.columnX, that.$scope.columnY);
        }

        // Update the chart config (highcharts-ng)
        that.$scope.chartConfig.series = parsedData.yValues;
        that.$scope.chartConfig.xAxis.categories = ["after1", "after2"];
        that.$scope.chartConfig.title.text = that.$scope.title;
    }
});
```

The watch listener does get executed, as the actual series are correctly rendered, the labels however do not get updated, despite the fact that they are being updated in the angular $scope.

Is it possible that the highchart does not refresh/redraw?

**Edit:**

I just found out that this probably causes the problem,
In the highcharts-ng watch expression for config properties, the newAxes and oldAxes seem to be equal (line 261):
```javascript
angular.forEach(axisNames, function (axisName) {
    scope.$watch('config.' + axisName, function (newAxes, oldAxes) {
        if (newAxes === oldAxes)
            return;
        if (newAxes) {
            chart[axisName][0].update(newAxes, true);
            updateZoom(chart[axisName][0], angular.copy(newAxes));
            chart.redraw();
        }
    }, true);
});
```

**Comment by jvanwinkle** [comment]
I'm getting the same thing. `newAxes` is always equal to `oldAxes` and never fires a redraw.

**Comment by raoabishay** [comment]
Try:
$scope.chartConfig.options.xAxis.categories = categories;

This worked for me.

**Comment by denislins** [comment]
I'm getting the same thing here. And the most strange thing is that I have another chart where updating the categories works with no problems at all.

Also, setting the categories in the `options` didn't help me.

**Comment by riyunoa** [comment]
I'm also getting the same issue, any update on a fix? Thank you.

**Comment by riyunoa** [comment]
Ok, I have a bit of a hack to update the xAxis.categories which works for me: 

````
$scope.chartConfig.xAxis.categories = ['asdf'];
var chart = $scope.chartConfig.getHighcharts();
chart['xAxis'][0].update($scope.chartConfig.xAxis, false);
chart.redraw();
````

**Comment by kalouantonis** [comment]
Is anyone still planning on fixing this?

**Comment by kalouantonis** [comment]
It looks like the issue has to do with (as @jvanwinkle said) `newAxes` always being equal to `oldAxes`. After further digging, I found that my issue was because the `oldAxes` value doesn't represent the actual axis values that are going to be rendered by the internal `chart` object.

Maybe we should remove the equality check all together or instead of comparing with `oldAxes`, we could compare with the `chart[axisName]` object itself.

Anyone have any ideas?

**Comment by KyleMcNutt** [comment]
+1 to @kalouantonis idea. This seriously tripped me up today and I was totally stuck trying to figure out why `oldAxes` and `newAxes` were the same.

`$watch` should only be fired by Angular when the actual value that you are watching changes. This is obviously different behavior than of `$observe` for example. I believe what we are seeing here is because the values are being set in different event loops Angular thinks that the value has "just appeared" and runs the watch with the same values for `oldAxes` and `newAxes`.

Tried to look into the history to determine if there was a specific reason for adding the equality check but didn't really see one. Would be interested if there was a specific reason.

I would love to see @kalouantonis's Pull Request get merged in soon, especially noting how old this issue is at this point.

**Comment by kalouantonis** [comment]
The pull request has been merged, can we marked this as closed? @pablojim

**Comment by pablojim** [comment]
Yes. Thanks all.

**Comment by gururajmca** [comment]
Hi Guys, I still have the same issue, where I could not able to update the chart type option which I read from the json service. But I could able to change the title of the chart..
Here is my controller code..

controller: function($scope, reportHttpService) {
                    console.log('I am here in controller' + $scope.widgetid);

                    $scope.highchartsNG = {
                        options: {
                            chart: {
                                type: ''
                            }
                        },
                        series: [
                            {
                                data: []
                            }
                        ],
                        title: {
                            text: ''
                        },
                        loading: false
                    };
                    $scope.initWidget = function() {
                        reportHttpService.getWidgetDataById($scope.widgetid)
                        .then(function(res) {
                            console.log(res.metadata.graph_type);
                            $scope.highchartsNG.options.chart.type = res.metadata.graph_type;
                            $scope.highchartsNG.series[0].data = res.widget_data;
                            $scope.highchartsNG.title.text = res.metadata.graph_title;
                            //$scope.highchartsNG = highchartsNG;
                        }, function(err) {
                            console.log(err);
                        });
                    }

                    $scope.initWidget();
                }

**Comment by gururajmca** [comment]
Hi Guys, I have found the work around for the above issue which i have mention past: Here is code, if any one has similar issue..

`mainApp.directive('myWidget', function() {
            function linkFunction($scope, elem, attrs) {
                $scope.chartTypeChange = function($type) {
                    $scope.highchartsNG.options.chart.type = $type;
                }
                $scope.remove = function(widget) {
                    $scope.$parent.remove(widget);
                };
            }
            return {
                restrict: 'A',
                replace: true,
                scope: { 
                    widget: '=',
                    widgetid: '='
                },
                templateUrl: '/index.php/widgets/myWidget.html',
                controller: function($scope, reportHttpService, $timeout) {
                    var highchartsNG = {
                        options: {
                            chart: {
                                type: ''
                            }
                        },
                        series: [
                            {
                                data: []
                            }
                        ],
                        title: {
                            text: ''
                        },
                        loading: false
                    };
                    $scope.initWidget = function() {
                        reportHttpService.getWidgetDataById($scope.widgetid)
                        .then(function(res) {
                            highchartsNG.options.chart.type = res.metadata.graph_type;
                            highchartsNG.series[0].data = res.widget_data;
                            highchartsNG.title.text = res.metadata.graph_title;
                            $timeout(function() {
                                $scope.highchartsNG = highchartsNG;
                            }, 100);
                            
                        }, function(err) {
                            console.log(err);
                        });
                    }

                    $scope.initWidget();
                },
                link: linkFunction
            }
        });`

and my DOM structure is

<div class="row">
	<highchart id="chart1" config="highchartsNG" class="span10"></highchart>
</div>

**Comment by varunis** [comment]
This issue is occurring again after I upgraded to version 0.0.12
