### ISSUE TITLE
highcharts map

### ISSUE THREAD

**Issue by angeliqueIcono** [pablojim/highcharts-ng#229]
Hi, 
I wanted to know if it's possible to do highmaps with your angular plugin, and if it's possible, how?

**Comment by tom-coefficient** [comment]
:+1:

**Comment by mathielen** [comment]
+1

**Comment by pablojim** [comment]
This is now added http://rawgit.com/pablojim/highcharts-ng/master/example/maps/example.html

**Comment by fizerkhan** [comment]
@pablojim example.html does not work. Can you please update? Also can you please add example code for world map instead of specific country?

**Comment by binarybaba** [comment]
@fizerkhan I guess it's because the its using angular 1.2.28 and the code's written in angular.component which is supported after Angular's 1.5.x ?
@pablojim is that right or am I missing something?
