### ISSUE TITLE
Solid Gauge chart losing series rendering on page/container resize [ng-highcharts + angular]

### ISSUE THREAD

**Issue by roydondsouza** [pablojim/highcharts-ng#230]
I have customized a solid gauge chart and it works fine when run on a simple html container

http://jsfiddle.net/roydondsouza/m4hzg181/

But after integrating it with angular and ng-highcharts the series data loses its rendering.

http://jsfiddle.net/roydondsouza/6hxaB/139/

Expected:
![](http://i.stack.imgur.com/1XGC4.png)

Result after resize: (Renders, but loses the rendering)
![](http://i.stack.imgur.com/zU1ka.png)

Details here: 
http://stackoverflow.com/questions/27311035/solid-gauge-chart-losing-series-rendering-on-page-container-resize-ng-highchart

**Comment by seiyria** [comment]
I'm also having this problem. @roydondsouza did you find a way around this?

**Comment by seiyria** [comment]
https://github.com/highslide-software/highcharts.com/issues/3708 Possible fix here.

**Comment by seiyria** [comment]
In fact, I can confirm that this fix works.

**Comment by roydon-tj** [comment]
@seiyria Thanks a lot for the link. Let me check and confirm this.

**Comment by roydondsouza** [comment]
@seiyria  Thanks a lot for the link. Let me check and confirm this.

**Comment by roydondsouza** [comment]
https://github.com/highslide-software/highcharts.com/issues/3708 fixes this issue. Thanks @seiyria

**Comment by pablojim** [comment]
Thanks @seiyria for looking into this and @roydondsouza for raising it!

**Comment by seiyria** [comment]
:+1:

**Comment by roydondsouza** [comment]
:) (Y)
