### ISSUE TITLE
Count visible lines

### ISSUE THREAD

**Issue by larssondaniel** [pablojim/highcharts-ng#234]
I'm trying to count the number of visible lines in a chart by looking at Series.visible.
This does, however, not seem to be updated from toggling the legends. 

Look at this fiddle from @pablojim: http://jsfiddle.net/pablojim/hpvmm93g/

If you toggle the legend for series 1 once, the hide/unhide button does not do anything the first time you click it, since the legend toggling did not actually change the value of this.chartConfig.series[0].visible.

**Comment by pablojim** [comment]
This seems ok to me - Is the problem still happening for you?
