### ISSUE TITLE
Highchart theme support

### ISSUE THREAD

**Issue by gayancc** [pablojim/highcharts-ng#239]
I'd like to see highchart-ng support theming 

Thanks

**Comment by ZaLiTHkA** [comment]
Have you tried using the [default method](http://www.highcharts.com/docs/chart-design-and-style/themes) for applying a theme? That worked perfectly for me.

**Comment by arsinawaz** [comment]
@ZaLiTHkA would you be kind to provide a fiddler?

**Comment by ZaLiTHkA** [comment]
@arsinawaz, I don't see how that would help you work it out; it is quite literally as simple as the documentation I linked to...

Keep in mind that this directive still loads Highcharts into the DOM as a global variable, so you can run `Highcharts` functions almost anywhere in your code. Just make sure you include your chosen theme configuration object and pass it to `Highcharts.setOptions()` to apply it.

Or, even simpler than that, simply load one of the [premade theme script files](https://github.com/highslide-software/highcharts.com/tree/master/js/themes), each of which include both the theme configuration and the command to apply it in one file.

**Comment by gayancc** [comment]
@ZaLiTHkA thanks for the info since highchart work as globally i came up with theming easily thanks

**Comment by Pinch1A** [comment]
is it possible set theme to specific highchart a theme and to another highcharts a different one?
