### ISSUE TITLE
options are not reflected in directives

### ISSUE THREAD

**Issue by yujiosaka** [pablojim/highcharts-ng#241]
options object is watched for change.
however, highcharts-ng does not reflects the values when it is used in directives.

In the [example](http://jsfiddle.net/yujiosaka/bqvpe2mj/2/), line has dash style as specified in options,
but it is not reflected when it's drawn.

**Comment by pablojim** [comment]
By using a controller function this seems to work: http://jsfiddle.net/Lnd8skdp/

Does this help?
