### ISSUE TITLE
Please add feature to sync xAxis zoom for multiple charts in ng-repeat

### ISSUE THREAD

**Issue by jeanpool407** [pablojim/highcharts-ng#243]
Thanks for your work on this, pablojim! 

I have a number of charts within a table using ng-repeat, all of which need to synchronize the xAxis on zoom and min/max. I've created a plunker here http://plnkr.co/edit/ZjJHKIpp9tgq6vSU657e?p=preview . Please let me know if this is possible or how to add functionality on my end for this.

Thanks again!

**Comment by ValentinH** [comment]
Your fiddle is broken now..

This is the solution I use to sync the xAxis zoom between 2 charts.

First, in the config on each chart:
```js
$scope.chart1 = {
	options: {
		chart: {
			events: {
				selection: function(event) {
					self.onZoomHandler(event, 'chart2');
				}
			}
		}
	}
}
```

then the custom handler:
```js
self.onZoomHandler = function(event, chartToUpdate) {
    var chart = $scope[chartToUpdate].getHighcharts();
    if (event.xAxis) {
        chart.xAxis[0].setExtremes(event.xAxis[0].min, event.xAxis[0].max);
        if (!chart.resetZoomButton) {
            chart.showResetZoom();
        }
    } else {
        chart.xAxis[0].setExtremes(null, null);
        if (chart.resetZoomButton) {
            chart.resetZoomButton = chart.resetZoomButton.destroy();
        }
    }
};
```

**Comment by fizerkhan** [comment]
@jeanpool407 Can you please share the code for synchronize multi chart in plunker?
