### ISSUE TITLE
Can't hide the export button

### ISSUE THREAD

**Issue by barretodavid** [pablojim/highcharts-ng#244]
I want to have a highchart directives with the ability to export the chart (showing the export button) and another without that option (not showing the export button) but I have not managed to disable (hide) the button using the configuration object:

```html
<div ng-app="app">
    <my-chart></my-chart>    
<div>
```

```javascript
var app = angular.module('app', ['highcharts-ng']);

app.directive('myChart', function(){
    return {
        restrict: 'E',
        scope: {},
        template: '<highchart config="chartConfig"></highchart>',
        link: function(scope, element, attrs) {
            scope.chartConfig = {
                options: {
                    exporting: {
                        enabled: false
                    }
                }
            };
        }
    };
});
```

Even if a disable the export property, the button is still there as you con see here: http://jsfiddle.net/davidbarreto/c2Lj14fq/

**Comment by pablojim** [comment]
duplicate #241
