### ISSUE TITLE
How to redraw highchart after change it's data?

### ISSUE THREAD

**Issue by Namdnitbk92** [pablojim/highcharts-ng#245]
Hi team! I have used highchart in my angular application but i have got a problem. After data has been changed after ajax loaded, the chart has not been redraw. 
My code is: 
js: 
olbius.controller('DashboardController',function($rootScope, $scope, $controller,DashboardService,InventoryService) {
    $.extend(this, $controller('BaseController', {
        $scope: $scope
    }));
//    $scope.chartSeries = [];
    $scope.chartSeries = [
                          
                        ];
    $scope.chartConfig = {
	            options: {
	                chart: {
	                	type: 'column',
	     	            borderColor: '#EBBA95',
	     	            borderWidth: 3,
	     	            height:220,
	     	   			 width:600
	                }
	            },
	            series:  [{
	                      data: $scope.chartSeries 
	            }]
	            ,
	            title: {
	                text: 'Tỷ lệ số lượng các SP đã bán(%)'
	            }
    };
    
    $scope.$on('$viewContentLoaded', function() {
    	$scope.setHeader("Thống kê", "/main", false);
        $scope.getDataPurchaseProduct();
	});
//    InventoryService.getTable().then(function(res){
//    	console.log(res);
//    });

		$scope.dataProduct = [];
		$scope.getDataPurchaseProduct =   function (){
		    	DashboardService.purchaseReportProduct().then(function(res){
		    		var productPurchaseArr = new Array();
		    		var productQuantity = new Array();
		    		var temp = new Array();
		    		var dataSet = new Array();
		    		var quantity = 0;
		    		var i = 0;//index
		    
				for ( var productReport in res["productQtyInfo"]) {	
					var quantity = parseFloat(res["productQtyInfo"][productReport]["quantity"]);
					productPurchaseArr.push(quantity);
					temp.push(productReport);
					i++;
				}
				var sum = 0;
				for (var j = 0; j < productPurchaseArr.length; j++) {
					sum += productPurchaseArr[j];
				}
				for (var j = 0; j < productPurchaseArr.length; j++) {
					productQuantity.push(((productPurchaseArr[j] / sum * 100).toFixed(2))/1);
				}
				for(var i=0 ;i<temp.length;i++){
					$scope.chartSeries.push({"name":temp[i],"data":[productQuantity[i]]});
				}
				console.log($scope.chartSeries);
//				$scope.chartSeries = $scope.dataProduct;
				
			
		    });
		    	
    };

});

html:
<highchart id="chart" config="chartConfig" ></highchart>

**Comment by pablojim** [comment]
Could you create a jsfiddle?

**Comment by typescripter** [comment]
Hi, should the code be $scope.chartConfig.chartSeries.push? You have $scope.chartSeries.push in your code.

I really like this this plugin btw, great job! :)

**Comment by Namdnitbk92** [comment]
:).Thanks Typescripter and pablojim,i really like this plugin too,and I fixed this problem then  add $scope.chartSeries.push...:D

**Comment by Namdnitbk92** [comment]
Thanks u so much :)

**Comment by pablojim** [comment]
Thanks @Namdnitbk92  and @typescripter

**Comment by Bclayson** [comment]
@Namdnitbk92 You said you fixed this problem. How?
