### ISSUE TITLE
xAxis.labels.format does not work

### ISSUE THREAD

**Issue by seiyria** [pablojim/highcharts-ng#246]
I've tried putting it on options.xAxis.labels.format, xAxis.labels.format, and probably other places. Any ideas?

For reference, this is strange because labels.rotation works just fine.

**Comment by gill0r** [comment]
Can you please create a jsfiddle?

Do you want to use `format` ([using highcharts 'template' engine](http://api.highcharts.com/highcharts#xAxis.labels.format)) or do you maybe want to use a function which returns the formatted label-string? Last one would be `formatter`. Just in case :)

**Comment by seiyria** [comment]
I want to use `format`. I'm making a chart editor that lets people change various details -- yAxis.format works, dataLabel.format works, but the xAxis one doesn't seem to. I can try to create a fiddle or something tomorrow.

**Comment by gill0r** [comment]
I quickly put one together and can't reproduce the problem. http://jsfiddle.net/wwtzqfh0/1/

**Comment by seiyria** [comment]
Strange, I'm pretty sure I tried this. I'll give it another try tomorrow and I'll post back. Thanks!

**Comment by seiyria** [comment]
You're right, it does work (I added an input to check out dynamically assigning it). I'm not sure what I'm doing, but at least I know it's not the library. Thanks.

**Comment by pablojim** [comment]
Thanks @gill0r

**Comment by seiyria** [comment]
This was actually due to us using https://github.com/blacklabel/grouped_categories for grouped categories support; spent way too long looking around for problems.
