### ISSUE TITLE
Update multiple yAxis labels

### ISSUE THREAD

**Issue by cosme-benito** [pablojim/highcharts-ng#247]
Hello, it is not currently possible to update multiple yAxis labels. I believe this happens because even though it detects yAxis changes correctly it always assumes there is only one yAxis when updating.
```
angular.forEach(axisNames, function (axisName) {
          scope.$watch('config.' + axisName, function (newAxes, oldAxes) {
            if (newAxes === oldAxes)
              return;
            if (newAxes) {
              chart[axisName][0].update(newAxes, false);
              updateZoom(chart[axisName][0], angular.copy(newAxes));
              chart.redraw();
            }
          }, true);
});
```

It should take into consideration multiple axis and possibly the need to create/remove axis. (eg: changing from 1 axis to 2 or vice-versa)

**Comment by dbujak** [comment]
I second this!

Example with 1 yAxis (changing label works): http://jsfiddle.net/dbujak/b9g5hemp/

Example with array of yAxis (changing labels doesn't work): http://jsfiddle.net/dbujak/dtfv4fgr/
