### ISSUE TITLE
Can't get 2nd Y-Axis to render correctly

### ISSUE THREAD

**Issue by andrewtnisbet** [pablojim/highcharts-ng#250]
Hi,
I am having some issues getting a 2nd Y-Axis to render, and I was hoping someone could tell me what I am doing wrong. I have stripped down the options to bare bones, troubleshooting this

JS Looks like this 
var options = {};
options.chart = {'type':  'areaspline','height': height, 'width': width};   // areaspline seems to give us the most flexibility
options.plotOptions = {'series': {'stacking':''}};
options.series = [];
options.title = {'text': null};
 options.xAxis = {title: {text: 'Date'}, type: 'datetime'};
 options.yAxis = [{title: {text: 'Primary'}, id: 'y1'},{title: {text: 'Secondary'}, id: 'y2'}];  
      compSeries = {name: 'comp', type: 'line', data: [[1387065600000,15],[1387152000000,10],[1387324800000,16]], yAxis:'y2'}; // have also tried 1 for the yAxis
           barSeries = {name: 'bar', type: 'column', data: [[1387065600000,1.5],[1387152000000,1.0],[1387324800000,1.6]]}; // have tried added yAxis:0  and yAxis: 'y1'  here 
options.series.push(barSeries);
options.series.push(compSeries);

$scope.chartConfig = options 

HTML 

highchart id="mainChart" config="chartConfig"  /highchart

Everything works fine with one y-Axis, but adding the 2nd axis gives me this 

 TypeError: Cannot read property 'length' of undefined
    at http://localhost:9010/bower_components/highcharts-release/highcharts.js:117:335
    at Array.forEach (native)
    at each.Array.forEach.g (http://localhost:9010/bower_components/highcharts-release/highcharts.js:22:165)
    at Object.na.adjustForMinRange (http://localhost:9010/bower_components/highcharts-release/highcharts.js:117:379)
    at Object.na.setTickPositions (http://localhost:9010/bower_components/highcharts-release/highcharts.js:121:43)
    at Object.na.setScale (http://localhost:9010/bower_components/highcharts-release/highcharts.js:127:34)
    at http://localhost:9010/bower_components/highcharts-release/highcharts.js:193:106
    at Array.forEach (native)
    at each.Array.forEach.g (http://localhost:9010/bower_components/highcharts-release/highcharts.js:22:165)
    at Object.Ya.redraw (http://localhost:9010/bower_components/highcharts-release/highcharts.js:193:88)
angular.js:9959 Highcharts error #18: www.highcharts.com/errors/18

running: 
"highcharts.com": "~4.0.4",
"highcharts-release": "~4.0.4",
 "highcharts-ng": "~0.0.7"

Anyone have ideas on what I am doing wrong here? 

Thanks

**Comment by pablojim** [comment]
I've just merged some changes. Could you retest on the latest src version?

**Comment by andrewtnisbet** [comment]
Gave it a go, but no luck, still seeing the same problem.

**Comment by roydondsouza** [comment]
@andrewtnisbet can you create a jsfiddle for this

**Comment by andrewtnisbet** [comment]
Apologies, I have been preoccupied with another project, I will try and get a fiddle put together as soon as I can.

**Comment by roydondsouza** [comment]
No problem @andrewtnisbet  , if you are still looking for a solution, create a jsfiddle when ever you find time and post it here, will see what we can do. Thanks
