### ISSUE TITLE
Can't use 3d Chart

### ISSUE THREAD

**Issue by Namdnitbk92** [pablojim/highcharts-ng#251]
Hi Team,my code: 

 $scope.chartConfig1 = {
            options: {
                chart: {
                	type: 'column',
     	            borderColor: '#EBBA95',
     	            borderWidth: 3,
     	            height:220,
     	   			 width:600,
     	   			options3d: {
                        enabled: true,
                        alpha: 15,
                        beta: 15,
                        depth: 50
                    }
                },
                plotOptions: {
                	series: {
                        dataLabels: {
                            enabled: true,
                            format :'{y} %',
                            style: {
                                fontWeight: 'bold'
                            },
                            borderRadius: 5,
                            backgroundColor: 'rgba(252, 255, 197, 0.7)',
                            borderWidth: 1,
                            borderColor: '#AAA',
                            
                            }
                        }
                    }
                },
            
            series: orderAmountPercent
            ,
           
            xAxis: {
                opposite: true
            },
            title: {
                text: 'Olbius'
            }
};
orderAmountPercent loading data from Ajax.I don't see 3D in chart?please,help me.Thanks all.

**Comment by pablojim** [comment]
jsfiddle please

**Comment by mketevi** [comment]
Hello did you add a reference highcharts-3d.js into your code??

**Comment by pablojim** [comment]
Hi closing this. Feel free to reopen if you can provide more details ideally a jsfiddle showing the problem.
