### ISSUE TITLE
Custom loading message 

### ISSUE THREAD

**Issue by zazasa** [pablojim/highcharts-ng#252]
Hi,
It works when I set loading true:
```javascript
$scope.chartConfig.loading = true;
```

but Im not able to set a custom msg as specified in the Readme.md
>//Boolean to control showng loading status on chart (optional)
>//Could be a string if you want to show specific loading text.
>loading: false,

this still show 'Loading...'

```javascript
$scope.chartConfig.loading = 'No Data.';
```

**Comment by pablojim** [comment]
jsfiddle please

**Comment by zazasa** [comment]
Ok, I've found that this depend on the version. 
The one installed by bower is the 0.0.7 and have this issue, but if I load the lib from here:

https://rawgit.com/pablojim/highcharts-ng/master/src/highcharts-ng.js

it works.

**Comment by pablojim** [comment]
It shall be included in the next release

**Comment by zazasa** [comment]
Sorry, ir seems not working any more.

http://jsfiddle.net/ukxxwa5j/

**Comment by KieranDotCo** [comment]
You can resolve this by wrapping the loading message in $timeout 0.

See updated fiddle - http://jsfiddle.net/ukxxwa5j/2/

Hope this helps somebody
