### ISSUE TITLE
Two highcharts in the same controller

### ISSUE THREAD

**Issue by iMomen** [pablojim/highcharts-ng#257]
Hello, 
I use highcharts-ng to draw two different charts but i already do this in the same controller ..
How can i pass the ID of the required div to the config?

**Comment by mohammadumairkhan** [comment]
Hey @iMomen 

You can use the highcharts-ng directive with different models defined on the controller. You will not need the id of the div. Just pass in the different model where you need to.

**Comment by iMomen** [comment]
I already find the solution thank you :100: 
You can do this by using different Chartconfig names

**Comment by roydondsouza** [comment]
@iMomen cool. Since its solved, we can close this issue now. @pablojim
