### ISSUE TITLE
some integration problem

### ISSUE THREAD

**Issue by GowrishankarGeek** [pablojim/highcharts-ng#258]
I am working with your plugin but i face following issues, 1. General Drawing shown as blank 2. Column chart displayed as line chart. I would like to know, is possible to do in this plugin? If so, Help me out here for integration.

**Comment by ValentinH** [comment]
For the Column chart, how do you set it? I have it working...

The best would be that you provide a fiddle for each case. ;)

**Comment by pablojim** [comment]
Closing - feel free to reopen if you have more  information and ideally a jsfiddle showing the problem.

**Comment by Bclayson** [comment]
@pablojim I've noticed that 80% of the 'chart not showing' or 'not redrawing' have to do with the column or bar chart. I too have had this problem. When I attempt to set a drilldown (in options) from an ajax call it won't render it. When I change bar type to pie, it works just fine.
