### ISSUE TITLE
What is the purpose of disabling navigator?

### ISSUE THREAD

**Issue by RPGillespie6** [pablojim/highcharts-ng#259]
In `highcharts-ng.js`:

```
var defaultOptions = {
        chart: {
          events: {}
        },
        title: {},
        subtitle: {},
        series: [],
        credits: {},
        plotOptions: {},
        navigator: {enabled: false} //line 91
      };
```

I'm wondering why `navigator` here has a hard-coded `false` default value for `enabled`, especially because according to the [Highstock API](http://api.highcharts.com/highstock#navigator.enabled) it should have a default value of `true`? Why not just let Highstock decide what the default value should be?

**Comment by Robinson7D** [comment]
It why says in the README, 
"When using with a highstocks navigator errors can occur"

https://github.com/pablojim/highcharts-ng/blame/master/README.md#L116

**Comment by RPGillespie6** [comment]
Do we have any of these error scenarios? How can I trigger an error with navigator enabled? I'd like to get this debugged, but so far I haven't been able to produce any errors with the navigator enabled.

**Comment by pablojim** [comment]
I think it was related to switching between HighStocks and Highcharts - which is a pretty edge scenario...
