### ISSUE TITLE
Open Question, bower integration

### ISSUE THREAD

**Issue by cRotermund** [pablojim/highcharts-ng#262]
More of an open question- not so much an issue.

I currently pull highcharts-ng down through bower for a project I am working on.  The latest version on bower is 0.0.7.  Unfortunately this version does not provide access to the function config.getHighcharts(), which is critical to my implementation.

When will this function be released in a version available for management through bower?  In the mean time I can pull the 0.0.8-dev version right off git and manage manually, but obviously would prefer bower to handle it.

Thanks!

**Comment by pablojim** [comment]
Hi, The next release will be out shortly. Similar functionality can be achieved with the func callback to access the chart object.

**Comment by cRotermund** [comment]
Alright, sounds good.  I appreciate the hard work, and the directive is very nice and easy to use!  Keep up the good work!
