### ISSUE TITLE
Is there any function to remove a plotBand?

### ISSUE THREAD

**Issue by xmes3** [pablojim/highcharts-ng#263]
Hi every one,

I'm using higcharts-ng and I need to add and remove plotBands depending on user actions.

I can use the next code to plot a new band on the chart:

```javascript
var newBand = {
    color: '#FF4000',
    from: 3.5,
    to: 4.5
};
$scope.chart.xAxis.plotBands.push(newBand);
```

But I didn't found an analog function to remove it. I tried to remove it by id like in this [fiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/axis-removeplotband/). At the moment I need to redraw all the plotBands to remove one of them.

So, is there any function to remove a plotBand?

Thanks.

**Comment by roydondsouza** [comment]
Does this help? http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/xaxis/plotbands-id/

**Comment by xmes3** [comment]
Hi, thanks for your answer but this is the same fiddle I wrote in the
question.

Removing it by id works fine in js, but I need to remove it in an Angular
enviroment.

Thanks

2015-02-02 10:33 GMT+01:00 roydondsouza <notifications@github.com>:

**Comment by pablojim** [comment]
Could you create a jsfiddle with what you are trying and I'll have a look?

**Comment by ValentinH** [comment]
I'm not sure that you want to remove it by ID or this is just for the JQuery example but if so, you can use the getHighcharts() method to get the actual chart object:

```js
$scope.removePlotBand = function(id) {
  var chart = $scope.chartConfig.getHighcharts();
  chart.xAxis[0].removePlotBand(id);
} 
```

*This method is not available on last release (0.0.7) but only on current sources.*

**Comment by xmes3** [comment]
I found the solution in a standard javascript function : splice()

**to add a new band:**
```javascript
var newBand = {
    color: '#FF4000',
    from: 3.5,
    to: 4.5
};
$scope.chart.xAxis.plotBands.push(newBand);
```

**to remove a existing band:**
```javascript
$scope.chart.xAxis.plotBands.splice(bandPositionToBeRemoved,1);
```

I am sorry to have wasted your time due to my lack of knowledge of javascript.
:sweat: 

Thank you very much.

**Comment by pablojim** [comment]
No problem. Glad you found a solution.
