### ISSUE TITLE
Chart drawing problem with Angular 1.3

### ISSUE THREAD

**Issue by ValentinH** [pablojim/highcharts-ng#268]
After updating my angular to 1.3, I noticed some troubles with the first draw of my charts.
Indeed, I'm showing my chart and adding data to it at runtime and it seems to be a problem with the new version of Angular.

The legend is broken and the chart is generally weirdly drawn.

See these example:
- With latest Angular 1.2 (1.2.27): http://jsfiddle.net/5kazz1c9/ (Working)
- With Angular 1.3.0: http://jsfiddle.net/5kazz1c9/1/ (Broken)

A simpler example (also broken), that simply adds some series before showing the chart:
http://jsfiddle.net/5kazz1c9/2/

So far, I have tried to place the initChart() function of highcharts-ng in a $timeout call to be sure it is run after the DOM is initialized. It works for the drawing problem but there is then some troubles with the chart not filling its parent Div.

**Comment by eduardopopego** [comment]
Hi,

I'm no expert but removing ng-show (or changing the default value to true) fixes the issue with the legend. In general, I've had trouble with Highcharts and CSS's "display: none !important" selectors on parent elements, used by the ngHide directive (https://docs.angularjs.org/api/ng/directive/ngShow).

Perhaps you could try overriding the default ngHide with the alternative method and test it.

I had a similar problem working with Angular-UI's tabs, which relied on the display hidden property to work. 

Good luck! Hope it helps

**Comment by ValentinH** [comment]
ng-show is a native feature of Angular and the use-case presented in the fiddle worked in 1.2 so it should work also in 1.3 without needing to remove ng-show...

**Comment by pablojim** [comment]
@ValentinH  That fiddle seems to work ok for me. Are you still having the problem

**Comment by ValentinH** [comment]
Indeed it works correctly now :) A recent commit has fixed it even if I don't know which one.

**Comment by ValentinH** [comment]
Actually it is pretty weird because the fiddle is fixed with the current version of highcharts-ng but the charts in my app are still broken if I don't add the series in a timeout... I'll try to reproduce it on a jsfiddle.
