### ISSUE TITLE
Resizing solid gauge

### ISSUE THREAD

**Issue by larssondaniel** [pablojim/highcharts-ng#269]
It seems like the filled in part of a solid gauge gets disconnected from the rest of the gauge during resizing of the window.

Fiddle with highcharts-ng, with bug: http://jsfiddle.net/6hxaB/3/

Fiddle with highcharts, without bug: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-solid/

**Comment by pablojim** [comment]
is this related #230

**Comment by larssondaniel** [comment]
It might be related, I'll try the patch and let you know if it fixes the issue.

Thanks.
