### ISSUE TITLE
Chart Title

### ISSUE THREAD

**Issue by neuzebe** [pablojim/highcharts-ng#270]
"Chart Title" shows up by default as the chart's title before my chart loads, is there anyway to stop this behaviour?

**Comment by RPGillespie6** [comment]
Yeah, set the default value to something else in your `chartOptions`

**Comment by neuzebe** [comment]
Is chartOptions in javascript or is it something I can apply on the <highcharts> tag itself?

**Comment by RPGillespie6** [comment]
chartOptions is a scope object defined in the tag and implemented wherever you want (most likely in the controller):

`<highchart config="chartConfig"></highchart>`

maps to

`$scope.chartConfig = {}` in your controller

and 

`<highchart config="foobar"></highchart>`

maps to 

`$scope.foobar = {}` in your controller

Of course, if you wanted, you could map a textbox to `chartConfig.title` using `ng-model` and just type the title into the textbox.

**Comment by neuzebe** [comment]
Understood, thank you.
