### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by Antiplod** [pablojim/highcharts-ng#275]
My limited understanding of angular leads me to believe that the following lines :

            scope.$on( 'highchartsng.reflow', function()
            {
               chart.reflow();
            } );

            scope.$on( '$destroy', function()
            {

should read:

            scope.deregFnc = scope.$on( 'highchartsng.reflow', function()
            {
               chart.reflow();
            } );

            scope.$on( '$destroy', function()
            {
               scope.deregFnc();

in order to avoid a cumulative resource leak.

**Comment by pablojim** [comment]
Again with limited understanding, I don't think this is necessary: http://stackoverflow.com/questions/22169888/angular-js-destroy-event-should-i-manually-unbind

Happy to revisit if you can demonstrate a problem. Thanks for raising this.
