### ISSUE TITLE
chore: Do a new release

### ISSUE THREAD

**Issue by TomNeyland** [pablojim/highcharts-ng#278]
```0.0.8``` looks to have enough improvements that it would be worth doing [another tagged release](https://github.com/pablojim/highcharts-ng/releases).

**Comment by TomNeyland** [comment]
#277 would need to be merged first

**Comment by ruzz311** [comment]
+1

**Comment by ruzz311** [comment]
and possibly publish to npm?

**Comment by TomNeyland** [comment]
@pablojim any chance for this? I'd love to go back to pointing my project at a versioned release rather than a commit.

**Comment by paradox41** [comment]
+1

**Comment by pablojim** [comment]
Done! Thanks for the prompting @TomNeyland @ruzz311 @paradox41
