### ISSUE TITLE
How to use addPoint

### ISSUE THREAD

**Issue by antonioperic** [pablojim/highcharts-ng#279]
Hi, i want to use graphs in real time. problem is that i want to add new point and remove first one, now with array.push it is just adding new point. Is there way to use addPoint?

thnx

**Comment by pablojim** [comment]
Could you use `array.shift` to remove the first point?

**Comment by antonioperic** [comment]
Tried that but is looks sloppy

**Comment by pablojim** [comment]
You have an array of data. You want to add a point and remove the first one. Using `array.push` and `array.slice` seems natural to me. 

Indeed, having an array of data and changing it with vanilla js methods with the graph automagically updating to reflect the changes is one of the main goals of this directive.

You can get access to the underlying series with `chartConfig.getHighcharts()`. But I would not recommend adding points with this as the array and chart will then be out of sync.

**Comment by antonioperic** [comment]
Will try again in morning and give you feedback
-- 
Antonio Perić-Mažar, mag.comp.ing
CEO @ Locastic - we help clients develop amazing web and mobile apps
 
Mob: +385 98 813 684
Skype: antonio.peric
 
Stinice 12/II - 21000 Split - Croatia
Tel: +38521 782 059
www.locastic.com <http://www.locastic.com/>
 
Facebook  <http://facebook.com/Locastic> -  Twitter  <http://twitter.com/Locastic> -  Google+  <http://google.com/+Locastic> -  Linkedin <http://linkedin.com/company/Locastic>

**Comment by pablojim** [comment]
Please reopen if you are still having problems

**Comment by loorinm** [comment]
Hi, I am having the same issue. When I use the vanila js method 'shift' on my series data to remove the first point, the animation on the graph looks bad. Highcharts has the function 'addPoint', which comes with options for 'shift' and 'animation'. http://api.highcharts.com/highcharts#Series

The question is: How can I access those options if I'm using your directive.

**Comment by topwood** [comment]
+1

**Comment by ruisebastiao** [comment]
+1

**Comment by ruisebastiao** [comment]
Here is my solution for using addPoint function, and is working flawlessly 
```
 $scope.chart_realtimeForceConfig = {
        options: {
            chart: {
                type: 'line',
            },
            plotOptions: {
                series: {
                    animation: false                                
                },               
            },           
        },
        series: [
            {
                name: 'Fx',
                data: []          
            },          
        ],
        func: function(chart) {
            $timeout(function() {
                chart.reflow();
                $scope.highchart = chart;
            }, 300);

            socket.on('ati_sensordata', function(data) {
                if (data) {
                    var splited = data.split('|');
                  
                        if (splited.length >= 6) {
                            var val = parseFloat(splited[5]);
                            var shift = chart.series[0].data.length > 100;
                            chart.series[0].addPoint(val, true, shift, false);
                        
                    }
                }
            });


        },
        loading: false
    }
```
