### ISSUE TITLE
Line chart JSON with Date

### ISSUE THREAD

**Issue by enkac01** [pablojim/highcharts-ng#280]
Hey

I want to make a line chart from this JSON, but i only want to show 'pulse' with the date on the X-Axis.
Do i need to make a function to make an array with all the values or ? is there any easier way to handle this.   
Can someone help or show me and example
Thanks :)
[{
                    "owner": 1,
                    "pulse": 95,
                    "oxygen": 98,
                    "fev1": 4.4,
                    "temperature": 38.4,
                    "question1": false,
                    "question2": false,
                    "question3": false,
                    "status": 3,
                    "date_created_on_client": "2014-12-16",
                    "date_saved_on_server": "2014-12-16",
                    "client_id": 235,
                    "id": 202
                },
                {
                    "owner": 1,
                    "pulse": 95,
                    "oxygen": 98,
                    "fev1": 4.4,
                    "temperature": 37.4,
                    "question1": true,
                    "question2": true,
                    "question3": true,
                    "status": 2,
                    "date_created_on_client": "2014-12-17",
                    "date_saved_on_server": "2014-12-16",
                    "client_id": 235,
                    "id": 202
                },
                {
                    "owner": 1,
                    "pulse": 95,
                    "oxygen": 98,
                    "fev1": 4.4,
                    "temperature": 37.4,
                    "question1": false,
                    "question2": false,
                    "question3": false,
                    "status": 1,
                    "date_created_on_client": "2014-12-18",
                    "date_saved_on_server": "2014-12-16",
                    "client_id": 235,
                    "id": 202
                },
                {
                    "owner": 1,
                    "pulse": 95,
                    "oxygen": 98,
                    "fev1": 4.4,
                    "temperature": 39.4,
                    "question1": false,
                    "question2": false,
                    "question3": false,
                    "status": 1,
                    "date_created_on_client": "2014-12-19",
                    "date_saved_on_server": "2014-12-16",
                    "client_id": 235,
                    "id": 202
                }]

**Comment by pablojim** [comment]
You'll need to make an array with the values. 

```
var myData = ...
pulse = _.pluck(myData, 'pulse')
```
requires underscore/lodash...


Of course you could use vanilla js too!
