### ISSUE TITLE
Problem return data from WebApi2 Controller

### ISSUE THREAD

**Issue by tobiashoeft** [pablojim/highcharts-ng#281]
Hey There! My Problem is that i return [[1325376000000.0,0.0],[1325376060000.0,0.0],[1325376120000.0,0.0],[1325376180000.0,0.0],[1325376240000.0,0.0],[1325376300000.0,0.0],[1325376360000.0,0.0],[1325376420000.0,0.0],[1325376480000.0,0.0],[1325376540000.0,0.0]] to my <highchart> from below Controller ( WebApi2 ) Asp.net Json.net (serialisier):
[code]
 [Route("")]
    public IHttpActionResult Get()
    {
        var value = GetSample();
        return Ok(value);
    }
    private string GetSample()
    {
        var data = new List<object[]>();
        DateTime start= DateTime.Parse("01.01.2012 00:00:00");
        DateTime end= DateTime.Parse("03.01.2012 00:00:00");
        using (SqlConnection connection = new SqlConnection(WebConfigurationManager.ConnectionStrings["XXXXX"].ConnectionString))
        using (SqlCommand cmd = connection.CreateCommand())
        {
            var Chart1Table = new DataTable();
            connection.Open();
            cmd.CommandText = String.Format("SELECT Datum_Zeit, {0} FROM XXX WHERE (Datum_Zeit >= '{1}') AND (Datum_Zeit < '{2}') AND USER='{3}'", "X", start, end, "XXXX");
            cmd.Connection = connection;
            var reader = cmd.ExecuteReader();
            Chart1Table.Load(reader);
            for (var i = 0; i < Chart1Table.Rows.Count - 1; i++)
            {
                var datum_zeit = (DateTime)Chart1Table.Rows[i][0];
                var akt_wert = (double)Chart1Table.Rows[i][1];
                object[] test = { MilliTimeStamp(datum_zeit), akt_wert };
                data.Add(test.ToArray());
            }
        }

        return JsonConvert.SerializeObject(data.ToArray());
    }
    public double MilliTimeStamp(DateTime TheDate)
    {
        DateTime d1 = new DateTime(1970, 1, 1);
        DateTime d2 = DateTime.SpecifyKind(TheDate, DateTimeKind.Utc);
        TimeSpan ts = new TimeSpan(d2.Ticks - d1.Ticks);
        return ts.TotalMilliseconds;
    }
[/code]
My $http.get Method 

http.get('api/Chart').success(function (jsonData) {
        var test1 = new Array();
        test1 = jsonData;
        console.log(test1);
        var data = [
            { name: "first", data:  test1  }
        ];
        $scope.chartConfig.series = data;
    });

The Highstockchart dont shown up any data just empty.

If i post that manually via copy past from jsonresult into "data:" it works :( 

Can anyone help me?

**Comment by tobiashoeft** [comment]
Just return object [][] thats what i want! 

Another question the json that was coming back i huge so my hole site i lasy any tipps for doing it?

**Comment by pablojim** [comment]
Not sure I have the WebApi2 knowledge for this and it's not really related to the highcharts-ng.
