### ISSUE TITLE
chore - Create examples for highmaps

### ISSUE THREAD

**Issue by pablojim** [pablojim/highcharts-ng#282]
Create and link to highmaps examples

**Comment by pablojim** [comment]
Anyone want to help with this? @TomNeyland @dmitruk

**Comment by TomNeyland** [comment]
@pablojim If I have some free time this weekend I can take a look into throwing one together

**Comment by pablojim** [comment]
Thanks @TomNeyland  - @dmitruk already put a nice one together.

**Comment by TomNeyland** [comment]
Cool!
