### ISSUE TITLE
Very strange bug with highmaps

### ISSUE THREAD

**Issue by mathielen** [pablojim/highcharts-ng#285]
I use the default continent-map from highmaps. When I have values for 5 continents, everything is working just fine. Until I add a sixth value. Now the chart disappears.

Any idea?
http://jsfiddle.net/mathielen/szo6cwkL/1/

The original (without highcharts-ng) is working just fine:
http://jsfiddle.net/mathielen/rLrqvLc1/1/

Thanks for any help!

**Comment by mathielen** [comment]
No highcharts-ng problem, but a highcharts one.
See https://github.com/highslide-software/highcharts.com/issues/3940

**Comment by pablojim** [comment]
Thanks - I had no idea how I was going to fix this one ;-)

**Comment by mathielen** [comment]
This is so weird...
Maybe the geojson file of the map is broken - or there is really a strange bug in highcharts...

Anyway, Thanks for the great ng wrapper!

**Comment by pablojim** [comment]
Interestingly it should work anyway with the plugin. Ideally on initialization the plugin should add the series to the config and then create the chart,. But currently it creates a blank chart and then calls addSeries. 

But that's something to fix another time!
