### ISSUE TITLE
Setting className has no effect.

### ISSUE THREAD

**Issue by ben-crowhurst** [pablojim/highcharts-ng#286]
scope.chartConfig = {
    options: {
      chart: { type: 'line' },
      xAxis: { type: 'datetime' }
    },
    title: { text: 'Weather Forecast' },
    className: 'MY-SPECIAL-DESIGN'
  };

**Comment by pablojim** [comment]
Try move it into the options? Create a jsfiddle and I could have a look

**Comment by shanSyapse** [comment]
chart: { type: 'line', className: 'MY-SPECIAL-DESIGN' },
