### ISSUE TITLE
Error: Invalid value for <text> attribute x="NaN"

### ISSUE THREAD

**Issue by TAMMENY** [pablojim/highcharts-ng#288]
html:
＜highchart config="chartConfig"＞＜/highchart＞
js:
rest.query("jobs", {limit: 0})
.then(function (response) {
$scope.chartConfig={...}
});

When i put the $scope.chartConfig into the function, the chrome console will throw out "Error: Invalid value for attribute x="NaN"", but the chart is normal. However, when i put $scope.chartConfig out of the function, the error was no longer being thrown.

If you know how to solve this problem, please let me know, thank you.

**Comment by pablojim** [comment]
Could you create a jsfiddle showing the problem?

**Comment by TAMMENY** [comment]
@pablojim I defined a default value for $scope.chartConfig, then update this value in rest function. As far as I'm concerned, the issue is over and done with. Thank you.

**Comment by pablojim** [comment]
Thanks
