### ISSUE TITLE
v0.0.8 failing for internet explorer 9.

### ISSUE THREAD

**Issue by bhtek** [pablojim/highcharts-ng#289]
hi,

something in 0.0.8 is stopping the charts from rendering in ie 9 (9.0.8112.16421)...

i tried reverting to 0.0.7 and it works okay...

interesting to note though, w/ 0.0.8 and IE 9, it works if i open F12...
it continues to work even after i close the developer console... until i restart IE.

**Comment by pablojim** [comment]
Interesting. Let me know fi you can find the specific error.

**Comment by seadour** [comment]
@bhtek Did you ever find out anything more about this particular issue?

**Comment by bhtek** [comment]
I am afraid not. Sorry.
