### ISSUE TITLE
Extern Ajax request

### ISSUE THREAD

**Issue by kabus202** [pablojim/highcharts-ng#292]
Hello all,

I have trouble with loading extern data into the graph. 

See my code below:

console.log(weight);
      //weight = JSON.parse(weight);
       
       

      $scope.chartConfig = {
        options: {
            chart: {
                type: 'line',
                zoomType: 'x'
            }
        },
        series: [{
            data: $scope.weight
        }],
        

        title: {
            text: 'Hello'
        },
        xAxis: {
          
           
        },
        loading: false
    }

im using http.get to get my data. when i do a console.log and paste the in to the graph, it's working all fine.
$http.get('api/')
  .success(function(jsonData){

I also tried to load the series afterwards

   $scope.chartConfig.series.push({
            data:  ($scope.weight)
        })

I can see the serie names, but no data. Can someone explain to me why my chart is empty?

Kind regards,
Lokman

**Comment by pablojim** [comment]
Could you make a jsfiddle?
