### ISSUE TITLE
printing pie's dataLabels numbers with commas

### ISSUE THREAD

**Issue by Danny-weebo** [pablojim/highcharts-ng#298]
hey, I'm trying to print numbers with commas (showing 9,000 instand of just 9000), this is the way I'm setting the format
```format: '{point.name}: {point.y}'```

I cant find a way to get `{point.y}` into a function that will return the wanted result, 
I tried this way ```format: '{point.name}: '+ numberWithCommas(point.y)``` but then of course `point is not defined` I'm not sure how to handle it,
any direction how can I make it work ?

thanks

**Comment by pablojim** [comment]
This sounds like a highcharts question maybe try on the highcharts forum/stackoverflow.
