### ISSUE TITLE
Charts being removed immediately when angular view is being destroyed?

### ISSUE THREAD

**Issue by Jorenm** [pablojim/highcharts-ng#302]
I've got a div with a bunch of charts in it that is conditionally shown with an ng-if

I'm using ng-animate to fade and slide the div in/out. When it's added, the transition works perfectly, but when it's removed the charts all disappear immediately, while the transition plays out.

Is this something highcharts-ng is doing? Perhaps it's not respecting the delay ng-animate uses to transition out elements.

**Comment by Jorenm** [comment]
Ok I don't know if this is the right way to fix it, but I can't find a way to detect when the animation finishes. Here's what I did @ line 379:

        scope.$on('$destroy', function(event) {
          if (chart) {
            element.on('remove', function() {
              element.off('remove');
              try{
                chart.destroy();
              }catch(ex){
                // fail silently as highcharts will throw exception if element doesn't exist
              }
            });
          }
        });

So, when angular removes the element, destroy the chart.

**Comment by danendt** [comment]
Thanks, Jorenm. Works great! This should be integrated into the release
