### ISSUE TITLE
Highcharts resize issue with Angularjs

### ISSUE THREAD

**Issue by sajeetharan** [pablojim/highcharts-ng#303]
In my dashboard application am using highcharts to generate charts, Which works fine. I have embedded the charts inside a div and assigning an id for the chart. It generates the chart. I am using resizeable directive to resize the chart whenever user resizes div. But

var chart1 = chart.highcharts(); 

Throws an error saying "Uncaught TypeError: undefined is not a function".This worked before some days. Is there any dependency issue? here is the HTML and Directive.

html:

<md-card-content>                  
   <highchart   id="{{widget.id}}" config="widget.chartConfig">
   </highchart>
</md-card-content>

routerApp.directive('resizeable', function() { 
  return { 
    restrict: 'EA', 
    link: function(scope, element, attrs) { 
      $(element).resizable({ 
        resize: function(event, ui) {     
          var  widgetId = attrs.identifier; 
          var chart = $('#'+widgetId);  
          var chart1 = chart.highcharts();
          height = ui.size.height - 100;
          width = ui.size.width - 40;
          chart1.setSize(width, height, doAnimation = true);

           jsPlumb.repaint(ui.helper); 
        }, 
        handles: "all" 

      }); 
    } 
  }; 
});

![issue](https://cloud.githubusercontent.com/assets/4833351/7066575/aa4a51fe-dee1-11e4-9b6b-423d421fd558.png)

**Comment by pablojim** [comment]
Have you tried instead of calling setSize to instead set the size in the chartConfig?

**Comment by sajeetharan** [comment]
yes when we set in config. it works fine. My bropblem is i want to resize the chart dynamically when we resize the container as well

**Comment by pablojim** [comment]
Could you just update the config to change it dynamically? It's watched for changes.

**Comment by sajeetharan** [comment]
how to do that? i have added the necessary code and screen shot

**Comment by OrganicCat** [comment]
Wait, what was the resolution to this issue?

**Comment by GowrishankarGeek** [comment]
![imageedit_2_6056617327](https://cloud.githubusercontent.com/assets/7455943/19676799/d414df74-9ab3-11e6-9c68-a0b57f0156e0.gif)

Hello i an using highcharts with angularjs..charts not fit in bootstrap class
