### ISSUE TITLE
Is there any way we can make high charts labels selected when push the tab button on keyboard?

### ISSUE THREAD

**Issue by rkori215** [pablojim/highcharts-ng#304]
Hi i was trying to create some bar charts  i need a feature like when the user press the tab button on key board as like it selecting all html elements in application i want it to be select labels also is there any way to do it using high charts in angularjs application.?

**Comment by pablojim** [comment]
Probably best to look into the highcharts api. Anything that is possible with that should be possible with highcharts-ng also.
