### ISSUE TITLE
Get svg from highcharts angular js directive?

### ISSUE THREAD

**Issue by rkori215** [pablojim/highcharts-ng#307]
Hi in jquery we use chart.getSvg() to get svg from high charts but how we can get that function working in angular highcharts.??

Thanks..

**Comment by pablojim** [comment]
Yes you can use chart.getSvg. you just need to get a reference to the chart using ```chartConfig.getHighcharts()```. See the print button in : http://jsfiddle.net/pablojim/m4pcpv5g/
