### ISSUE TITLE
Animation doesn't works with HighStock and navigator enabled

### ISSUE THREAD

**Issue by gyss** [pablojim/highcharts-ng#308]
Hi,
I've just found a problem with HighStock when the navigator is enabled. As you can see in the examples below, the animation stops working for the main chart.

The problem comes with this option:

``` javascript
navigator: {
   enabled: true
}
```

Here is enabled:
http://jsfiddle.net/na8nknad

And here disabled. 
http://jsfiddle.net/na8nknad/1/

**Comment by Telemakhos** [comment]
Same problem here... animation is not working.. Any fix/workaround?
