### ISSUE TITLE
Scatter Charts and Bubble Charts  have lines

### ISSUE THREAD

**Issue by echasin** [pablojim/highcharts-ng#310]
I am trying to integrate Highcharts with a jhipster generated application.  I have recreated the example highcharts.com scatter chart.  It renders but incorrectly.  Same issue with bubble.  Only css used 

<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />

 Any thoughts would be appreciated. Thx in advance.

![highcharts_scatter](https://cloud.githubusercontent.com/assets/2588838/7375239/3bf50262-eda5-11e4-8b6f-2e125aa78ba7.PNG)

**Comment by pablojim** [comment]
Jsfiddle please

**Comment by echasin** [comment]
Thx, for the response.  I tried it again an the chart works,  but the legend does not display.

https://jsfiddle.net/echasin/cd220q76/1/  see  the original http://www.highcharts.com/demo/scatter

**Comment by echasin** [comment]
Accidentally closed the issue..oops

**Comment by Vivihung** [comment]
I sometime see this behavior when using highcharts. My work around is to short series data by the value of x-axis. Not sure if this can help.

**Comment by pablojim** [comment]
http://jsfiddle.net/6j9kfggd/ how's this?

**Comment by Rafi993** [comment]
this issue still seems to exist and both the fiddle does not work.

**Comment by pablojim** [comment]
@Rafi993 please see the changes in 1.0.0 documented on the faq. If you are still having issues please open a new issue.

**Comment by mikepsinn** [comment]
@Vivihung What do you mean by "short series data by the value of x-axis"?  Thanks!

**Comment by Vivihung** [comment]
@mikepsinn Sorry, typo. I mean 'sort series data by the value of x-axis'
