### ISSUE TITLE
3d `column` chart shown 2d

### ISSUE THREAD

**Issue by Jossef** [pablojim/highcharts-ng#313]
### I'm trying to get a 3d column  chart 

I've looked in highcharts demos and found [this](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/3d-column-null-values/)

![image](https://cloud.githubusercontent.com/assets/1287098/7443824/9ca6f570-f16f-11e4-8949-5d6ce3e429c3.png)

then copied the following config and replaced it in the [jsfiddle provided in the project description](http://jsfiddle.net/pablojim/Hjdnw/) 

```js

    $scope.chartConfig = {
        chart: {
            type: 'column',
            margin: 75,
            options3d: {
                enabled: true,
                alpha: 10,
                beta: 25,
                depth: 70
            }
        },
        title: {
            text: '3D chart with null values'
        },
        subtitle: {
            text: 'Notice the difference between a 0 value and a null point'
        },
        plotOptions: {
            column: {
                depth: 25
            }
        },
        xAxis: {
            categories: Highcharts.getOptions().lang.shortMonths
        },
        yAxis: {
            title: {
                text: null
            }
        },
        series: [{
            name: 'Sales',
            data: [2, 3, null, 4, 0, 5, 1, 4, 6, 3]
        }]
    }

```

I've also added highcahrts-3d.js as a resource to this fiddle
and this is the result :cry: 

![image](https://cloud.githubusercontent.com/assets/1287098/7443831/c287254e-f16f-11e4-90ee-84309a47d2a3.png)

### http://jsfiddle.net/n6a50gw7/

**Comment by Jossef** [comment]
## figured it out,

```
$scope.chartConfig = {
	chart: {
		type: 'column',
		margin: 75,
		options3d: {
			enabled: true,
			alpha: 10,
			beta: 25,
			depth: 70
	}
	title: {
		text: '3D chart with null values'
	},
	...
}
```

**changed to**

```
$scope.chartConfig = {
	options: {
		chart: {
			type: 'column',
			margin: 75,
			options3d: {
				enabled: true,
				alpha: 10,
				beta: 25,
				depth: 70
		}
	},
	title: {
		text: '3D chart with null values'
	},
	...
}
```

# http://jsfiddle.net/v74qr1yb/1/

![image](https://cloud.githubusercontent.com/assets/1287098/7443886/2c53cd58-f173-11e4-8e27-8d0c64042f8a.png)

**Comment by Jossef** [comment]
@pablojim, some config fields wrapped under `options`. why is that? 
it confuses me in the *getting started* process  (and i believe others as well)

:smile:

**Comment by pablojim** [comment]
https://github.com/pablojim/highcharts-ng#faq ;-) Thanks for using the plugin. Glad you found a solution.
