### ISSUE TITLE
Create bar chart using get data from angular js servie $http or resource or restangular.

### ISSUE THREAD

**Issue by rkori215** [pablojim/highcharts-ng#314]
Hi 
how can we  create bar chart using below score object from below json data as series.

{
    "Type": null,
    "Id": null,
    "Date": null,
    "reportCategories": [{
        "categoryName": "x",
        "categoryDescription": "cgcvc",
        "specDescription": "sdsdsd",
        "subCategories": [],
        "score": 1.9,
        "rating": "Low"
    }, {
        "categoryName": "y",
        "categoryDescription": "dfdf.",
        "specDescription": "fdfdf.",
        "subCategories": [],
        "score": 1.9,
        "rating": "Low"
    }, {
        "categoryName": "z",
        "categoryDescription": "Pdfdfdfd",
        "specDescription": "dfdfd.",
        "subCategories": [],
        "score": 2.3,
        "rating": "Low"
    }]
}

**Comment by pablojim** [comment]
Maybe one for stackoverflow
