### ISSUE TITLE
Conflicts with Wijmo

### ISSUE THREAD

**Issue by lesoped** [pablojim/highcharts-ng#315]
Hello, looks like highcharts-ng conflicts with wijmo
If wijmo is initializes like this:
`script src="http://cdn.wijmo.com/jquery.wijmo-open.all.3.20151.69.min.js"></script>
script src="http://cdn.wijmo.com/jquery.wijmo-pro.all.3.20151.69.min.js"></script>
script src="http://cdn.wijmo.com/interop/angular.wijmo.3.20151.69.min.js"></script>`
Angular app:
`var app = angular.module('myapp', ['wijmo', 'highcharts-ng']);`

Highchart fails to render the chart and console error is:

Error: a.ownerDocument is undefined
Ib@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:24562
Jb@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:24676
.css@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:30095
.css/<@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:31553
m.access@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:3432
.css@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:31396
u@http://cdn.wijmo.com/jquery.wijmo-open.all.3.20151.69.min.js:68:99
jQuery.fn.animate@http://cdn.wijmo.com/jquery.wijmo-open.all.3.20151.69.min.js:68:3604
win.HighchartsAdapter<.animate@http://code.highcharts.com/highcharts.src.js:1198:4
SVGElement.prototype.animate@http://code.highcharts.com/highcharts.src.js:1821:4
SVGElement.prototype.align@http://code.highcharts.com/highcharts.src.js:2441:3
Chart.prototype.layOutTitles@http://code.highcharts.com/highcharts.src.js:11679:1
Chart.prototype.redraw@http://code.highcharts.com/highcharts.src.js:11380:3
highchart/<.link/<@http://localhost/scriptopro2a/js/highcharts-ng/highcharts-ng.js:294:15
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:14308:23
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.js:14571:13
@http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-touch.js:471:7
m.event.dispatch@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:8384
m.event.add/r.handle@http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js:3:5122

If jquery.wijmo-open.all.3.20151.69.min.js is removed, highchart-ng works fine. Also, tried older versions of Wijmo and it still conflicts.
Any ideas how to fix?

**Comment by pablojim** [comment]
Sorry I have no idea what Wijmo is.
