### ISSUE TITLE
Current zoom is reset when options is changed

### ISSUE THREAD

**Issue by ValentinH** [pablojim/highcharts-ng#318]
I have noticed that if I want to update the options at runtime, the changes are correctly applied but the zoom is reset. Is it a working-as-design behaviour or a bug?

Here's an example that updates the chart type: http://jsfiddle.net/a3ssubt4/

**Steps to show what I mean:**
1 - Zoom
2 - Click on the toggle button
**Result:** The chart type is updated but the zoom is reset.

**Comment by pablojim** [comment]
Not as designed anyway - so more of a feature. Try defining an x-axis and that might help.

**Comment by ValentinH** [comment]
I had actually forgot that all chart state was reset when options modified. Indeed, the initChart() function is called. I tried to think about a way to do something like updateChart() that would actually recreate the chart but with the previous state (zoom, legends visibility, etc...). But it is quite tough...

Do you see a way to implement this?
