### ISSUE TITLE
Refreshing the graph

### ISSUE THREAD

**Issue by tetsi** [pablojim/highcharts-ng#323]
Hi, 
I'd like to refresh the graph so the animation is playing everytime I click on the tab that contains my graph. I haven't found any mothod to do this in the API. Does anyone has an idea ? (ps : I'd like to use pure angular and no jquery).

Thanks in advance

**Comment by muudles** [comment]
@tetsi Did you manage to find a solution?

**Comment by tetsi** [comment]
@muudles Hi, I haven't found any "good" solution so I'm just re-instanciating the charts in a function on the buttons which starts like this : $scope.chartName.series = [ rewrite here your entire graph... ].
I don't know how effective it could be with a lot of data in the graph or with a hudge database...

**Comment by pablojim** [comment]
If you add a dummy property to the chart config object. e.g. foo and then change its value the chart should refresh

**Comment by DVelbeck** [comment]
Sorry to reopen this old case, but when you say "add a dummy property", where to put this ?
I'm facing an issue where if my chart is rendered with a bunch of data from a json object, when changing the data the chart is not refreshed with it.

Here is a pastie : http://pastebin.com/Q3mtEUeF

Thanks for your help.

**Comment by pablojim** [comment]
New issue with a jsfiddle pointing 1.0.0 please.
