### ISSUE TITLE
Animation when adding data not being shown

### ISSUE THREAD

**Issue by bartvanremortele** [pablojim/highcharts-ng#328]
I have a strange issue with the highcharts default animations using highcharts-ng. They aren't being shown when I add my own data and are sometimes shown when I use the sample data from highcharts-ng. I think it has something to do with ui-router but I'm not sure. I can't quite locate the issue. I looked through the issues here but didn't quite seem to find anything like the issue i'm reporting. Does anyone have an idea what this could be? Thanks

**Comment by ottosson** [comment]
I probably have the same issue. It doesn't animate when the number of series' is changed.
See fiddle: http://jsfiddle.net/kq8L50f8/

**Comment by bartvanremortele** [comment]
@ottosson now it makes sense. How do we fix it?

**Comment by pablojim** [comment]
This seems to be an artifact of how highcharts handles setData calls with pie charts. I'm not sure we can fix it as part of this plugin. Maybe see if you can replicate this by calling setData on a vanilla highcharts pie chart. If so, you could raise an issue with highcharts. If you do this please reference this issue.

In the meantime you could force a refresh of the whole chart by changing the value of an option that highcharts-ng doesn't know how to handle individually: http://jsfiddle.net/kq8L50f8/4/
