### ISSUE TITLE
Legends not showing values

### ISSUE THREAD

**Issue by sadranyi** [pablojim/highcharts-ng#329]
adding legend settings to the configuration does not show the y value.

    $scope.attendanceChartConfig = {
        options:{
            chart:{type:'column'}
        },
        title:{text:''},
        subtitle:{text:''},
        xAxis:{
            categories:['Firts Service', 'Second Service', 'Third Service', 'Jericho Hour', 'Moning Glory'],
            crosshair:true
        },
        yAxis:{
            min:0,
            title:{text:'Attendance per service'}
        },
        tooltip:{
            headerFormat:'<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' + '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions:{
            column:{pointPadding: 0.2, borderWidth:0}
        },
        legend:{
            labelFormat:'{point.y}',
            title:{text:'just Testing'}
        },
        series:[
            {
                name: 'Membership',
                data:[10,20,30,25,15]
            },
            {
                name: 'New Members',
                data:[5,10,8,9,15]
            },
            {
                name: 'Born Agains',
                data:[10,15,12,20,15]
            },
            {
                name:'Visitors',
                data:[10,15,12,20,15]
            }]
    };

results
![Uploading error.png…]()

**Comment by pablojim** [comment]
See the faq. You need to move your tooltip and legend options.
