### ISSUE TITLE
Can you separate chart data from options?

### ISSUE THREAD

**Issue by jlebrech** [pablojim/highcharts-ng#330]
if it's possible already could you please document it.

Thanks.

**Comment by pablojim** [comment]
You can reference objects from the options. 

e.g.

```series: [{
     data: myFancyDataObject
  }]```

Is that what you had in mind?

**Comment by jlebrech** [comment]
I meant something like this:

<div class="panel" ng-repeat="n in nodes">

<h1>{{n.title}}</h1>

<highchart data="n.data" options="myLineChartObject"></highchart>

</div>

On Thu, May 28, 2015 at 11:29 AM, Barry Fitzgerald <notifications@github.com

**Comment by pablojim** [comment]
No that is not supported. You could quite easily wrap the directive in another one though to acheive this.
