### ISSUE TITLE
Points is missing after reload highchart

### ISSUE THREAD

**Issue by oliang33** [pablojim/highcharts-ng#331]
Hi Guys,

I am going to use the highchart to show the data in spline graphic.

In order to auto-fit for the windows, I need to reload the highchart. I am using angularjs and calling the reload by $rootScope.$broadcast('highchartsng.reflow');

However, after I reload the highchart, some points on the spline is missing. Do not know it is bug or not?

Please check the pics in the attachment. 1.png is the pic before the reloading, 2.jpg is the pic after reloading

It seems that highcharts only update the points in original size area. Not update the points in the extended area

![1](https://cloud.githubusercontent.com/assets/12650986/7873380/0234e01c-05e5-11e5-8d89-852b88e60bb0.jpg)

**Comment by oliang33** [comment]
Are there anybody could help?

**Comment by pablojim** [comment]
Could you create a jsfiddle that shows the problem?
