### ISSUE TITLE
IE8 issue - grpah not loading

### ISSUE THREAD

**Issue by praswebdev** [pablojim/highcharts-ng#332]
Highcharts - bar chart not loading on initial load of the page in IE8. When you refresh the page it works.

Getting following errors in console. 
TypeError: 'd.renderer' is null or not an object
TypeError: 'this.spacingBox.width' is null or not an object.
 TypeError: 'chart[...].0' is null or not an object

Looks like IE8 is slow and the highcharts library is not ready and am trying to initialize the chart before that. Do we have any events which let us know when highchart is ready?

**Comment by pablojim** [comment]
Have you got a jsfiddle?
