### ISSUE TITLE
When the chart is not rendered immediately, reflowing the chart doesn't work

### ISSUE THREAD

**Issue by denislins** [pablojim/highcharts-ng#333]
We made a new feature, in which the charts on this page are hidden on load, but can be visible when a button is clicked.

This introduced major problems with the chart not filling the parent's size correctly, even when reflowing the chart. I made a plunkr to demonstrate the problem: http://plnkr.co/edit/14x7gfQAlHw12XZVhWm0?p=preview

The problem on this one, is that the chart is reflowed when the chart is not visible, thus not resizing correctly. Changing `ng-show` to `ng-if` solved the problem in the plunkr, as it is now created every time it shows, but it didn't work for my application.

I tried several alternatives, such as increasing the timeout, broadcasting the event every time the chart is shown, and many combinations of those, but none of them worked for me.

Have you guys seen anything like this? What about the ng-if solution, is it viable? I mean, should we warn users not to use ng-show with highcharts-ng?

**Comment by OrganicCat** [comment]
I have this exact problem as well. The redraw and/or load function fires BEFORE the actual rendering, causing the reflow to not work properly. The only workaround, which does not look good, is using a timeout within the redraw method. You can also use a setSize WITHOUT a timeout, but I've found setting the "chartWidth" (not using setSize) does not account for the labels on the right or left side. Please take a look at this issue devs!

Also:

http://stackoverflow.com/questions/30987841/highcharts-event-redraw-load-with-reflow-and-angular?noredirect=1#comment50028208_30987841

**Comment by kirkchris** [comment]
:+1: had the same issue. Would love to hear if there is a more appropriate fix.

However, as a workaround I was able to get it working by putting the definition of my highcharts variable & data loading, etc inside of `$scope.$evalAsync`

So in my controller initialization I have:

```
$scope.$evalAsync(->
   $scope.highChartsConfig = {...}
)
```

**Comment by ramoniglesias** [comment]
Hi @kirkchris , do you mind sharing the snippet? I'm having a similar issue. Thanks!

**Comment by kirkchris** [comment]
@ramoniglesias sure:

```
angular.module('app').controller('GraphController', ['$scope', function($scope) {
  function init() {
    $scope.$evalAsync(function() {
      $scope.highChartsConfig = {
         options: {
           type: 'line'
         }
      }
    })
  }
  
  init()
})
```

then in html for your controller:
```
<highchart id="chart1" config="highChartsConfig"></highchart>
```

**Comment by ramoniglesias** [comment]
Thanks!
