### ISSUE TITLE
Chart does not update when changing formatter function.

### ISSUE THREAD

**Issue by msrose** [pablojim/highcharts-ng#335]
When changing the chart config formatter properties, such as `options.tooltip.formatter` or `yAxis.labels.formatter`, the chart doesn't update. Fiddle here: http://jsfiddle.net/3ku41tb2/2/

I think this is because `angular.equals` ignores properties that are functions when comparing objects (https://docs.angularjs.org/api/ng/function/angular.equals). As a result, scope.$watch won't detect a change in the chart config when any property that is a function is changed.

**Comment by pablojim** [comment]
This is a problem. One workaround is to increment a dummy property to force a refresh.
