### ISSUE TITLE
columnrange not supported

### ISSUE THREAD

**Issue by ELE3E** [pablojim/highcharts-ng#339]
I have problems rendering a graph using the columnrange type. Here's the JSFiddle:
https://jsfiddle.net/Hjdnw/1257/

**Comment by jaimeguaman** [comment]
It's not ng-highcharts related issue at all, you're not generating appropriate highchart build

http://jsfiddle.net/Hjdnw/1257/

@pablojim you should close issues related to misconfiguration of Highcharts
