### ISSUE TITLE
highcharts-ng does not render data from angularfire immediately.

### ISSUE THREAD

**Issue by aungyin** [pablojim/highcharts-ng#340]
I am having problem rendering the chart using highcharts-ng plugin.

I use angularfire as the backend.
I am sure that angularfire response data to the chart, but in the browser chart is not display on the first time access.

But If I click other link and come back to the same link. The chart will be rendered. 

I am not sure what's the problem in here. Why the chart doesn't render at the first time access? 
Thanks in advanced.

**Comment by jburgueno** [comment]
Something similar was happening to me, I was calling a REST service and then updating the data inside the series with the value given by the service, but the chart was only refreshing when I clicked some link or change some input inside the webpage.

Fixed it calling $scope.$apply(); in the function inside $scope.chargConfig ,like this:

```javascript
$scope.chartConfig = {
      options: {
        chart: {
            type: 'gauge'
        },
        ....
        },
        .....
        func: function (chart) {
                $scope.chartConfig.series[0].data[0] = $scope.grafico.valor;
                $scope.$apply();
        }
};
```

**Comment by AaronBuxbaum** [comment]
@aungyin Are you using 3 way binding to do this? AngularFire doesn't automatically update the local data unless you're binding to a scope object. If you give some code snippets, I can help you debug; I'm about to start a project using Angularfire as well.

**Comment by pablojim** [comment]
Sorry I have never used angularfire.
