### ISSUE TITLE
Variable in highcharts config

### ISSUE THREAD

**Issue by kbuckinghamCR** [pablojim/highcharts-ng#345]
I seem to be unable to pass a variable to the highcharts config. Example:

Template:
```
<highchart config="$index"></highchart>
```
Results in error:
```
TypeError: Cannot assign to read only property 'getHighcharts' of 0
```
On the other hand, everything works fine if I use:
```
<highchart config="0"></highchart>
```
How can I use a variable in the config?

**Comment by pablojim** [comment]
Maybe post a jsfiddle showing the problem?
