### ISSUE TITLE
highcharts ng is downloading only the two series with new plugins

### ISSUE THREAD

**Issue by shanthiforu** [pablojim/highcharts-ng#347]
Highcharts ng is downloading  CSV and XLS with only the two series with new plugins

Please check the following link:

http://codepen.io/anon/pen/wayPro?editors=101

Even i make all series visible:true, then also it is downloading two series.

**Comment by pablojim** [comment]
Exporting will only export visible series. e.g. change visible to true on line 320 and it will then export.

I think the confusion comes from $scope.chartSeries. You don't appear to use this object.
