### ISSUE TITLE
highcharts-ng does not properly update chartConfig when a series click handler is modified

### ISSUE THREAD

**Issue by ASethi77** [pablojim/highcharts-ng#349]
When I initially set a function to handle clicking a specific data point in a series, highcharts-ng works fine. However, if I wish to override this event handler later, highcharts-ng does not detect the change, and therefore does not properly update the chart's handler.

[Here's a Plunkr](http://plnkr.co/edit/yulUWc?p=preview) to demonstrate this issue. Note that the first click function prints "click one!" to the console and changes the event handler to the second click function. If I click a second time, however, it will still call the first function.

I'm fairly certain that [this block of code](https://github.com/pablojim/highcharts-ng/blob/master/dist/highcharts-ng.js#L318-L325) is not watching correctly. If I change $watch to $watchCollection instead, it works as expected.

**Comment by pablojim** [comment]
Angular does not inspect functions for differences so the change is not detected. I'd suggest adding a dummy property that you modify to force angular to detect a change and therefore let highcharts-ng reinitialise the chart.

Alternative you could do this with a bit of indirection e.g. have the click handler call another function that you modify.

**Comment by ASethi77** [comment]
I was able to get this working using a dummy property as you suggested. Thanks for your help!
