### ISSUE TITLE
getSVG is swapping the bar chart axis

### ISSUE THREAD

**Issue by woolyninja** [pablojim/highcharts-ng#353]
When I do chartConfig.getHighcharts().getSVG() everything works great except the bar chart axises are swapped.  My guess is a certain option needs to be sent to the getSVG but I can't seem to figure it out.

**Comment by pablojim** [comment]
Probably a question for highcharts itself as this plugin should affect this method call.

**Comment by woolyninja** [comment]
Sorry, I kept researching after I wrote this and just realized the issue was a programming issue on our end.  Closing it was the right call as I would've closed it myself if you wouldn't have been so fast.

**Comment by pablojim** [comment]
No problem. Glad you got it fixed.
