### ISSUE TITLE
layout issues

### ISSUE THREAD

**Issue by mparisi76** [pablojim/highcharts-ng#354]
I cannot for the life of me figure out what is giong on here. When I refresh the page, the charts look awesome, but when I go from route to route, the charts are all out of whack. What id going on??

![screen shot 2015-07-24 at 4 51 36 pm](https://cloud.githubusercontent.com/assets/4642133/8886750/9292f692-3224-11e5-905e-2bd23da9ef57.png)

![screen shot 2015-07-24 at 4 51 18 pm](https://cloud.githubusercontent.com/assets/4642133/8886752/a8e0eca6-3224-11e5-8eea-9ca1f662bcb4.png)

I've spent way too long on this not to have a solution...!!!

**Comment by seadour** [comment]
I was having a very similar issue with my graphs. Are you setting global Highcharts options via Highcharts.setOptions() (or an angular-ng equivalent)?

I realized that when I went to a certain route, I was changing global style options via Highcharts.setOptions() that persisted when I went back to the previous route and overrode the individual style settings.

**Comment by seadour** [comment]
Hey @mparisi76, did you find a solution to this?

**Comment by mparisi76** [comment]
The issue was not with highcharts-ng, it was a race condition with the structures I had in place which wrapped highcharts.
