### ISSUE TITLE
Exporting all charts

### ISSUE THREAD

**Issue by Vaelyr** [pablojim/highcharts-ng#355]
Anyone has been able to figure out how would I be able to have an external handler for exporting all charts given array like in this example? http://jsfiddle.net/highcharts/gd7bB/

I have an array of configurations and would like to perform exactly the same action, but unable to successfully convert these 2 methods so they would suit for the angular directive.

Thanks.

**Comment by dfromero** [comment]
@Vaelyr you would need to add the functions there and also the exporting dependency, it should work then, i tried my self and worked just as in the example.
