### ISSUE TITLE
Support for funnel & gauge charts?

### ISSUE THREAD

**Issue by josephluck** [pablojim/highcharts-ng#357]
Not sure if this has already been covered, but I can't certainly get it to work, but... are funnel and gauge charts going to be supported any time soon?

**Comment by danyim** [comment]
+1. Wondering this as well.

**Comment by llanzo** [comment]
Me too.

**Comment by allencch** [comment]
For the funnel, please include modules/funnel.js

**Comment by pablojim** [comment]
@josephluck , @danyim , @llanzo 

A good start would be to link to some examples that you would like working. Then also attempt to reproduce them with this plugin - link also to these (even if broken). Then we can see what needs to be added/fixed.

**Comment by llanzo** [comment]
I think I just didn't understand where the options for funnel charts mapped to the charConfig object.  So I'm only commenting to say that funnel charts appear to work fine, and to help if anyone else is still struggling with it. Once I included funnel.js, the key seems to be to pass any funnel chart specific options as a property of **chartConfig.options.plotOptions.funnel**,  I have forked an awful jsfiddle here that illustrates this:
http://jsfiddle.net/twj1p76s/

**Comment by pablojim** [comment]
Thanks @llanzo
