### ISSUE TITLE
get SVG for multiple charts

### ISSUE THREAD

**Issue by rkori215** [pablojim/highcharts-ng#358]
Hi I am using highcharts for generating charts in that by selecting drop down i am adding changing series data for that chart now i need to get svg for all charts at a time with out selecting any option from  dropdown is there any way wwe can get svg for multiple charts where series is changing by dropdown.

sorry my english is bad but please help me in this.

Thanks in advance.

**Comment by dfromero** [comment]
@rkori215 highcharts have a built-in function to get the svg from each chart for the current chart, I'm not sure about your question, do you have multiple charts or a chart with lines changing based on a dropdown. What i would do is render all the series, get the svg and hide them back. Reference for getting all svg for all charts http://jsfiddle.net/highcharts/gd7bB/
