### ISSUE TITLE
What is process for incorporating a plugin written for highcharts?

### ISSUE THREAD

**Issue by linkedrank** [pablojim/highcharts-ng#359]
Apologies if this is an ignorant question!

**Comment by pablojim** [comment]
You should be able to just include the javascript. Some plugins will be unsupported though.

**Comment by linkedrank** [comment]
OK thanks - any info on what kinds of plugins won't work? I assume things
that change the rendering are ok? For example I have a plugin that
determines the optimal max and min and tick values. I have another one that
adds buttons to the graph - perhaps that one won't work?

**Comment by pablojim** [comment]
Hard to say without seeing them. IF you setup a jsfiddle I can have a look.

Problematic examples:
- Changing data without changing the angular coy of the data.
- in highcharts-ng the chart can be initialised first and then the series added - this can cause problems if the plugin expects all data to be there after initialisation

**Comment by linkedrank** [comment]
Ok thank you much. I'll send you an example if I have trouble.
