### ISSUE TITLE
Dynamic Highcharts-ng using ng-repeat

### ISSUE THREAD

**Issue by leksanboy** [pablojim/highcharts-ng#361]
I'm create a Dashboard with dynamic Charts.
Before I put the names directly on config="chartName", but now I'm using json file.
And now it's doesn't work correctly.

for Example:
    data.json
        [
            { "chart":"dataOne" },
            { "chart":"dataTwo" },
            { "chart":"dataThree" }
        ]

if I set it for this way
-ul- ng-repeat="item on items"
 -li- highchart(config="{{item.chart}}") -/li-
-/ul-

the result is config={{}}

but if for this way
-ul- ng-repeat="item on items"
 -li- highchart(config="'{{item.chart}}'") -/li-
-/ul-

the result is config="'dataNumber'"  extra quotes -->' '<--.

on index.html --> line 21 Uncomment and comment line 20. And move the middle bar for rescaling highcharts.
Check this plunker --> http://plnkr.co/edit/97OrEAPrV3yDXcXF37L9?p=preview

Inspect element Use Console and Elements on Google Chrome.

**Comment by dfromero** [comment]
the thing if your passing a string and config is expecting an object

**Comment by leksanboy** [comment]
dfromero, I don't understant you, can you explain better? or try plunker

**Comment by FDIM** [comment]
I am pretty sure you figured this out already but you were binding data incorrectly.
see http://plnkr.co/edit/TnJXbDRqi4aK8EqnqQsK?p=preview
All I am saying is that this is not an issue and can be closed :)

**Comment by pablojim** [comment]
Thanks @FDIM and @leksanboy

**Comment by sourav-kings** [comment]
@FDIM 

The suggestion mentioned by you worked perfectly. Thanks a lot. : )
