### ISSUE TITLE
Do i need to buy license from Highchart to use this project in a commercial website?

### ISSUE THREAD

**Issue by anmolagar** [pablojim/highcharts-ng#362]
highcharts-ng looks amazing and i want to use this in my project. My only concern is that highcharts are actually not free for commercial websites. So do i need buy some licenses from them to use this project.

**Comment by dfromero** [comment]
@anmolagar yes, you need to buy highcharts license in order to use it on your commercial site.

**Comment by maniakhil** [comment]
After buying license how do you apply license,where to point that this is licensed verison?
