### ISSUE TITLE
Highstock vanilla example not working

### ISSUE THREAD

**Issue by yesman85** [pablojim/highcharts-ng#363]
I am trying to convert the highstock example from the highcharts website:
http://jsfiddle.net/r88yszk0/122/

But it just shows a blank chart.

**Comment by pablojim** [comment]
This is a using angualrjs question:

You need to:
- angular $http methods (preferable) 
- use a $scope.apply call.

**Comment by yesman85** [comment]
Oh my bad, just noticed I was using the jquery functions.
