### ISSUE TITLE
yAxis

### ISSUE THREAD

**Issue by millo82** [pablojim/highcharts-ng#370]
After the new tag from 0.0.8 to 0.0.9 with the same config object when i set the yAxis attribute get an error.

This is my configObject:

```javascript
{
                xAxis: {
                    currentMin: 0,
                    title: {
                        text: 'label'
                    }
                },
                yAxis: {
                    currentMin: 0,
                    minRange: 1,
                    title: {
                        text: 'label'
                    }
                },
}
```

if i remove the yAxis no more error.

The solution is adds defaultOptions the yAxis attribute in the *defaultOptions*

**Comment by pablojim** [comment]
I think this is fixed by #369 - could you check on master?
