### ISSUE TITLE
Adding custom Attributes to Chart Options

### ISSUE THREAD

**Issue by samzer** [pablojim/highcharts-ng#375]
Hi,
Is it possible to add custom attribute to the chart options as shown in the following link 
http://jsfiddle.net/jmunger/KFpJC/17/

**Comment by pablojim** [comment]
It might be difficult with this plugin. Best to give it a try and let me know where you get stuck.

**Comment by samzer** [comment]
Hey,

Thanks Pablo, I got it working with a round about manner. Following is the Plunkr link for it.

http://plnkr.co/edit/N1o3zxmeH64lVv5eWCQx?p=preview
