### ISSUE TITLE
Redraw issues with column chart using highcharts 

### ISSUE THREAD

**Issue by tarsuzi** [pablojim/highcharts-ng#377]
Hi,

I have an error with drawing bar chart in the example for the following link: http://jsfiddle.net/FC3qV/18/

I want to use many of type charts and switching them. However, whenever change the type of chart from line to bar chart, bar chart is loading twice.

Thank for your advice

**Comment by pablojim** [comment]
You are updating the entire chart options and also the series data. This will cause two updates.

Maybe instead define the type on the series and just update it? Or add one series and remove another?
