### ISSUE TITLE
highcharts-ng: Cannot read property 'setExtremes' of undefined

### ISSUE THREAD

**Issue by JoachimR** [pablojim/highcharts-ng#378]
found this on stackoverflow and have the same problem

http://stackoverflow.com/questions/32477613/highcharts-ng-cannot-read-property-setextremes-of-undefined

since it wasn't posted here before I figured you might be interested..

**Comment by pablojim** [comment]
his is a new bug introduced in 0.0.9 and only partially fixed in 0.0.10.

It will be fixed in a 0.0.11 shortly. In the meantime if in your chart config you define a yAxis it will work:

`yAxis: {
      events: {}
    }`
