### ISSUE TITLE
Jumpy animation when chart updated and a point is removed

### ISSUE THREAD

**Issue by JONBRWN** [pablojim/highcharts-ng#379]
When updating a chart, the animation is jumpy when a point is removed from the series to keep a set number of points within the series.
i.e. only 13 points
See:
http://jsfiddle.net/7fg99f2c/

Am I adding/removing points wrong? or is this the expected behavior?

**Comment by pablojim** [comment]
This looks ok to me (on Chrome) what behaviour were you expecting?

**Comment by JONBRWN** [comment]
@pablojim I was expecting it to look like this:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-update/

**Comment by JONBRWN** [comment]
@pablojim I was able to get the desired animation using `chartConfig.getHighcharts()` and `series.addPoint` but it seems this goes against the way highcharts-ng should be used. Is there a way to get the desired animation without the workaround at this moment?

**Comment by pablojim** [comment]
Ok now I see the issue. addPoint is handled differently by Highcharts than setData. Currently highcharts-ng watches the data for changes and when it changes it calls setData on the series. It does not distinguish cases of adding one point vs other data changes and hence uses setData in all cases.

In theory it could workout when the change to the data is a simple addition of a point. This could work but might be slow. This wouldn't be something I'd work on at the moment, but pull requests are welcome!

**Comment by JONBRWN** [comment]
@pablojim I'll look into the work it will take to add the functionality.

What's the best way to know that the `chartConfig` has been initialized? so I can use the `chartConfig.getHighcharts()` within a controller and not get undefined function

**Comment by pablojim** [comment]
The most foolproof way is to use the load event in highcharts itself. e.g. something like...

` events: {
                    load: function () {
                       $scope.myChart = chartConfig.getHighcharts();
                    }
                }`

**Comment by jaimeguaman** [comment]
I think it would be difficult (without affecting performance) to know whenever to use `addPoint`, `removePoint` or `setData`

I ran into the same problem in two different projects and the best way to get rid of it is to use `load` event and use [addPoint](http://api.highcharts.com/highcharts#Series--addPoint)  or [removePoint](http://api.highcharts.com/highcharts#Series--removePoint) from Series API, in fact, the example at Highchart's website is based on this approach

**Comment by JONBRWN** [comment]
@jaimeguaman so you ended up calling `chart.redraw()` or added the redraw flag to `addPoint` manually when needed? I'd like to avoid that if possible but it doesn't seem as if that is the case

**Comment by jaimeguaman** [comment]
@JONBRWN for my particular case, I added redraw flag to addPoint when needed

**Comment by JONBRWN** [comment]
@jaimeguaman can you provide a snippet of your `load` config?
