### ISSUE TITLE
Legend / Circle icons

### ISSUE THREAD

**Issue by MasamuneCode** [pablojim/highcharts-ng#382]
Hi there !

I'd like to have the fancy circle icons for the legend, like this example found on stackoverflow : http://jsfiddle.net/Wzs9L/

I've tried to add this in the options :

legend: {
    symbolHeight: 120, // ko
    symbolWidth: 120, // ok
    symbolRadius: 120 // ko
},

But only the symbolWidth options seems to work.
Couldn't find some documentation for highcharts-ng, not sure if the 2 toher options or misplaced or doesn't exist yet.

Am I doing something wrong ?
Thanks ^^'

![capture-1](https://cloud.githubusercontent.com/assets/10812138/10069179/b5d5ea04-62aa-11e5-973c-607bdf42ffbd.jpg)

**Comment by pablojim** [comment]
This should be possible. Create a jsfiddle with your best attempt and we can go from there.
