### ISSUE TITLE
Dynamically adding axes to results in highchart error 18

### ISSUE THREAD

**Issue by trilogysci** [pablojim/highcharts-ng#383]
highcart-ng does not support adding or removing axes. When trying to add new axes dynamically to the chartConfig the following error occurs, if a series is is also added (or changed) with a xAxis or yAxis not equal to 0.

     Highcharts error #18: www.highcharts.com/errors/18

The error is caused by highcharts attempt to add a series to an axis that does not exist.

The following code is a partial fix, but does not address the fact that the $watch on series changes might occur before the $watch on axis changes. So the axes may be added, but not before the series is added/updated causing the same error to still occur.

```javascript
    if(_.isArray(newAxes)) {
      console.log('checking axis', axisName);
      for(var idx in newAxes) {
        var axis = newAxes[idx];
        if (idx < chart[axisName].length) {
          chart[axisName][idx].update(axis, false);
          updateZoom(chart[axisName][idx], angular.copy(axis));
        } else {
          console.log('adding axis');
          chart.addAxis(axis, axisName=='xAxis', false);
        }
      }
      for(var idx=chart[axisName].length-1; idx>=yAxis.length; idx--) {
        console.log('removing axis',idx);
        chart[axisName][idx].remove();
      }
    } else {
      for(var idx=chart[axisName].length-1; idx>=1; idx--) {
        console.log('removing axis',idx);
        chart[axisName][idx].remove();
      }
    }
```

**Comment by tidemann** [comment]
+1

**Comment by pablojim** [comment]
Thanks for reporting this. Could you package up this in a pull request with a jsfiddle that demonstrates the behaviour before and after the fix.

**Comment by kalouantonis** [comment]
I have the same issue with data formatted like so:

```
{
  "options": {
     "chart": {
       "type":"bar",
       "zoomType":"x"
     },
  },

  "loading": false,
  "useHighStocks": false,

  "xAxis": {
    "categories": ["John", "Jack", "Steve","Bob", "Jill", "van Burren", "Rachael", "Paul", "Butch", "Bill", "Adam","Generic Name"]
  },
  "yAxis": [{
    "title": {
      "text":"Commits"
     },
     "labels": {
        "format": "{value} commits"
      },
      "opposite":false
  }, {
    "title": {
      "text":"Issues"
     },
     "labels": {
        "format": "{value} issues"
      },
      "opposite":true
  }],
   
  "series":[{
     "name":"Commits",
     "data": [791.148876939785,680.020725213894,702.298513346685,810.068295760475,892.882166927293,582.397471988678,751.130015961866,1064.58885388916,730.430013483391,687.891708986568,487.893457060837,895.592387845036], 
     "yAxis":0
   }, {
     "name":"Issues",
     "data": [3217.82112208269,2717.65031789011,3196.11900868479,2968.85191566591,3679.18552860981,2662.61806793373,3269.54582555192,4069.00503676359,2461.99233789815,2647.79355789731,3647.25728514159,3428.94112221734]], 
     "yAxis":1
  }]
}
```

**Comment by AdnanKukuljac** [comment]
To fix this issue put your yAxis in "options" like this: 

$scope.chartConfig = {
				chart : {
					zoomType : 'xy'
				},
				title : {
					text : ''
				},
				credits : {
					enabled : false
				},
				xAxis : [ {
					categories : data.xAxis,
					crosshair : true
				} ],
				options : {
					yAxis : [ { // Primary yAxis
				
					labels : {
						format : '{value}'
					},
					title : {
						text : 'Text1'
					}
					}, { // Secondary yAxis
						gridLineWidth : 0,
						title : {
							text : 'Text2'
						},
						labels : {
							format : '{value}'
						},
						opposite : true
					} ]
				},
				tooltip : {
					shared : true
				},
				legend : {
					layout : 'vertical',
					align : 'left',
					x : 80,
					verticalAlign : 'top',
					y : 55,
					floating : true,
					backgroundColor : (Highcharts.theme && Highcharts.theme.legendBackgroundColor)
							|| '#FFFFFF'
				},
				series : [ {
					name : 'data1',
					type : 'column',
					yAxis : 1,
					color : '#148F76',
					data : data.yAxis
				}, {
					name : 'data2',
					type : 'spline',
					color : '#1ab394',
					data : comp.yAxis
				} ]
			};

**Comment by sguilly** [comment]
If i load options and series together : Highcharts error #18: www.highcharts.com/errors/18

if i load options then series : OK

My workround : 

$scope.displayChart.options = chartConfig.options;
setTimeout(function(){$scope.displayChart.series = chartConfig.series;},1);

**Comment by kalouantonis** [comment]
Sorry for the late reply. This fixed it for me, thank you!

**Comment by drichard1989** [comment]
I am having the same issue with this. When I am trying to dynamically add an axis, it gives the error. I really do not want to add a timeout on the application. Has there been a fix discovered for this?

**Comment by decklord** [comment]
Same issue here. Can't render the chart, this was working before.
If I put the yAxis or xAxis inside options, it doesn't recognize the axis configuration.

**Comment by decklord** [comment]
@pablojim please open this issue. The mentioned fixes are not working.

**Comment by pablojim** [comment]
@decklord this is two year's old. Open a new issue with a jsfiddle demonstrating the problem.
