### ISSUE TITLE
Where to put the chart config in a directive?

### ISSUE THREAD

**Issue by riyunoa** [pablojim/highcharts-ng#384]
I've tried putting the config in the "link" function of the directive but it doesn't work. When I put it in "controller", it works. Why is this? Thanks in advance!

**Comment by ASethi77** [comment]
I've built wrapper directives for highcharts-ng and had no problem putting configs in the link function, so we would need a JSFiddle or Plunkr demonstrating the issue.

In general, though, Angular directive controller functions are the first thing compiled in a new scope; they are processed before the directive is rendered. Link functions are processed *after* the directive is rendered, so processing the config after the chart is rendered is probably too late.

**Comment by mluisbrown** [comment]
There are a number of things that just don't work if you put the config in the `link` function of a directive.  Issue #326 demonstrates this. `datetime` x-axis formatting doesn't work, neither do axis titles (x or y). JSFiddle: https://jsfiddle.net/w657bcdp/
If you have the config in a controller there's no issue. Spent hours scratching my head before realising this.

**Comment by ovarunendra** [comment]
You can put your chart config in directive pre and post section of link.
JSFiddle: https://jsfiddle.net/k9x0tx9m/

**Comment by pablojim** [comment]
Thanks @ovarunendra
