### ISSUE TITLE
ng-click on x-axis label formatter is  not working

### ISSUE THREAD

**Issue by rkori215** [pablojim/highcharts-ng#385]
Hi am trying to call a function on label click on a bar chart using ng-click when i use onclick='window.scrollTo(0, document.body.scrollHeight);' it's working but if i use ng-click='xLabelClick1()' it's not working can any one help me please.. below is sample of my chart config

$scope.xLabelCick1 = function () {
                alert("OK");
                $rootScope.$broadcast('xLabelClick');
            };

 $scope.chartConfig = {
                options: {
                    chart: {
                        type: 'bar'
                    },
                    legend: {
                        enabled: legend
                    }
                },
                title: {
                    text: null
                },
                xAxis: {
                    categories: [jan.feb,march,apr],
                    labels: {
                        formatter: function () {
                                return "<a style='font-size: 16px;cursor: pointer;' ng-click='xLabelClick1()'>" + this.value + "</a>";
                        },
                        useHTML: true
                    }
                },

  $timeout(function () {
            var element = $(".highcharts-container");
            $compile(element)($scope);
        });

**Comment by sadlerw** [comment]
I've done something similar by defining a legendItemClick in the series.  Like:
series:
			[
			 	{
			 		events: {
			 			legendItemClick: xLabelClick1
			 		}

**Comment by pablojim** [comment]
I would use the approach @sadlerw  suggested
