### ISSUE TITLE
Charts not populating when used with ngmap. 

### ISSUE THREAD

**Issue by AymanNatsheh** [pablojim/highcharts-ng#386]
For some reason, the chart is not rendered when used inside a marker in a google map. 

Example: 
http://plnkr.co/edit/5DE8iMQteoQJ7Q5Sgzkf?p=preview

In the example, you will see two charts. One inside the map itself which is not rendering correctly. The other chart is outside and under the map

I have tried the very same example using Highcharts and it renders with no issues. So I suspect the issue is with highcharts-ng.

**Comment by AymanNatsheh** [comment]
Please also note that mouse listeners (click, mouseonver ... etc ) are not working as well.

**Comment by sadlerw** [comment]
It looks like it is working for me in chrome...

**Comment by AymanNatsheh** [comment]
Yes, looks like everything is working now.
