### ISSUE TITLE
type arearange not working

### ISSUE THREAD

**Issue by wroquet** [pablojim/highcharts-ng#393]
I try to use highchart-ng to display an area range chart similar to the highchart.js example : http://www.highcharts.com/demo/arearange

Here is my JSFiddle, it shows me only 1 point on the xAxis : http://jsfiddle.net/vv4q1849/1/ , 
maybe i missed something...

Thanks in advance

**Comment by wroquet** [comment]
Ok i forgot to add highcharts-more in my fiddle, but it still not working with it : 
http://jsfiddle.net/vv4q1849/2/

**Comment by pablojim** [comment]
See faq and http://jsfiddle.net/smkrekaa/
