### ISSUE TITLE
plotOptions does not work with areaspline

### ISSUE THREAD

**Issue by saurabh531** [pablojim/highcharts-ng#394]
I have put plotOptions inside the options block and it does work correctly. But if I change the chart type to areaspline then plotOptions stop working. 

here is a sample code - http://jsfiddle.net/7cAq3/689/

**Comment by pablojim** [comment]
What exactly stops working.

**Comment by saurabh531** [comment]
The plotOptions itself. Whatever values you have defined for plotOptions
are not taken into consideration when chart type is areaspline.




Regards,

*Saurabh Agrawal*

-------------------------------------------------------------------------------------------------

Founder, Stripetics.com

saurabh@novasys.in | Skype: saurabh531 | Linkedin
<http://in.linkedin.com/pub/saurabh-agrawal/3/a22/a58>
www.novasys.in | India

**Comment by pablojim** [comment]
I'm going to need more information than "whatever" values. If you are still having problems please open an issue with a clear and specific description of what functionality you want. Ideally with an illustrative jsfiddle

**Comment by saurabh531** [comment]
I had already given a jsfiddle link when I opened the bug.


Regards,

*Saurabh Agrawal*

-------------------------------------------------------------------------------------------------

Founder, Stripetics.com

saurabh@novasys.in | Skype: saurabh531 | Linkedin
<http://in.linkedin.com/pub/saurabh-agrawal/3/a22/a58>
www.novasys.in | India
