### ISSUE TITLE
Highcharts angular performance

### ISSUE THREAD

**Issue by pawelszczerbicki** [pablojim/highcharts-ng#399]
Hello,
I've got performance issue/question. I'm rendering about 80 area charts in single page using angular and highcharts-ng. When data is loaded and angular is binding it to charts my browser does not respond for about 2 seconds. It is maybe not great amount, but still...
1. What is the reason? It is angular-to-chart binding issue or just chart rendering by highcharts?
There is possibility to make it a little faster or just make it not hanging browser ?

**Comment by woolyninja** [comment]
I had a similar problem and adding disable-data-watch="true" to the <highchart> element fixed this problem for me.  It's worth a shot if you haven't tried it already.

**Comment by pablojim** [comment]
as @woolyninja says! You could also try use setTimeout to render each chart asynchronously. This won't speed it up but may stop the browser freezing.

**Comment by pawelszczerbicki** [comment]
Thank you for responses. There is no visible performance after adding disable-data-watch="true". Data is loaded asynchronously because page is loaded and after about 5 seconds chart data is loaded via websocket. You mean render each chart in async mode ?

**Comment by pablojim** [comment]
Yes I mean render each chart individually asynchronously.

**Comment by pawelszczerbicki** [comment]
Ok, but charts and other data are generated in ng-repeat. Each chart tag is marked by ng-if="obj.hasChart". In code it looks like this:
```
<tr ng-repeat="element in array" >
    <p>{{element.name}}</p>
    <highchart ng-if="element.hasChart" config="element.chart"></highchart>
</tr>
```
After page load each hasChart property is set to false so there is no any chart in page, but name is filled. After about 5-7 seconds additional data is loaded via websocket and some of charts are filled with data by Angular because array object has changed. So angular is taking care of binding data to chart. You mean that I should create each chart settings with timeout function, and set different timeout values ? Or you suggest other method ?
