### ISSUE TITLE
excessive re rendering when adding a point

### ISSUE THREAD

**Issue by Niler851** [pablojim/highcharts-ng#401]
<p>Hi i wonder how i should go about having better animations when adding points to a area plot. In regular highcharts this i done pretty smooth but using highcharts-ng i rerenders a huge chunk of the chart.</p>
I have two fiddels that shows the issue. Maby there is a simpe way to solve this ?
[JsFiddle highcharts-ng](http://jsfiddle.net/Cp73s/3399/)
[JsFiddle regular-highcharts](http://jsfiddle.net/m8Lavyrc/3/)

Tnx

**Comment by pablojim** [comment]
See #379
