### ISSUE TITLE
Update Highstock navigator after deleting / adding series

### ISSUE THREAD

**Issue by arnoutaertgeerts** [pablojim/highcharts-ng#402]
How do I update the navigator after deleting / adding series for a Highstock chart? Currently the first series is always displayed in the navigator even after deleting this series.

**Comment by nkeeslin** [comment]
I am having the same issue

**Comment by pablojim** [comment]
I think you will have to trigger a redraw of the whole chart. You can do this by altering a dummy property in the options config.
