### ISSUE TITLE
Credits dynamic update

### ISSUE THREAD

**Issue by raimonbosch** [pablojim/highcharts-ng#403]
Hi,

I am using $scope.chartConfig.credits.href to include a dynamic link towards a website. This way, depending on the stats I show on highcharts, this link changes. However, this link never updates when I keep using the same type of chart i.e. if I do not change from 'spline' to 'line'.

The only way I have found to solve the problem is including this watch:

scope.$watch('config.credits', function () {
            initChart();
            processSeries(scope.config.series);
            chart.redraw();
        }, true);

I am not sure if it is a good idea to redraw everything just because a small link change on the bottom of the stats.

Thoughts?

**Comment by pablojim** [comment]
Unfortunately there is no method to dynamically change the Credits on an existing chart. http://api.highcharts.com/highcharts#Chart

You should not have to create your own watch though. Have you put the credits config in the right place? Can you show a jsfiddle?
