### ISSUE TITLE
Exporting object inside options is not working

### ISSUE THREAD

**Issue by ShivaliPatel** [pablojim/highcharts-ng#404]
Hii..

I am trying to set `exporting` attribute inside `options` object, but it is not working. In highchart, if we want to set some changes of exporting button,then it allows us to do it inside `exporting` object.

As I also checked the source code of `highcharts-ng`. But I dont find any exporting object in it. 
However, I want to know, is this possible? If yes, then how to do it?

**Comment by pablojim** [comment]
It is possible. See the faq. If you are having trouble still post a fiddle of what you have tried.

**Comment by ShivaliPatel** [comment]
Yes.. It is resolved my issue. Thank you..
