### ISSUE TITLE
Possible Memory leak when constantly rendering charts

### ISSUE THREAD

**Issue by ignaciovillaverde** [pablojim/highcharts-ng#406]
My app consists of a slideshow, where there are slides that swap after a certain amount of time. These slides, include charts.

For making some tests, I have built 3 different snippets:

1 - A simple javascript app that rebuilds a chart every second. This does not produce a memory leak: http://jsfiddle.net/78af7zcm/

2 - An AngularJS app that manages an array of charts. Every second it removes one chart and includes another one, simulating a slideshow behaviour. I couldn't detect a memory leak here: http://plnkr.co/edit/7Zkheiz82ajVusB2EtqH?p=preview

3 - An AngularJS app, similar to number 2, but managing an active chart, which is being modified by listening to an event. The event is listened because in my original app I must do it like this, and here is where the memory leak appears. http://plnkr.co/edit/7cvDrMlWlgLOBAwoNgkW?p=preview . 

Here is the StackOverflow question: http://stackoverflow.com/questions/33636378/memory-leak-using-highcharts-angularjs?noredirect=1#comment55111758_33636378

**Comment by pablojim** [comment]
Thanks for reporting - looking into it.
