### ISSUE TITLE
Lang options set, but not applied.

### ISSUE THREAD

**Issue by aaronatdetroittrading** [pablojim/highcharts-ng#407]
I'm trying to have my scatter plot format axes and tooltips with $X,XXX format for Y and X,XXX format for X. I've included my chart config below. I've grabbed the chart reference via the getHighCharts() helper method and it shows my lang options set appropriately but my output consistently uses the default thousands separator of " " instead of ",". 

Is this an issue with this angular port or perhaps I've misconfigured something. I greatly appreciate any response. 

chartConfig: {
	"options": {
		"chart": {
			"type": "scatter"
		},
		"lang": {
			"decimalPoint": '.',
			'thousandsSep': ','
		},
		"plotOptions": {
			"scatter": {
				"marker": {
					"radius": 5,
					"states": {
						"hover": {
							"enabled": true,
							"lineColor": 'rgb(100,100,100)'
						}
					}
				},
				"states": {
					"hover": {
						"marker": {
							"enabled": false
						}
					}
				},
				"tooltip": {
					"headerFormat": '<b>{series.name}</b><br>',
					"pointFormat": '${point.y:,.0f}<br>{point.x:,.0f} miles'
				}
			}
		}
	},
	"series": [],
	"title": {
		"text": ""
	},
	"xAxis": {
		"title": {
			"enabled": true,
			"text": 'Miles'
		},
		"startOnTick": true,
		"endOnTick": true,
		"showLastLabel": true
	},
	"yAxis": {
		"title": {
			"text": 'Price'
		},
		"labels": {
			"formatter": function () {
				return '$' + this.axis.defaultLabelFormatter.call(this);
			}
		}
	},
	"credits": {
		"enabled": false
	},
	
	"loading": false,
	"size": {
		"width": ""
	},
	"subtitle": {
		"text": ""
	}
}

**Comment by pablojim** [comment]
Could you create a jsfiddle?
