### ISSUE TITLE
Setting pie chart title dynamically at center

### ISSUE THREAD

**Issue by SushantKadam008** [pablojim/highcharts-ng#408]
HI,
Is there any solution on the above issue ? 

I am trying to achieve the below functionality using highcharts-ng but to no avail.

http://jsfiddle.net/LHSey/129/ 

All events are fired before the chart is drawn. But if I use a timeout with 0 sec it works.
Please help.

**Comment by pablojim** [comment]
Use a timeout or highcharts events is the current best approach.

**Comment by SushantKadam008** [comment]
HI Pablojim,
Can you please upload a jsFiddle showing how to solve the issue ? 
Appreciate your help.
