### ISSUE TITLE
Manually call chart.redraw() function

### ISSUE THREAD

**Issue by erdysson** [pablojim/highcharts-ng#409]
Hi, I am using the highcharts-ng within a flexbox grid. The problem is, charts are displayed wrong on page load, but when I resize the window manually, It's fine.
The second problem is, when I shrink the window, redraw function is not called. I am trying to adding it manually and bind on to the window resize event. Is there any way to call redraw() function manually over the configuration given to the directive config?

**Comment by pablojim** [comment]
Sure get the chart object and call redraw! See the faq for how to get the chart object.

Another way to force a redraw is to add a dummy property to the options and change it. This will trigger a redraw as any unknown options cause a full refresh.
