### ISSUE TITLE
Highcharts resize without losing the responsive functionality 

### ISSUE THREAD

**Issue by calvinKG** [pablojim/highcharts-ng#414]
Hi, 

Highcharts resize without losing the responsive functionality.

I have configured my chart  using the  size option on the configuration. 

 size: {width: 350,
                     height: 250}

but when i test the  responsiveness  functionality  those not work

**Comment by aNieto2k** [comment]
Hi, 

I change the version to 0.0.7 and it works again.

**Comment by calvinKG** [comment]
Thanks will test
