### ISSUE TITLE
Implementation of Custom Events Plugin

### ISSUE THREAD

**Issue by zeelobby** [pablojim/highcharts-ng#418]
I'm basically just attempting to implement the custom events plugin for Highcharts found here: http://www.highcharts.com/plugin-registry/single/15/Custom-Events

Anyone got a good way to handle this? Or know where I could modify the highcharts-ng code to add this functionality?

Thanks!

**Comment by pablojim** [comment]
What happens when you use the plugin with highcharts-ng?
