### ISSUE TITLE
How to create highcharts-maps with angular?

### ISSUE THREAD

**Issue by hank-hong** [pablojim/highcharts-ng#419]
I want to create a China map by angular and highchart. Though I tried to any way, the map still doesn't work, Then I tired to run the demo in "highcharts-ng-master\example\maps", it reported  "Uncaught TypeError: Cannot set property 'custom/world' of undefined".
The js I imported are as follows:

src="standalone-framework.js">[From url "http://code.highcharts.com/adapters/standalone-framework.js"]
src="highcharts.js"  [From url "http://code.highcharts.com/highcharts.js"]
src="map.js"[From url "http://code.highcharts.com/maps/modules/map.js"]
src="world.js" [From url "http://code.highcharts.com/mapdata/custom/world.js"]
src="angular.js"[From url "https://ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular.min.js"]
src="highcharts-ng.js" [From zip file I downloaded]
src="app.js"  [From zip file I downloaded]

The other codes are all the same in highcharts-ng-master
Can someone help me? It's urgency issue  =-=

**Comment by hank-hong** [comment]
I found the reason, it was caused by the conflict with file "hgihcharts.js" and "highmaps.js", how can I fix it?

**Comment by levipadre** [comment]
Did you figured the problem out? I have the same problem.

**Comment by hank-hong** [comment]
Hello,

Sorry, I still face this problem and not fix it. After investigating, it may be caused by the codes 'Highcharts.maps["custom/world"] ={...}' in js "world.js", but I'm not sure.

I think I need do some more investigating. =-=, do you have some suggestions?

**Comment by pablojim** [comment]
The demo seems to work ok for me: http://rawgit.com/pablojim/highcharts-ng/master/example/maps/example.html

**Comment by cyril-blanco** [comment]
For the next people landing here:

AFAIK, highmaps.js is the standalone version of the map charts. To display a map, you have then 2 possibilities:
- Include highmaps.js and world.js (or any map data)
- Include highcharts.js, maps.js (module) and world.js

**Comment by fizerkhan** [comment]
@cyril-blanco Thanks. Can you please share any sample code in JSFiddle since example code does not work.

**Comment by cyril-blanco** [comment]
Check the previous version, it works: http://rawgit.com/pablojim/highcharts-ng/0.0.13/example/maps/example.html

@pablojim It looks like the exemples are broken in the latest tag/master

I'm sorry I don't have this code anymore, couldn't keep it. But I don't remember having issues with the loading of ng-highcharts/maps: my map wasn't displaying because I was using flexbox and one of the div wasn't properly styled (I think I commented on another issue about this)
