### ISSUE TITLE
sync tool tip / crosshair between my charts

### ISSUE THREAD

**Issue by oriko** [pablojim/highcharts-ng#420]
Hi 

I am trying to sync tool tip/crosshair between my charts like in this example 
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/synchronized-charts/

What is the way to do it with highcharts-ng?

Thanks,

**Comment by fizerkhan** [comment]
+1. Can you please explain or point to reference of how to do it?
