### ISSUE TITLE
Setting series data dynamically causes chart to not animate when displayed.

### ISSUE THREAD

**Issue by incomestore** [pablojim/highcharts-ng#421]
I'm having an issue where data set dynamically (from a service) shows the chart, but doesn't animate it. Here's my code:

**Controller**

    $scope.chartConfig = {
      // other settings
      series: [{
        data: []
      }],
      // more settings
    };

    Service.getData().then(function(response) {
      $scope.chartConfig.series[0].data = [
        response.score,
        100 - response.score
      ];
    });

Is there a better way to be updating data or is there a way to redraw the chart when the data is updated?

**Comment by pablojim** [comment]
I would expect this to animate the change. Could you make a jsfiddle?

**Comment by lancerushing** [comment]
Same problem, I fixed by putting the data/series manipulation in a $timeout:

```javascript
Service.getData().then(function(response) {
  $timeout(function() {
    $scope.chartConfig.series[0].data = [
      response.score,
      100 - response.score
   ];
  });
});
```

**Comment by pablojim** [comment]
You can see animation happening on data change in the basic example here: http://jsfiddle.net/pablojim/Hjdnw/ (click add data button)

Please give me details on how to reproduce this,
