### ISSUE TITLE
ng highcharts maps

### ISSUE THREAD

**Issue by PhilipAdservice** [pablojim/highcharts-ng#423]
Hi
I'm trying to use the map function in ng-highcharts, but can't seem to get it to work :/ 
Do you have any good examples other then the one in the example folder?

For now i'm just trying to get a map shown, but i either get nothing or a graph :/
Here's my config:
vm.mapConfig = {
			options: {
                legend: {
                    enabled: false
                },
                plotOptions: {
                    map: {
                        mapData: Highcharts.maps['custom/world'],
                    }
                }
            },
            chartType: 'map',
            title: {
                text: 'Highcharts-ng map example'
            },
            series: [
				{countries: {europe: 'France, Germany, Russia'},
				name:"test",
				data: [],
				
				}
			]
};

**Comment by pablojim** [comment]
There is an example here: https://github.com/pablojim/highcharts-ng/tree/master/example/maps

**Comment by PhilipAdservice** [comment]
Hai again
I've seen the examples, but cant seem to get it to work.
With my current config I get a chart instead of a map.

vm.config = {
            options: {
				chart: {
					type: 'heatmap',
					marginTop: 40,
					marginBottom: 80
				},
				colorAxis: {
					min: 0,
					minColor: '#FFFFFF',
					maxColor: Highcharts.getOptions().colors[0]
				}
			},
            title: {
                text: 'Highcharts-ng map example'
            },
            series: [
                this.makeSeries('Europe', countries.europe),
                this.makeSeries('Asia', countries.asia)
            ]
        };
