### ISSUE TITLE
pointPlacement: 'between' doesn't work for datetime x-axis

### ISSUE THREAD

**Issue by keshavr7** [pablojim/highcharts-ng#424]
Tried startontick, endontick etc. The first and the last column always seems to overflow.

options: {
        chart: {
          type: 'column',
          //zoomType: 'x'
        },
        plotOptions: {
            column: {
                pointPlacement: 'between',
            }
        }

**Comment by pablojim** [comment]
Could you create a jsfiddle showing the issue?

**Comment by keshavr7** [comment]
https://jsfiddle.net/n81vxoqa/6/

It works fine in this fiddle. But when I try the same thing in Ionic - the first and the last column get cut in half.

The only thing that has changed there (as compared to fiddle) is HTML 

<ion-view view-title="{{graph.name}}">
<ion-content>
    <div class="item">
      <highchart id="chart1" config="graph.chartConfig"></highchart>
    </div>
</ion-content>
</ion-view>

And, the way data array is populated

$http.get("http://..........")
                .success(function(response) {
                    graphs[i].chartConfig.series[0].data.push([Date.UTC(year, month, day), XXX]);
                  }

Everything else remains the same. Strange!

**Comment by keshavr7** [comment]
https://jsfiddle.net/n81vxoqa/6/

It seems to work fine in this fiddle.

But, when I do the same thing with ionic, the first and the last column seem to be cut in half

<img width="398" alt="screen shot 2016-01-04 at 10 23 23 pm" src="https://cloud.githubusercontent.com/assets/7363289/12094983/d520d0ea-b331-11e5-8d3d-6bed65cdded4.png">

Everything else is the same.

**Comment by pablojim** [comment]
I've not used ionic I'm afraid.
