### ISSUE TITLE
highmaps not working!

### ISSUE THREAD

**Issue by PhilipAdservice** [pablojim/highcharts-ng#426]
Hi again.
I tried to use the example code to get a map, but i get a chart and not a map ?
Am i missing an import or is there an error in the example code?

**Comment by seadour** [comment]
Can you post your source code for us in a plunkr or jsfiddle?

**Comment by PhilipAdservice** [comment]
https://jsfiddle.net/2bdjqk92/

This is the example code, from the project, which i can't seem to get to work..
I tried in my own project, but here i got a chart.
I'm using grunt and i've installed highcharts using bower and added some imports:
<script src="bower_components/highcharts-ng/dist/highcharts-ng.js"></script>
	<script src="bower_components/highcharts-ng/dist/highcharts-ng.min.js"></script>
	
	<script src="http://code.highcharts.com/adapters/standalone-framework.js"></script>

	<script src="http://code.highcharts.com/highcharts.js"></script>
	<script src="http://code.highcharts.com/highcharts-more.js"></script>
	<script src="http://code.highcharts.com/maps/modules/map.js"></script>
	<script src="http://code.highcharts.com/maps/modules/data.js"></script>
	<script src="http://code.highcharts.com/modules/heatmap.js"></script>
	<script src="http://www.highcharts.com/samples/data/maps/world.js"></script>
	<script src="http://code.highcharts.com/mapdata/custom/world.js"></script>

As you can see i've also tried to add the standalone framework, but with no luck.. :( 
In my controller i simply setup a config:
var countries = {
                europe: 'France, Germany, Russia',
                asia:   'Japan, China'
            };

this.config = {
            options: {
                legend: {
                    enabled: false
                },
                plotOptions: {
                    map: {
                        mapData: Highcharts.maps['custom/world'],
                        joinBy: ['name']
                    }
                },
            },
            chartType: 'map',
            title: {
                text: 'map example'
            },
            series: [
                countries 
            ]
        };

**Comment by pablojim** [comment]
Does the example here: http://rawgit.com/pablojim/highcharts-ng/master/example/maps/example.html work for you?

**Comment by PhilipAdservice** [comment]
Yes.
So do you have any ideas to what could be wrong?
Am i missing an import, or am i using a wrong version ?

**Comment by pablojim** [comment]
Not sure. I'd take the example that works and change it pice by piece to match your desired result.

**Comment by cyril-blanco** [comment]
For the next people landing here: this issue is probably not related to highcharts/highcharts-ng. In the fiddle, angular is outputting errors and doesn't even start due to wrong include order (and maybe more)

**Comment by rishijoshi** [comment]
The below error shows up with the example.
http://rawgit.com/pablojim/highcharts-ng/master/example/maps/example.html
Uncaught TypeError: angular.module(...).component is not a function
    at highcharts-ng.min.js:8
    at highcharts-ng.min.js:8

Does the highcharts-ng have support for map-bubbles?
