### ISSUE TITLE
What does "equality checks" mean in terms of slowness as mentioned in caveats section?

### ISSUE THREAD

**Issue by george-hawkins-aa** [pablojim/highcharts-ng#429]
Hello Barry - sorry to use an issue as a messaging mechanism.

We've noticed a considerable performance difference between using Highcharts in a non-Angular context and when using it via highcharts-ng (for what I would call midsize datasets).

Could you tell us something about the costs imposed via "equality checks" as mentioned in the caveats section of your README?

Sorry if the term "equality checks" should immediately mean something to the average Angular developer (I work mainly on the backend - in Java - on providing the data that is ultimately consumed via Highcharts).

Is there anything that can be done to minimize these checks or otherwise mitigate the cost?

**Comment by pablojim** [comment]
@george-hawkins-aa 

Angular and Highcharts-ng does regular checks to see if any data in the scope has changed. To do this it does a recursive check on the objects in the scope - this is the equality checks mentioned.

If you have lots of charts or lots of data then iterating through all the charts and data doing this check can be slow.

If you don't update you data you can add the following option.

<highchart config="chartConfig" disable-data-watch="true">
 
This may help performace.

This plugin captures the general case for charts lots of other (better?) optimisations are possible if the exact use case is known. Maybe it's best to create a jsfiddle showing the exact problem

**Comment by george-hawkins-aa** [comment]
You wrote:
> If you don't update you data you can add the following option.

I guess you then intended to paste in some option name or something following this but forgot? I don't see an option name or anything similar in your comment.

The data in our charts does not change regularly - so I guess what we need is to be able to disable the automatic watching and instead explicitly call `$apply()` (as outlined in this [SO answer](http://stackoverflow.com/a/9693933)) when changes are made.
