### ISSUE TITLE
how to get selected points?

### ISSUE THREAD

**Issue by kobiburnley** [pablojim/highcharts-ng#430]
What is the right way to do something like this example using the angular directive?
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/maps/demo/rich-info/

**Comment by pablojim** [comment]
You would have to alter the directive to achieve this.

**Comment by SnpDeveloper** [comment]
We are also having a similar issue, I want to get all selected map points? is there any way without overriding default select event?
