### ISSUE TITLE
Highchart point is not right in its line

### ISSUE THREAD

**Issue by ssuhat** [pablojim/highcharts-ng#431]
I'm using Highchart (Highstock type) for my statistic. But got a  slight problem. 

See below screenshot:

[![Problem][2]][2]

As you can see the point is not in correct line with 25 December. 
I've tried to remove all my style but still like that. 

Here is my data to use for highcharts:

And here is my setting:

    var arr = [[1450976400000, 265567],[1451062800000,263272],[1451149200000,268065],[1451235600000,197184]];
    $scope.chartConfig = {
        useHighStocks: true,
        options: {
            title: {
                text: 'Hello'
            },
            chart: {
                type: 'StockChart',
                zoomType: 'x',
                alignTicks: true
            },
            navigator: {enabled: false},
            scrollbar: {enabled: false},
            legend: {enabled: true},
            tooltip: {
                dateTimeLabelFormats: {
                    millisecond: "%A, %b %e",
                    second: "%A, %b %e",
                    minute: "%A, %b %e",
                    hour: "%A, %b %e",
                    day: "%A, %b %e, %Y",
                    week: "Week from %A, %b %e, %Y",
                    month: "%B %Y",
                    year: "%Y"
                }
            }
        },
        series: []

    };

    $scope.chartConfig.series.push(
        {
            name: key,
            gapSize: 5,
            type: 'area',
            data: arr,
            animation: true,
            marker: {
                enabled: true,
                radius: 3
            },
            shape: 'square',
            shadow: true
        }
    );

Any solution?

https://jsfiddle.net/z1rar1sq/4/

  [1]: https://github.com/pablojim/highcharts-ng
  [2]: http://i.stack.imgur.com/HPCkw.png

**Comment by pablojim** [comment]
I'd guess this is a UTC/Timezones problem. Best to reproduce it in vanilla highcharts and then ask on the Highcharts forums/stackoverflow.
