### ISSUE TITLE
Plot background color animates in simple spline

### ISSUE THREAD

**Issue by mpedersen15** [pablojim/highcharts-ng#434]
First off, thank you for the great directive! 

I've got a simple spline chart in my angular app, and the plotBackgroundColor seems to animate from outside the plot area on load. 

Check out this fiddle  <a href="http://jsfiddle.net/mpedersen15/3mnvne21/2/">here</a> to see what I'm talking about. 

Is this behavior expected? I would like to configure the chart so that the background remains static as it does <a href="http://jsfiddle.net/mpedersen15/r6a3tyfw/">here</a> (using just Highcharts, not with Angular). Is there a way to do this?

Thank you for the help!

**Comment by roydondsouza** [comment]
Hi @mpedersen15 

I added `animation: false` on line no. 11. 
Check [here](http://jsfiddle.net/3mnvne21/3/)

If you want to stop animating the series you can do so. 
```
plotOptions:{
....
...
 series: {
        animation: false
    }
}
```

Hope this helps!

**Source:**
Stackoverflow [question](http://stackoverflow.com/questions/13831501/highcharts-turn-animation-false-for-line-chart)
Highcharts [documentation](http://api.highcharts.com/highcharts#chart.animation)

**Comment by mpedersen15** [comment]
Works like a charm! Thank you for the help, @roydondsouza!
