### ISSUE TITLE
Advanced timeline chart doesn't redraw after AJAX.

### ISSUE THREAD

**Issue by manishrw** [pablojim/highcharts-ng#436]
After dynamically loading the data, and changing the timeline chart config, the chart doesn't redraw. 
The issue seems to be with this chart itself, as other graphs are working fine.

Chart - http://www.highcharts.com/demo/combo-timeline

**Comment by pablojim** [comment]
jsfiddle please

**Comment by manishrw** [comment]
Issue is resolved, it was due to Javascript references. While dynamically updating the object, the original object pointed by the highcharts config gets lost and is not updated.
