### ISSUE TITLE
How to combine two series into one chart

### ISSUE THREAD

**Issue by samwzm** [pablojim/highcharts-ng#443]
Hi, there,

could anyone share an example with me about how to combine two series into one chart using directive? those two series have different y axis values, so they can't share the same y axis. For example, the right y axis represents price (the data range is from 0 ~ 100), the left y axis represents volume (the data range is from -9000 ~ 9000). In this case, the right y axis must use different scale with left y axis, otherwise, the price series is almost a line.

thanks,
Sam

**Comment by KieranDotCo** [comment]
I haven't tried this but there is an example on the Highcharts site which might be useful to you

http://www.highcharts.com/demo/combo-multi-axes
