### ISSUE TITLE
Highchart colors keep changing

### ISSUE THREAD

**Issue by arsinawaz** [pablojim/highcharts-ng#448]
Hi all,

I am using highcharts and the colors keeps changing when i refresh the chart with different data. Here is my theme object:

        Highcharts.theme = {
            colors: [
                // Main Colours
                /* '#1E73AA', '#C44441', '#55BF3B', '#7A5992',
                '#009AB2', '#F08736', '#8EAACF', '#CE7057', '#737373' */
                '#2691d9','#cf6563','#79cf63','#9d81b1','#33e4ff','#f39b58','#a6bcd9','#d78a75','#a6a6a6'
           ],
            legend: {
                itemStyle: {
                    font: '9pt Trebuchet MS, Verdana, sans-serif',
                    color: 'black'
                },
                itemHoverStyle:{
                    color: 'gray'
                }   
            },
            lang: {
                decimalPoint: ',',
                thousandsSep: ' '
            }
        };

        // Apply the theme:
        Highcharts.setOptions(Highcharts.theme);

It chooses the colors from the which i have provided but it keeps choosing dynamically. The default behavior of highcharts is to select the first color for first series all the time if there is second series then it should select second color from theme.

Here is the fiddle with just highcharts: http://jsfiddle.net/sffnk2k1/
Here is the fiddle with highcharts and ng-highcharts: http://jsfiddle.net/Lurau4s7/

Many thanks in advance.

**Comment by levipadre** [comment]
Any result? I have the same problem

**Comment by levipadre** [comment]
Try to override the colors within the options.
```
$scope.chartConfig = {
   options: {
      colors: ['#2691d9']
   }
}
```

**Comment by arsinawaz** [comment]
@levipadre  Thank you for your contribution but its does not solve my problem, i want to use multiple colors so that if there are multiple series then different colors should be applied to different series and they should stay same color even if data changes (Which is the default behavior of highcharts).

**Comment by arsinawaz** [comment]
It looks like the difference is that the regular version is destroying the chart completely and building a new one, which will cause the series to use the first color - but the ng-version is not entirely destroying the chart, which causes each iteration to increment the series counter, and choose the next color.

**Comment by ray-peters** [comment]
Same thing happening here using `highcharts-ng`. Chart is inheriting some strange fillColors from... seemingly nowhere.

**Comment by umutgithub** [comment]
When color added to series array color doesn't change anymore.  for multiple sets you can do 
series[0]. color ="yellow" 
series[1]. color ="blue" 

series: [{
            color:'blue',
            name: 'New York',
            data: [-0.2, 0.8, 5.7, 11.3, 17.0, 20.0, 26.8, 23.1, 20.1, 15.1, 8.6, 2.5]
          }]

hope this helps

**Comment by umutgithub** [comment]
Anyone has come up with this issue?

**Comment by mcalamosca** [comment]
I'm also having this issue, has anyone found a solution?

**Comment by umutgithub** [comment]
I track series array and it's values. If not change I don't send the series array to config. If it did then I send. This helps to keep the colors same

**Comment by pablojim** [comment]
@arsinawaz  @umutgithub @mcalamosca  @ray-peters 

you can force highcharts-ng to refresh the whole chart by setting an option that it doesn't know how to handle. e.g. the dummy property 'foo' here: http://jsfiddle.net/oxc5q4y5/
