### ISSUE TITLE
Call reset zoom button manually

### ISSUE THREAD

**Issue by levipadre** [pablojim/highcharts-ng#449]
Hi can I call manually the Reset zoom button? I change the data dynamically, and I would like to call the reset event somehow and makes it disappear. I tried with the currentMin and currentMax, but nothing:

```
vm.chartConfig.xAxis.currentMin = null;
vm.chartConfig.xAxis.currentMax = null;
```

**Comment by akio46** [comment]
I need to zoom in/out specific area of highchart programmatically, how can i do this?
