### ISSUE TITLE
How to disable legend?

### ISSUE THREAD

**Issue by kramer65** [pablojim/highcharts-ng#450]
I'm trying to disable the legend in my application using the 

    legend: {
        enabled: false
    }

but unfortunately that doesn't seem to work.

Does anybody know how I can disable the legend using highcharts-ng? 

All tips are welcome!

**Comment by benelliott** [comment]
Ensure that you are adding this field to <configObject>.options rather than the base config object itself.

**Comment by pablojim** [comment]
Thanks @benelliott
