### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by gaelduplessix** [pablojim/highcharts-ng#452]
Hi!

Is there any way to know when the last release is scheduled for ? Last release is not very convenient to use with Webpack/Browserify/... And this PR fixed the problem: https://github.com/pablojim/highcharts-ng/pull/428 but I have to depend on master to use it right now.

Thanks !

**Comment by graingert** [comment]
@pablojim any chance of a release soon?

**Comment by graingert** [comment]
@gaelduplessix I've released highcharts-ng-next@0.0.13

**Comment by graingert** [comment]
@pablojim hey, it would be great to get a new release

**Comment by pablojim** [comment]
Planning to get a release it next week. Thanks for chasing!

**Comment by pablojim** [comment]
0.0.12 released

**Comment by graingert** [comment]
Sweet

**Comment by pablojim** [comment]
@graingert Thanks for all the work on this!
