### ISSUE TITLE
highmaps drilldown click event not firing

### ISSUE THREAD

**Issue by ragefuljoe** [pablojim/highcharts-ng#453]
_UPDATE_
got this working, had to do all the property settings on all avail mapdata things in my config, not just the main one.

I set this in my chart config

```
 options: {
            chart: {
                events: {
                    drilldown: function (event) {
                         console.log(event);
                    }
                }
            },
```

But the drilldown event does not seem to fire. Replacing `drilldown` with `click` captures clicks outside of map area, but that won't do what I need.

I do have modules/drilldown.js loaded up as well. Any help or hints appreciated.

thanks

**Comment by Taxman972** [comment]
Same for me any update about this bug ?

**Comment by janey0536** [comment]
same for me. Any update? @ragefuljoe Could you please attach a jsfiddle for your update? Appreciate your help.

**Comment by ragefuljoe** [comment]
I used a service to generate chart config objects, here's what I have for maps:

https://gist.github.com/ragefuljoe/fa642ab632f6787d20a127720d65caa5

**Comment by FilipLukac** [comment]
Same for me - drilldown and drillup events are not firing
