### ISSUE TITLE
Markers are not beying hover-disabled

### ISSUE THREAD

**Issue by bcupello** [pablojim/highcharts-ng#458]
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-marker-enabled/

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-marker-enabled-false/

There are those 2 examples from the API Reference, but the markers are not disabled when you hover the graph. Neither is the halo.

**Comment by matinca** [comment]
Hover is set by the tooltip option. Your examples use highcharts and not highcharts-ng.

**Comment by bcupello** [comment]
Would you mind show me an example?

Thanks a lot!
