### ISSUE TITLE
can't change chart type

### ISSUE THREAD

**Issue by Cyneric** [pablojim/highcharts-ng#461]
fix - highcharts-ng.js:
if(config.chart.type) {
        mergedOptions.chart.type = config.chart.type;
}

**Comment by Rafi993** [comment]
could you provide plunker

**Comment by wandiong** [comment]
can you provide the plunker or either quote your full code of that function which provides different config?

or you can try mine . https://github.com/pablojim/highcharts-ng/issues/510

**Comment by pablojim** [comment]
@wandiong thanks
