### ISSUE TITLE
Same config in Highcharts and ng-highcharts but differents results

### ISSUE THREAD

**Issue by RemiAWE** [pablojim/highcharts-ng#463]
Hello,

I have the same simple config in Highcharts and Ng-highcharts. A basic chart with the chart type defined in the "serie" object. I set the "serie" to the "bar" type. In highcharts the result is a bar chart, in ng-highcharts the result is a column chart. Why ?

In Highcharts:
http://jsfiddle.net/remichanaud/t5ddm1ba/
Ng-Highcharts:
http://jsfiddle.net/remichanaud/dxg4a5ab/

**Comment by jerryjoseph-net** [comment]
It is because the "type" should be mentioned under "options" for highcharts-ng.

See http://jsfiddle.net/dxg4a5ab/6/

**Comment by RemiAWE** [comment]
Thank you for your help ! It works.

But why is there a difference between the Highcharts config and the Ng-Highcharts config ?

**Comment by pablojim** [comment]
See the faq!
