### ISSUE TITLE
chart.reflow causes initial animation to be stopped or skipped

### ISSUE THREAD

**Issue by SushantKadam008** [pablojim/highcharts-ng#467]
I am using highchrat in a modal popup. I managed to get the chart working in the popup.
But when I use chart.reflow, there is no animation in the first load.
All the subsequent times the animation works.

Is there a way to fix this ? 

Regards,
Sushant Kadam

**Comment by ibsenleo** [comment]
Workaround
You could delay the data loading by assign it with a timeout

`
$timeout (function(){
  chartConfig.series[0].data[0] = [ <your data> ]
}, 100)
`
This may vary depending on your chart.
Is a workaround, so would be great to fix it on the library, but i think this could work fine regardless i haven't tried.

Good luck!
