### ISSUE TITLE
highcharts-ng width resize issue in ngDialog

### ISSUE THREAD

**Issue by smrutiranjan727** [pablojim/highcharts-ng#473]
Highcharts is not rendering properly inside an ngDialog popup when it's is opened. It never fits inside the dialog. But after resizing the window the chart automatically changes the width property and fits into it. Why doesn't it fit to the dialog window when dialog popup is loaded?

Thank You!!!

**Comment by ivannoel** [comment]
You can try using the reflow function in a call back or _after_ the DOM has rendered the parent container to resize the chart with respect to its parent. A bit dodgy but it will get the job done.

`$(element).highcharts().reflow()`

**Comment by suggy75** [comment]
I have this issue also, and used a tip from a similar issue raised previously. It's a bit hacky but it seems to work.
Add the following to your chart config...

`func: function (chart) {
          $timeout(function () {
            chart.reflow();
          }, 1000);
        }`

chart.reflow() stops the animation so you can set a longer timeout to allow animation before calling reflow(), which resizes the chart correctly. The downside to this is the chart jumps after a second.
