### ISSUE TITLE
range-selection buttons are gone!

### ISSUE THREAD

**Issue by jjsanabria** [pablojim/highcharts-ng#474]
Hello,

I'm using highstocks and of course highcharts-ng. 

No jquery and no standalone-framework.js adapters since it was working just fine without the later script.

Anyway, today Monday I noticed  that my "range-selection" buttons are gone, as well as the 'x' axis scrolling bar for my line chart.
I also noticed that a new highstocks version was posted during the weekend, v4.2.5.
Firebug shows the following error on the console: "scroller.baseSeries is undefined" (line 22406).

Any pointers would be greatly apreciated!!!

Juanjo

**Comment by jjsanabria** [comment]
It's funny, after setting the navigator to true, the buttons reapear!!!!

`  $scope.chartConfig = {
    useHighStocks: true,

    options: {
        chart: {
          type: 'line', 
          zoomType: 'x'
        },

      navigator: {
        enabled: true
      },`


Still getting the "scroller.baseSeries is undefined" error message though.

Cheers,

Juanjo.

**Comment by manojasm** [comment]
i am also getting that error when i keep my navigator enabled to true but it disappears when i change it to false

**Comment by LastDragon-ru** [comment]
This bug is really exists in v4.2.5 (not in v4.2.4), code to reproduce http://jsfiddle.net/cssx5a8r/
