### ISSUE TITLE
TypeError: $scope.chartConfig.series[0].removePoint is not a function.  And the same to addPoint(), setData().... and so on

### ISSUE THREAD

**Issue by SophiaWSJWong** [pablojim/highcharts-ng#477]
The code is as follow.
            
    $scope.chartConfig = {
                    options: {
                        chart: {
                            zoomType: 'x',
                            height: 250,
                            width: 1380,
                        },
                        rangeSelector: {
                            enabled: false,
                            selected: 0
                        },
                        xAxis:{
                        },
                        yAxis: {
                            allowDecimals:false,
                            title: {
                                text: 'EOG II'
                            }
                        },
                        colors: ['#7cb5ec'],
                        navigator: {
                            enabled: true
                        }
                    },
                    series:  [{
                        name : 'LEFT EEG',
                        data : (function () {
                            return twoParts.leftData;

                        }())
                    }],
                    title: {
                        text: 'Alpha'
                    },
                    useHighStocks: true
                },

                if($scope.chartConfig_left) {

                    $scope.chartConfig_left.series[0].removePoint(0);
                    $scope.chartConfig_left.series[0].addPoint([x, y], true, true);
                }

**Comment by pablojim** [comment]
The intention of this plugin is to use change the data directly not to use addPoint and removePoint
