### ISSUE TITLE
Offline export

### ISSUE THREAD

**Issue by arodriguezf** [pablojim/highcharts-ng#479]
Hello, it´s possible to export the images of the graphics using offline export like this: http://www.highcharts.com/docs/export-module/client-side-export  ?

Regards

**Comment by pablojim** [comment]
Possibly. Try and see. Report an error with a jsfiddle if you experience problems.

**Comment by drb-27** [comment]
Couldn't do it. Added file 'offline-exporting.js' to my project folder next to 'exporting.js', but call to 'exportChartLocal' doesn't work while 'exportChart' does. Here's the api docs for this:
http://api.highcharts.com/highcharts#Chart.exportChartLocal

And here's a jsfiddle:
http://jsfiddle.net/drb27/m4pcpv5g/176/

Do I have to manually add a reference to 'offline-exporting.js' somewhere?

Regards
