### ISSUE TITLE
width:100%

### ISSUE THREAD

**Issue by antonioaltamura** [pablojim/highcharts-ng#480]
Hi, how can I set the graph size to width:100%?
If I don't set the width or height as highchart parameters div.highcharts-container and the svg in it takes 600x400 dimensions.

**Comment by pablojim** [comment]
More appropriate to StackOverflow

**Comment by mikepsinn** [comment]
You may need to include `<link href="dist/highcharts-ng.css" rel="stylesheet">` in your project. See [here](https://github.com/pablojim/highcharts-ng#current-version)

**Comment by pablojim** [comment]
thanks @mikepsinn
