### ISSUE TITLE
drop IE8 - IE10 support

### ISSUE THREAD

**Issue by graingert** [pablojim/highcharts-ng#494]
Microsoft has EOL'd every version of IE except 11.

**Comment by pablojim** [comment]
Sure but the effort to maintain it is minimal and unfortunately in some corporate environments old version of IE are still greatly used.

Will reconsider when usage drops further, or the effort of maintaining support increases.

**Comment by graingert** [comment]
Maybe just document how to use core-js? This way we can use indexOf and
reduce

On 15 Jul 2016 19:37, "Barry Fitzgerald" <notifications@github.com> wrote:

Closed #494 <https://github.com/pablojim/highcharts-ng/issues/494>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pablojim/highcharts-ng/issues/494#event-724743932>, or mute
the thread
