### ISSUE TITLE
highmap colors (colorAxis prop) is not working

### ISSUE THREAD

**Issue by umutgithub** [pablojim/highcharts-ng#495]
I have integrated pablo's angular-hihgcharts to gridster widgets. Below is the config object for the highmap. colors are not coming properly. Anyone had the same issue?  Thanks

 var mapConfig = {

                            options: {
                                legend: {
                                    enabled: false
                                },
                                plotOptions: {
                                    map: {
                                        mapData: Highcharts.maps['countries/us/us-all'],
                                        joinBy: ['postal-code', 'code']
                                    }
                                }
                            },
                            chartType: 'map',
                            title: {
                                //text: widget.selectedMapCol
                                text: widget.additionalProperties.chartName
                            },
                            colorAxis: {
                                min: 1,
                                type: 'logarithmic',
                                minColor: '#EEEEFF',
                                maxColor: '#000022',
                                stops: [
                                    [0, '#EFEFFF'],
                                    [0.67, '#4444FF'],
                                    [1, '#000022']
                                ]
                            },
                            series: [
                                {
                                    animation: {
                                        duration: 1500
                                    },
                                    data: widget.results.mapdata[widget.selectedMapCol],
                                    mapData: Highcharts.maps['countries/us/us-all'],
                                    joinBy: ['postal-code', 'code'],
                                    dataLabels: {
                                        enabled: true,
                                        color: 'white',
                                        format: '{point.code}'
                                    },
                                    name: 'Population density',
                                    tooltip: {
                                        pointFormat: '{point.code}: {point.value}'
                                    }
                                }
                            ]
                        };
                        widget.chartConfig = mapConfig;

<img width="454" alt="screen shot 2016-07-15 at 1 02 31 pm" src="https://cloud.githubusercontent.com/assets/11237530/16882328/76d26510-4a8c-11e6-919b-aa3dd521a77b.png">

should be like this 
<img width="305" alt="screen shot 2016-07-15 at 1 03 34 pm" src="https://cloud.githubusercontent.com/assets/11237530/16882356/94525ffa-4a8c-11e6-9b67-5c1919c161bb.png">

**Comment by pablojim** [comment]
You need to move colorAxis into the options object. If you are still having problems make a jsfiddle and I can help there.

**Comment by umutgithub** [comment]
Thanks pablo! This helped big time. You are the man!!!
