### ISSUE TITLE
Graphs don't fit the container when resizing it

### ISSUE THREAD

**Issue by maximelafarie** [pablojim/highcharts-ng#499]
The graphs are well displayed when the page is loaded, but when you want to resize it the graphs are not fitting the container.

I already put `func: function (chart) { $scope.$evalAsync(function () { chart.reflow(); }); }` at the end of each graph's configuration, and I don't set any width to them.

**Comment by TimeBomb006** [comment]
+1

**Comment by adwerrd** [comment]
+1
