### ISSUE TITLE
Synchronized chart for highcharts

### ISSUE THREAD

**Issue by fizerkhan** [pablojim/highcharts-ng#503]
HighCharts supports synchronised chart http://www.highcharts.com/demo/synchronized-charts. This is most useful when we are showing multiple related charts in a single page.

Do `highcharts-ng` have support for it? If yes, can you please provide example for it?

**Comment by df-jsykes** [comment]
Yes. Already covered.

https://github.com/pablojim/highcharts-ng/issues/243

**Comment by pablojim** [comment]
@df-jsykes thanks
