### ISSUE TITLE
Angular 2 highcharts

### ISSUE THREAD

**Issue by alaa-bourouissi** [pablojim/highcharts-ng#506]
I'm using highchart with angular 2 , the charts works fine , but the export button (PNG-JPEG-PDF-SVG ) doesn't work 
any suggestions ??

**Comment by Rafi993** [comment]
If you are using angular2 please use https://github.com/gevgeny/angular2-highcharts or https://www.npmjs.com/package/ng2-highcharts. please close the issue if it is solved
