### ISSUE TITLE
Tooltip Formatter not working

### ISSUE THREAD

**Issue by justinator92** [pablojim/highcharts-ng#512]
I had troubles showing a tooltip with a formatter function. It always showed the default tooltip while ignoring the formatter function. 

I found out that the tooltip property was not taken into the new mergedOptions dictionary inside the highcharts-ng module. I had to insert the 3 lines of code by myself to make it work.

 if (config.tooltip) {
          mergedOptions.tooltip = config.tooltip;
}

**Comment by smallg** [comment]
can you provide online test demo, like plnkr.
