### ISSUE TITLE
Disabled datawatch and modifying config.series

### ISSUE THREAD

**Issue by jschuler** [pablojim/highcharts-ng#515]
Hi,

Currently hitting this error:
TypeError: Cannot read property 'length' of undefined
![image](https://cloud.githubusercontent.com/assets/869106/19160296/584ac480-8bbd-11e6-8486-01de60bed42a.png)

Looking at the trace, after modifying the series it goes into here:

```
if(scope.disableDataWatch){
        scope.$watchCollection('config.series', function (newSeries, oldSeries) {
          processSeries(newSeries);
          chart.redraw();
        });
      }
```

But oldSeries is not passed into the processSeries function, so when it hits the line above it results in an error. This was working in previous version.

Thanks,
Joachim

**Comment by pablojim** [comment]
Could you make a jsfiddle please?

**Comment by jschuler** [comment]
Added jsfiddle here:
http://jsfiddle.net/Cp73s/5411/

1. On highcharts directive: disable-data-watch="true"
2. Click Add Series results in error

Thanks!

**Comment by pablojim** [comment]
@jschuler Thanks for the report. Fixed in master
