### ISSUE TITLE
Support module loader

### ISSUE THREAD

**Issue by houssemba** [pablojim/highcharts-ng#516]
I'd like to import the directive directly in my app (ES6).
The problem is that the current code suppose to have Highcharts as a global variable attached to window.
So I need to do this hack

``` javascript
import Highcharts from 'highcharts/highcharts.js';
window.Highcharts = Highcharts;
import HighchartsNg from 'highcharts-ng';
```

It would be great if the syntax support a module loader (https://github.com/umdjs/umd).

**Comment by pablojim** [comment]
Sounds like a good idea. We could use https://github.com/bebraw/grunt-umd any chance of a PR?

**Comment by feitzi** [comment]
In case you use Webpack, you can use this fix  until module loaders will be supported.

webpack.config.js:
``` js
//...
 plugins: [
    new webpack.ProvidePlugin({
            Highcharts: "highcharts"
        })
  ]
```

**Comment by pablojim** [comment]
see #572
