### ISSUE TITLE
bubble chart supported?

### ISSUE THREAD

**Issue by Hesesses** [pablojim/highcharts-ng#518]
http://jsfiddle.net/6j9kfggd/1/

If I change the chart type from "scatter" to "bubble" it doesnt work.

**Comment by Hesesses** [comment]
Is this support or just a bug?

**Comment by eMerzh** [comment]
isn't it in highcharts-more or smth ?

**Comment by pablojim** [comment]
@eMerzh is right you need highcharts-more
