### ISSUE TITLE
Question - Support for Highchart 5

### ISSUE THREAD

**Issue by guylhermetabosa** [pablojim/highcharts-ng#520]
Hi, congrats for the directive.

Since Highchart 5 was just released, I would like to know if it is planned to support the new version.

http://www.highcharts.com/news/236-highcharts-5-0?utm_medium=email&sslid=szA0srCwNDA3N7cEAA&sseid=MzY3Mze2sDC0BAA&jobid=9b722cc6-e69e-463d-b8c8-54f943e56133

**Comment by houssemba** [comment]
I'm using the directive with Highchart 5 and I have no problem until now.

**Comment by guylhermetabosa** [comment]
I started with v4.2.7 and I tried to migrate to 5 and my charts are totally black in background.

**Comment by pablojim** [comment]
Good question. The new Chart update api will mean the plugin can be simplified greatly. A weekend project sometime soon!

I would expect it to still more or less work with HC5 raise a bug if anything seems broken.

http://api.highcharts.com/highcharts/Chart.update
