### ISSUE TITLE
How to make the chart updating every second ?

### ISSUE THREAD

**Issue by MaadMax** [pablojim/highcharts-ng#524]
I haven't any idea how to reproduce that : http://www.highcharts.com/demo/dynamic-update

However, is it possible with highcharts-ng ?

**Comment by pablojim** [comment]
Just update the series data every second with a call to $timeout? If it doesn't work post a jsfiddle with your best attempt and I'll try help.

**Comment by MaadMax** [comment]
You mean $interval ? Anyway, with $interval it works like a charm. Thanks !

**Comment by pablojim** [comment]
yep $interval is good too!
