### ISSUE TITLE
For a large data set x-axis categories are not plot.

### ISSUE THREAD

**Issue by dilani-maheswaran** [pablojim/highcharts-ng#525]
When I generate a column / bar chart with a data set of 168 records, the x-axis labels are plot as numbers apart from the first label.
Example:
[http://jsfiddle.net/dilani_di/2554kx8x/5/](url)

If I un-select and select the legend, then it shows the correct x-axis values.

**Comment by pablojim** [comment]
Can you create a jsfiddle showing the correct behaviour you want in vanilla highcharts.

**Comment by dilani-maheswaran** [comment]
http://jsfiddle.net/dilani_di/u5j9a10r/
The issue is demonstrated in the above fiddle. 
Issue got solved after i added cropThreshold and turboThreshold
          series: [
            {
            	turboThreshold: 0,
              cropThreshold: 500,

https://jsfiddle.net/dilani_di/0ox0vmjk/

Thanks.
