### ISSUE TITLE
Series dataGrouping

### ISSUE THREAD

**Issue by andymccorkell** [pablojim/highcharts-ng#526]
Hey,

I'm looking for an example of dataGrouping in action or some advice on how it should be implemented in highcharts-ng. I've used it many times with Highcharts but struggling to get it working with highcharts-ng.

I'm not getting any error, just no grouping, I normally do this at the series level but also tried in `options`:

```
series: [
    {
        name: "Readings",
        data: readings,
        yAxis: 0,
        dataGrouping: {
            enabled: true,
            smoothed: true,
            approximation: "high",
            groupPixelWidth: 20
        }
    }
]
```

Anyone had any luck with dataGrouping?

**Comment by pablojim** [comment]
Maybe try make a jsfiddle showing it not working. Or even better one with vanilla highcharts and one with highcharts-ng

**Comment by DilMahesh** [comment]
I am facing the same issue. My x-axis is dates and I am not able to group chart by year.  
[http://jsfiddle.net/46rhz/578/ ](url) This fiddle demostrates the issue.

    series: [{
                        data: [ 
                            [1357370470000,65] , 
                            [1357370470000,165],
                            [1483600871,71] , 
                            [1483600871,52] ],
                        dataGrouping: {
                              approximation: "sum",
                              enabled: true,
                              forced: true,
                              units: [['year',[1]]],

                          }
      }]
The expected chart is 
![image](https://cloud.githubusercontent.com/assets/24932821/21677574/c0ca940a-d360-11e6-8f41-1c889a82e217.png)
out of 4 data points, 2 points belong to year  2013 and other two points belong to year 2017 Where both points are sum of each year. But the actual chart given on the above fiddle has four data points ( one point for each year. grouping is not applied).
