### ISSUE TITLE
graph doesn't update when series changes in highchart-ng 0.13 

### ISSUE THREAD

**Issue by MHL3060** [pablojim/highcharts-ng#528]
when a series is updated, the graph doesn't redraw. this is use to work in 0.11

an examples is in
http://jsfiddle.net/6p39mdye/1/

**Comment by MHL3060** [comment]
I added the setTimeout section.

**Comment by pablojim** [comment]
You need to use angular $timeout: http://jsfiddle.net/uys5qrf2/

As far as I'm aware nothing has changed with this.
