### ISSUE TITLE
referencing options dynamically

### ISSUE THREAD

**Issue by MichaelGradek** [pablojim/highcharts-ng#530]
If you have to draw a series of charts using `ng-repeat`, you need to assign the `options` attribute dynamically, however, this does not work:

```
<tr ng-repeat="user_id in user_ids">
    <td>
        <highchart config="highchartsNG['{{ user_id }}']"></highchart>
    </td>
</tr>
```

**Comment by pablojim** [comment]
Hard to tell without a jsfiddle. Could you try just `<highchart config="highchartsNG[user_id]"></highchart>`

See: http://jsfiddle.net/pablojim/6b929n92/
