### ISSUE TITLE
 Uniform series shift when series added or updated

### ISSUE THREAD

**Issue by VincentGuedes** [pablojim/highcharts-ng#534]
When adding or updating a series in the highcharts config object, constant series get shifted along the x-axis. 
As an indication for those facing this problem, setting the data directly via the highcharts object furnished by `configObject.getHighcharts()` can be used as a workaround.

https://jsfiddle.net/VincentGuedes/r4c4oweh/

**Comment by pablojim** [comment]
That is strange. I'll have a look. Please have a look at the Beta version and see if the problem occurs there too. https://github.com/pablojim/highcharts-ng/tree/highcharts-ng2

**Comment by VincentGuedes** [comment]
Hello Barry,
I'll check it out. Looking at the directive code the issue seems to stem
from the processSeries function which makes a call to highchart's function
to add a point and shift the series - which I presume is wanted behaviour
in the case of continuously updated series. The function seems to take that
path after comparing 'new' and 'old' series (which are the same in this
case) by the way it compares the series : from what I remember it takes a
point from the new series , sticks it onto a copy of the old one, shifts
this and then compares the result to the new series, so they'll be equal in
the case of a constant series.
That's how far I looked into it, if it may help.

Cheers
(and thanks for your plugin we've been using here at work ;) )

Le 24 nov. 2016 6:26 PM, "Barry Fitzgerald" <notifications@github.com> a
écrit :
