### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by wiggitamoo** [pablojim/highcharts-ng#537]
I am trying to add a rounded-corners library to highcharts-ng.

[https://github.com/highcharts/rounded-corners/blob/master/rounded-corners.js](https://github.com/highcharts/rounded-corners/blob/master/rounded-corners.js)

After adding it to the project I add the following code for my chartConfig options.

```
{
 "options": {
   "chart": {
     "type": "column"
   },
   "legend": {
     "enabled": true
   },
   "plotOptions": {
     "column": {
       "borderRadiusTopLeft": 10,
       "borderRadiusTopRight": 10
     }
   }
 },
 "series": [
   {
     "data": [["11",18],["1",31],["1", 31],["3", 29]],
     "id": "series-1"
   }
 ],
 "title": {
   "text": "t"
 },
 "xAxis": {
   "title": {
     "text": "Sales"
   },
   "type": "category"
 },
 "yAxis": {
   "title": {
     "text": "Vehicles"
   }
 }
}
```

For some reason, the library doesn't get triggered when the chart loads. Do you know how we can get this feature supported?

**Comment by pablojim** [comment]
2 suggestions:
- make a failing jsfiddle
- try the beta https://github.com/pablojim/highcharts-ng/tree/highcharts-ng2
