### ISSUE TITLE
drilldown not surpported 

### ISSUE THREAD

**Issue by Hsensor** [pablojim/highcharts-ng#538]
when I use highcharts-ng , I found config.drilldown not surpported.  if drilldown will be surpported

**Comment by VictorioBerra** [comment]
> The drilldown feature requires the drilldown.js file to be loaded, found in the modules directory of the download package, or online at code.highcharts.com/modules/drilldown.js.

As per the official documentation [here](http://api.highcharts.com/highcharts/drilldown).

**Comment by Hsensor** [comment]
I have required "highcharts/modules/drilldown"  when I give the issue; I found the Pie with drilldown not work.

The code is shown below.

require("highcharts/modules/drilldown")(window.Highcharts);
Highcharts.setOptions({global: {useUTC: false}});
require("highcharts-ng");

**Comment by Hsensor** [comment]
I have required "highcharts/modules/drilldown"  when I give the issue; I found the Pie with drilldown not work.

The code is shown below.

require("highcharts/modules/drilldown")(window.Highcharts);
Highcharts.setOptions({global: {useUTC: false}});
require("highcharts-ng");

thanks again !

**Comment by Hsensor** [comment]
I have required "highcharts/modules/drilldown"  when I give the issue; I found the Pie with drilldown not work.

The code is shown below.

require("highcharts/modules/drilldown")(window.Highcharts);
Highcharts.setOptions({global: {useUTC: false}});
require("highcharts-ng");

thanks again !

**Comment by Hsensor** [comment]
I have required "highcharts/modules/drilldown"  when I give the issue; I found the Pie with drilldown not work.

The code is shown below.

require("highcharts/modules/drilldown")(window.Highcharts);
Highcharts.setOptions({global: {useUTC: false}});
require("highcharts-ng");

thanks again !

**Comment by Hsensor** [comment]
I have required "highcharts/modules/drilldown"  when I give the issue; I found the Pie with drilldown not work.

The code is shown below.

require("highcharts/modules/drilldown")(window.Highcharts);
Highcharts.setOptions({global: {useUTC: false}});
require("highcharts-ng");

thanks again !

**Comment by Hsensor** [comment]
I have required "highcharts/modules/drilldown"  when I give the issue; I found the Pie with drilldown not work.

The code is shown below.

require("highcharts/modules/drilldown")(window.Highcharts);
Highcharts.setOptions({global: {useUTC: false}});
require("highcharts-ng");

thanks again !

**Comment by VictorioBerra** [comment]
[Here is a jsfiddle of drilldowns working with highcharts-ng2 **beta** ](http://jsfiddle.net/Lord_Zero/LnkgL135/10/)

- Angular 1.5.6
- Highcharts 5.x

**Comment by Hsensor** [comment]
@VictorioBerra  thank your again ! 
I found highcharts-ng 
`if (config.options) {
        mergedOptions = deepExtend(defaultOptions, config.options);
} else {
        mergedOptions = defaultOptions;
}`

just merge config.options;but I do like this config.drilldown ,not like config.options.drilldown . so not show drilldown. now work fine. 

thanks again.

if we can add some code to config.drilldown work fine.

like this 
`if(config.drilldown){
     mergedOptions.drilldown = config.drilldown;
}`
