### ISSUE TITLE
Highcharts-ng loading indicator issue

### ISSUE THREAD

**Issue by manatarms** [pablojim/highcharts-ng#539]
I have a very strange angular issue that I've been trying to solve for a while now, but can't seem to get it working. Any help is appreciated.

I have an angular service that pushes csv data into my highchart-ng. Before I put in the data I want to show the loading indicator, and once it's done I want to turn it off.

My issue currently is that it turns on the loading indicator after completing the load, not before. After which it is instantly turned off because of the promise. It's like the UI is freezing, but it's not because I can still move the webpage. I've tried moving around the code, but it's not doing what I want it to. A new perspective would really help.

**Here's my processCsv function that accepts the csv data and calls the csvService**
 
    function processCsv(results){
        $scope.chartConfig.loading = true;

        // Tried this as well, but doesn't work
        // $scope.$apply(); 

        var csvServicePromise = csvService.csvHandler(results.data, $scope.chartConfig);

        $scope.$apply();

        csvServicePromise.then(function() {
                $scope.chartConfig.loading = false;
        });
        $rootScope.$broadcast('csvUploaded', [results]);  
     }

**Here is my csvHandler function**

     function csvHander(content, chartConfig) {
        if (content !== null) {
       
      //Left the call in case I want to separate this function later
        processLargeArrayAsync(content);
        function processLargeArrayAsync(array, maxTimePerChunk) {
            maxTimePerChunk = maxTimePerChunk || 200;
            var index = 1;//Start from 1 to skip headings
            var rowLenght = array.length;
            function now() {
                return new Date().getTime();
            }

            function doChunk() {
                var startTime = now();
                while (index < rowLenght && (now() - startTime) <= maxTimePerChunk) {
                    for(i=0;i<content[index].length;i++){
                        switch (i) {
                            case 0:
                                chartConfig.xAxis.categories.push(parseFloat(content[index][i]));
                                break;
                            case 1:
                                chartConfig.series[0].data.push(parseFloat(content[index][i]));
                                break;
                            case 2:
                                chartConfig.series[1].data.push(parseFloat(content[index][i]));
                                break;
                            case 3:
                                chartConfig.series[2].data.push(parseFloat(content[index][i]));
                                break;
                            case 4:
                                chartConfig.series[3].data.push(parseFloat(content[index][i]));
                                break;
                            case 5:
                                chartConfig.series[4].data.push(parseFloat(content[index][i]));
                                break;
                            case 6:
                                chartConfig.series[5].data.push(parseFloat(content[index][i]));
                                break;
                            case 7:
                                chartConfig.series[6].data.push(parseFloat(content[index][i]));
                                break;
                            case 8:
                                chartConfig.series[7].data.push(parseFloat(content[index][i]));
                                break;
                            default:
                                break;

                        }

                    }
                    ++index;
                }
                if (index < rowLenght) {
                    // set Timeout for async iteration
                    $timeout(doChunk, 1);
                }
            }    
            doChunk();    
        }

    } //End Null check 
    return $q(function(resolve, reject) {
        resolve();
    });

    }

I'm assuming angular is doing something weird here. I don't exactly know what.

Thanks for your time and I appreciate any help.

Have a great day!

**Comment by pablojim** [comment]
Could you create a jsfiddle showing the issue?
