### ISSUE TITLE
navigator empty after data changed

### ISSUE THREAD

**Issue by jeyzorus** [pablojim/highcharts-ng#541]
Hello,
I encounter a problem using highstock.js in my angularjs app

#### Expected behaviour
Nagivator update with new data, like highchart plot.

#### Actual behaviour
When i update series data, navigator becames empty.

#### Live demo with steps to reproduce
In my html view
`<highchart config="plot_cfg"></highchart>`

In my controller:

```
function loadData(){

var res=requestService.getSeries(id).query().$promise;
        $scope.plot_cfg.loading = true;
        res.then(function(d){
            var res= [];
            $scope.plot_cfg.title.text = configService.record.timeinterval;
            $scope.plot_cfg.loading = false;
            
            $scope.plot_cfg.series=res;
            //$scope.rplot_cfg.series.showInNavigator=true;
            //reset zoom scale
            $scope.plot_cfg.getHighcharts().redraw();
            $scope.plot_cfg.getHighcharts().zoom();
            $scope.plot_cfg.getHighcharts().xAxis[0].setExtremes();

        });
}

```

loadData() is called first time when user click on show curves. But when we click on other curves and loadData() is called a second time, curves are refresh in main plot, but Navigator becomes empty.

#### Affected browser(s)

any idea ?

**Comment by pablojim** [comment]
Could you try with the latest version (1.0.0)? if it is still broken please create a jsfiddle.
