### ISSUE TITLE
Did something break?

### ISSUE THREAD

**Issue by jhomble** [pablojim/highcharts-ng#545]
I've been using this library and it's been working great. But around yesterday, I get the error:

Uncaught TypeError: angular.module(...).component is not a function on line 11

This issue is also seen in other examples including the jsfiddle on this page:
http://jsfiddle.net/pablojim/LnkgL135/show/

I don't know if this is just me, but even the example on this git is broken on my browser.

**Comment by dheerajps** [comment]
You are not the only one.. 
I get this error on my highcharts :
angular.js:13708 Error: Highcharts error #18: www.highcharts.com/errors/18
    at Object.H.error (https://code.highcharts.com/highcharts.src.js:102:23)
    at https://code.highcharts.com/highcharts.src.js:16372:27
    at Array.forEach (native)
    at H.each (https://code.highcharts.com/highcharts.src.js:1601:44)

Will be watching this space

**Comment by pablojim** [comment]
@jhomble @dheerajps Hi - just in the process of releasing a new version that is backward incompatible with earlier versions.

See the readme for changes!
The new version should be more stable. You can always pin to old versions if you prefer.

**Comment by telmogoncalves** [comment]
Hello all, have you guys managed to fix this issue?
