### ISSUE TITLE
graph types are messed up

### ISSUE THREAD

**Issue by dheerajps** [pablojim/highcharts-ng#546]
May be this might be an duplicate issue.. sorry about that.

A dual y-axis graph is broken, is it a problem with
chart: {
   zoomType: 'xy'
 } 
does this have something to do with "2 way binding to chart xAxis no supported" ? 
Also a line graph shows up for a bar and pie-charts show up as line..
the only console error I get is 
angular.js:13708 Error: Highcharts error #18: www.highcharts.com/errors/18
    at Object.H.error (https://code.highcharts.com/highcharts.src.js:102:23)
    at https://code.highcharts.com/highcharts.src.js:16372:27

Any response will be greatly appreciated

**Comment by pablojim** [comment]
@dheerajps A new version has been released. Can you try with that having read the Readme about the changes?

If you still are having problems let me know and create a jsfiddle.
