### ISSUE TITLE
Suggestion Highcharts-3d support

### ISSUE THREAD

**Issue by ihabadly** [pablojim/highcharts-ng#548]
Is it possible to add support for Highcharts-3d, to enable drawing series with x,y,z values, same way as in the jsfiddle hereby. 
## Steps to Reproduce & Link to Example 

1.http://jsfiddle.net/highcharts/V37Vv/?utm_source=website&utm_medium=embed&utm_campaign=V37Vv
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by pablojim** [comment]
Please attempt it with latest release version and open and issue with links to a js fiddle for any problems found
