### ISSUE TITLE
Resizing to screen size

### ISSUE THREAD

**Issue by ihabadly** [pablojim/highcharts-ng#550]
After updating to latest version the resizing to screen size is not working with normal bootstrap.css
## Expected Behaviour

The chart in previous versions resizes according to screen size using typical bootstrap.css
After latest update, it only resizes if using bootstrap-combined.css

## Current Behaviour

Resizing is not working
## Steps to Reproduce & Link to Example 

1. http://jsfiddle.net/pablojim/LnkgL135/
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by parigi-n** [comment]
I had a lot of troubles with this too, and had to go back from 1.0 to 0.0.13 to fix it.
(Angular 1.5, latest angular-bootstrap and highcharts 5.0.6)

**Comment by brunowebdev** [comment]
I found a solution to resolve it. I added a simple timeout to process the constructor method as late possible at line 33 of highcharts-ng.js file. This worked for me.

**Comment by jaxoserina** [comment]
Hi brunowebdev, 

would you be able to share your fix, please? I've encountered exactly the same issue and wondering if there's an easy fix.

Thanks

**Comment by matewilk** [comment]
+1

**Comment by npetralia** [comment]
Hi,

The problem is coming from passing of a directive to a component.

The reflow function of Highcharts do not work because the code is not able to get the correct width and height of HTML element highcharts.
Previously the directive replace the highcharts element by a div.

There are a lot of problem to use component is the case of highcharts wrapper.

Is is possible to have a version without a component but with the new clean code ?

**Comment by pablojim** [comment]
Hi, I'm looking into this. There is a css fix here: http://jsfiddle.net/pablojim/LnkgL135/48/

**Comment by npetralia** [comment]
@pablojim : it is looking good.

I made a specific reflow function :
`var chart = $scope.chartConfig.getChartObj();
 var parent = $(chart.container).parent().parent();
 var width = parent[0].clientWidth;  
 var height = parent[0].clientHeight;
 chart.setSize(width, height);
 chart.reflow();`

And  i am also looking on renderTo function under the lib : http://api.highcharts.com/highcharts/chart.renderTo

**Comment by ihabadly** [comment]
@pablojim : it works with me but I am stuck trying to enable animation with no luck.

**Comment by brunowebdev** [comment]
Nice!
Try it. I was implemented this on Fuse Angular template and I have troubles to render highcharts.

**Comment by someone1** [comment]
None of the solutions here were working for me. I'm using highcharts-ng in a nested view with ui-router and angular material. I was able to get this working in my controller as follows:

```javascript
function WidgetCtrl ($scope) {
        var vm = this;
        vm.highChartConfig = { ... };
        $scope.$on('$viewContentLoaded', 
            function (event) {
                vm.highChartConfig.getChartObj().reflow();
            }
        );
}
```

Kind of hacky but its working!

**Comment by pablojim** [comment]
Hi all, @houssemba has committed a fix for this that has now been merged to master. Can you have a look to see if that solves your issue?

**Comment by dmak** [comment]
I am not sure if I experience the same issue. I would like the chart to adapt to changing window width. In [this example](http://jsfiddle.net/dma_k/hch2o45m/2/) I have built two charts: the top one (vanilla Highcharts API) reacts correctly, but the bottom one has the fixed width all the time (expected that it extends/shrinks).

**Comment by houssemba** [comment]
@dmak add ``` display:block ``` to your highchart style or include highcharts-ng.css file

**Comment by pablojim** [comment]
@dmak http://jsfiddle.net/pablojim/2a8q4veg/
as @houssemba said!

**Comment by dmak** [comment]
@houssemba: Many thanks, it helped.
