### ISSUE TITLE
Series reference yAxis in config results in Highcharts error #18

### ISSUE THREAD

**Issue by spainb123** [pablojim/highcharts-ng#555]
Not related to 2-way axis binding, but referencing yAxis in a series config causes highcharts to fail to find the axis.  Error is "Highcharts error 18"  (Similar to Issue: #544 , but with backing fiddles)

Issue appears broken in 1.0.0
[https://jsfiddle.net/spainben/zb2kzmaa/](https://jsfiddle.net/spainben/zb2kzmaa/)

Issue appears fixed in 'master' as of commit/14c80f1aec8120b17b581ee7a117feb3562447d9
[https://jsfiddle.net/spainben/91de8w0v/](https://jsfiddle.net/spainben/91de8w0v/)

Since it appears fixed in master, this may not be an 'issue' per se, but rather just a confirmation that a fix is pending in a future release.

**Comment by pablojim** [comment]
@spainb123 Thanks! This will be included in the next release
