### ISSUE TITLE
european-union map drops out Malta

### ISSUE THREAD

**Issue by antonioaltamura** [pablojim/highcharts-ng#557]
I noticed Malta label and related <path> is out of the map

## Expected Behaviour
Island of Malta should be completely visible.

## Current Behaviour
The island is partially visible 

![map](https://cloud.githubusercontent.com/assets/6325475/22882844/637ea434-f1ed-11e6-9600-8ac2a1cbac64.png)

## Context
The problem is the Malta `<path>` and `<text>` are out of the visible part of the svg, obiouvsly increase the height of the wrapper div doesn't solve.

## Your Environment
* Version used:  highcharts-ng v0.0.13 - 2016-10-04

* Browser Name and version: 1.8.0
* Operating System and version (desktop or mobile): win7 x64

**Comment by parigi-n** [comment]
Isn't this a problem related to Highcharts and not Highcharts-ng ?

**Comment by antonioaltamura** [comment]
Yes it's related to the map itself.
