### ISSUE TITLE
[Highstocks] - X-Axis value is outside the scale when zooming via navigator.

### ISSUE THREAD

**Issue by badrinarayan20** [pablojim/highcharts-ng#559]
Current Behavior:
Steps:
1. Plot lot of data on highstocks.
2. Apply navigator zoom from left to right (or) vice versa. (width between the navigator buttons should be very less as shown in the screenshot).
3. Zoom the chart very slowly and we can observe that in the whole series there will be atleast one point which goes out of the scale.

Expected Behavior:
None of xaxis values should be plotted outside the scale of xaxis.

![outside_xaxis](https://cloud.githubusercontent.com/assets/22932732/22963027/91d85228-f376-11e6-8315-429ec68d9b52.png)

**Comment by pablojim** [comment]
jsfiddle please. Is this a problem with highstocks without using highcharts-ng?
