### ISSUE TITLE
Highchart events not working

### ISSUE THREAD

**Issue by misaizdaleka** [pablojim/highcharts-ng#56]
I want to trigger a function when clicking a highchart. I tried this in two different ways:
- Using ng-click on highchart directive
- Using highchart's click event
  Neither of these to work, check out this fiddle (both approaches included):
  http://jsfiddle.net/47m46/1/

Any idea what the problem may be?

**Comment by deepVova** [comment]
Have same problem, need to make click on plotOptions series point, but your solution isn't working
