### ISSUE TITLE
Synchronize multiple chart's x-axis.

### ISSUE THREAD

**Issue by fizerkhan** [pablojim/highcharts-ng#560]
I found the solution for x-axis synchronize for two chart(pasted below). But I stuck with multi chart synchronize. I have 8 charts in my dashboard. I want to synchronize all of them. 

Is there any fiddle code to do it? It will be very helpful if you put them in examples folder.

Existing code for two charts:

    $scope.chart1 = {
        options: {
            chart: {
                events: {
                    selection: function(event) {
                        self.onZoomHandler(event, 'chart2');
                    }
                }
            }
        }
    }

    self.onZoomHandler = function(event, chartToUpdate) {
        var chart = $scope[chartToUpdate].getHighcharts();
        if (event.xAxis) {
            chart.xAxis[0].setExtremes(event.xAxis[0].min, event.xAxis[0].max);
            if (!chart.resetZoomButton) {
                chart.showResetZoom();
            }
        } else {
            chart.xAxis[0].setExtremes(null, null);
            if (chart.resetZoomButton) {
                chart.resetZoomButton = chart.resetZoomButton.destroy();
            }
        }
    };

**Comment by pablojim** [comment]
This could be done with angular events. Not really an issue with this framework though. Maybe try stackoverflow?

**Comment by fizerkhan** [comment]
@pablojim Thanks.
