### ISSUE TITLE
Custom event handlers (series.point.events) are removed after data reload

### ISSUE THREAD

**Issue by koalalam** [pablojim/highcharts-ng#561]
## Expected Behaviour

Init chart config has custom event handlers defined in "series.point.events", for example:

chartConfig.series[0].point.events.click = function(e) {
    // do something
};

chartConfig.series[0].data = [ 1, 2, 3, 4, 5];

After that change the "data" field, for example:

chartConfig.series[0].data = [ 3, 4, 5, 6, 7];

The event handler is gone.

## Possible Solution

In $doCheck, new config is merged with default one which adds fields like "plotOptions". The existence of these default fields seem to make highchart to rebuild all the series and eventually the custom event handlers are lost

## Steps to Reproduce & Link to Example 

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by pablojim** [comment]
Jsfiddle please.

**Comment by pablojim** [comment]
Can you see if the new 1.0.1 release fixes your issue? Please reopen with a jsfiddle if not.
