### ISSUE TITLE
The plug-in error, can you tell me the version is wrong?Tips 5.0, but the latest was 1.0.2

### ISSUE THREAD

**Issue by wangcj10086** [pablojim/highcharts-ng#562]
angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.2/$injector/modulerr?p0=yooLi&p1=Error%3A%2…Flocalhost%3A1627%2Fbower_components%2Fangular%2Fangular.min.js%3A21%3A332)
    at angular.js:38
    at angular.js:4779
    at q (angular.js:357)
    at g (angular.js:4740)
    at db (angular.js:4662)
    at c (angular.js:1842)
    at Mc (angular.js:1863)
    at qe (angular.js:1748)
    at angular.js:33129
    at HTMLDocument.b (angular.js:3318)

**Comment by pablojim** [comment]
I'm sorry. I do not know what the problem is. Please open a new issue with a jsfiddle demonstrating the problem you are facing and what result you would expect.
