### ISSUE TITLE
Can't able to display above 999 points in time series chart

### ISSUE THREAD

**Issue by PrashanthYP** [pablojim/highcharts-ng#563]
In Time series chart, i have more than 1000 points. At the time the chart is not rendering. Getting blank area. Please suggest some option to resolve this.

## Expected Behavior
It should need to display all the points

## Current Behavior
chart is not rendering the graph when it reach above 999 points

## Possible Solution
Please suggest the possible solution

## Steps to Reproduce & Link to Example 
https://jsfiddle.net/kqLm66js/

## Your Environment

* 0.0.11
* Chrome 56.0
* Windows 7 & Desktop
* Currently development in local only

Please suggest on this issue.

**Comment by pablojim** [comment]
Not an issue with the plugin. Seehttp://api.highcharts.com/highcharts/plotOptions.series.turboThreshold
