### ISSUE TITLE
reflowing charts

### ISSUE THREAD

**Issue by TheNamlessGuy** [pablojim/highcharts-ng#564]
## Expected Behaviour

The reflow option that was previously in this plugin seems to have disappeared. In our application, we need to be able to reflow our charts, so bringing the old way back (or some new way) would be fantastic.

## Your Environment

* Version used: v1.0.1-dev
* Browser Name and version: Chrome 56
* Operating System and version (desktop or mobile): Android 5.1.1 using Cordova

**Comment by pablojim** [comment]
How about `chartConfig.getChartObj().reflow()`?

**Comment by TheNamlessGuy** [comment]
Since we use the <highchart></highchart> tags in our HTML code, we can't get access to the chartConfig object.

**Comment by pablojim** [comment]
I'm not sure what you mean. Please make a jsfiddle.

**Comment by TheNamlessGuy** [comment]
Well, our project is built up like: http://jsfiddle.net/pv645od3/  
However, it doesn't seem to want to realize getChartObj() is a function in our code.  

But since it works in JSFiddle the problem must be at our end. Apologies.

**Comment by pablojim** [comment]
@TheNamlessGuy  no problem - open an issue if you can reproduce it
