### ISSUE TITLE
Animation stops working for some types of chart in Angular 1.6.2

### ISSUE THREAD

**Issue by tmhung88** [pablojim/highcharts-ng#567]
I just upgraded to the latest Angular, 1.6.2 from 1.5.7, and the animation of the solid chart is not working anymore. 
## Link to jsfiddle showing the issue.
https://jsfiddle.net/tmhung88/tm5zej60/4/

## Expected Behavior
The gauge should run like this
https://jsfiddle.net/tmhung88/tm5zej60/5/

## Current Behavior
The chart is rendered fully without animation.

## My Environment

* Version of highcharts-ng used: 1.0.1
* Browser Name and version: Chrome

**Comment by tmhung88** [comment]
I am able to make the animation is shown again by putting the chart construction code into $postLink instead of $onInit. However, this change broke the other charts in my site.

**Comment by pablojim** [comment]
Not sure really - I imagine it is a change in AngularJS behaviour.
