### ISSUE TITLE
Labels in legend for highchart map not showing

### ISSUE THREAD

**Issue by adeetshah** [pablojim/highcharts-ng#570]
## Expected Behaviour
Expecting labels to be shown for the legend (please see expected.png attached file)
<img width="145" alt="expected" src="https://cloud.githubusercontent.com/assets/14948186/23764734/73a251fc-04b3-11e7-9cd7-1f852965f8b4.png">

## Current Behaviour
Currently, the legend labels do not show.
<img width="104" alt="observed" src="https://cloud.githubusercontent.com/assets/14948186/23764735/73a41dca-04b3-11e7-80b6-d51c99f9d3d8.png">
This is the code we use: 
colorAxis    : {
        min     : 0.01,
        labels  : {
          formatter: function () {
            return this.value + '%';
          }
        },
        minColor: '#B1CFE4',
        maxColor: '#173A66',
        stops   : [
          [0, '#B1CFE4'],
          [0.05, '#97B6CF'],
          [0.1, '#7E9DBA'],
          [0.15, '#6485A5'],
          [0.2, '#4A6C90'],
          [1, '#173A66']
        ]
      } 

## Your Environment

* Version of highcharts-ng used: 1.0.1
* Browser Name and version: Chrome V 56
* Operating System and version (desktop or mobile): mac os

**Comment by adeetshah** [comment]
<img width="734" alt="dom" src="https://cloud.githubusercontent.com/assets/14948186/23765738/0c0b27cc-04b7-11e7-843f-7cc2b2c83f17.png">

**Comment by pablojim** [comment]
Jsfiddle please

**Comment by adeetshah** [comment]
@pablojim Its complicated to get a jsfiddle out of it. Its part of a bigger application.

**Comment by pablojim** [comment]
Unfortunately if you can't reproduce the issue I can't fix it.
