### ISSUE TITLE
HighStock supported?

### ISSUE THREAD

**Issue by ChaseTJacobs** [pablojim/highcharts-ng#571]
The readme mentions highstock a few times, but there are no examples on how to use highstock instead of highcharts. What I want is something like this:
http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/compare/

From a few google searches I found this, which is from the same creator as highcharts-ng.
https://jsfiddle.net/pablojim/r88yszk0/
It doesn't work though.

So yea. Is highstocks supported? If so, does anyone have a working example?
Thanks

**Comment by dheerajps** [comment]
One of the graphs I was working on needed Highstocks, a basic one, but in the highcharts config object I added this at the bottom and it worked 
useHighStocks: true

**Comment by houssemba** [comment]
@ChaseTJacobs According to the source code, you need just to add ``` chartType: 'stock' ``` to your chartConfig. Feel free to open a PR to update the README

**Comment by ChaseTJacobs** [comment]
@houssemba Thanks that worked. useHighStocks: true didn't work for me.
