### ISSUE TITLE
Release a minor version with the resizing fix

### ISSUE THREAD

**Issue by houssemba** [pablojim/highcharts-ng#573]
Hello @pablojim 

Could you release a minor version with the resizing fix please ? 

I'm waiting for this fix to upgrade from the 0.0.13 to 1.0.x

Thank you

**Comment by houssemba** [comment]
@pablojim any news ?

**Comment by pablojim** [comment]
@houssemba life intruded! hopefully will get something out in the next few days.

**Comment by pablojim** [comment]
@houssemba @stonexjr just committed some changes. Let me know if these work for you and I'll then cut a release.

**Comment by houssemba** [comment]
LGTM

**Comment by pablojim** [comment]
Released version 1.1.0
Thanks @houssemba

**Comment by stonexjr** [comment]
LGTM! Thanks @pablojim.
