### ISSUE TITLE
Chart series are plotted not in the same order as declared

### ISSUE THREAD

**Issue by dmak** [pablojim/highcharts-ng#576]
If you run [this example](https://jsfiddle.net/dma_k/brcgktg6/) you will see a number of stacked columns with two splines. Now if you press "Add series" button, new stacked columns are added to the chart.

Result: splines are rendered behind newly added columns. Expected: splines are rendered on the top of columns.

Actually new series are inserted by `addSeries()` explicitly at the position (line 140), so that splines are at the end of series array. If you uncomment line 146 (which will add new series before initial chart is rendered), you will see that splines are correctly rendered on the top of all columns as expected.

highcharts-ng v1.0.1, AngularJS v1.6.2.

**Comment by pablojim** [comment]
So the order of series is not tracked at the moment. I'd suggest using http://api.highcharts.com/highcharts/series%3Cline%3E.zIndex to get the behaviour you want.

I think to fix it in the directive we'd need to manually keep track of the series' indexes. See: https://github.com/pablojim/highcharts-ng/blob/master/src/highcharts-ng.js#L58

As always PRs accepted!

**Comment by dmak** [comment]
Thanks for the hint with `zIndex`. I tried to dig deeper into `highcharts-ng.js`, however I couldn't understand the approach on high-level. If at the end of the day `mergedConfig.series` should be exactly the same as `ctrl.config.series`, why would one take care of what items are removed, and what – added? Maybe it would be enough to trace that _something_ is changed (or don't trace this at all)?
Also do you think it's reasonable to close issue which is confirmed to be an issue? Because `is:open` is the default filter on GitHub, so someone can not find this issue and will create similar one.

**Comment by pablojim** [comment]
Did the zIndex workaround work for you? If so maybe you could add a faq entry to the readme to help others.

The current behavior is that when someone adds a series is that that series is then added. Equally if they remove a series it is removed. If we just noticed that something in the series array has changed we would need to refresh all series which is not desirable. Tracking series index in the array would be possible but not something I'll work on at the moment if there is a simple workaround. 

As always PRs accepted, and I'm happy to help with questions.
