### ISSUE TITLE
Module not defined error

### ISSUE THREAD

**Issue by Pcummings** [pablojim/highcharts-ng#578]
Hi when upgrading from 1.0.1 to the latest version I'm getting these errors:
Uncaught ReferenceError: module is not defined
    at highcharts-ng.js:20
    at highcharts-ng.js:153

Preventing the page from loading.

I'm running AngularJS 1.6 on Node 7

**Comment by Pcummings** [comment]
Downgrading to 1.0.1 again fixes the issue

**Comment by pablojim** [comment]
Load highcharts.js before you load highcharts-ng.js. Let me know if this fixes your issue.

Please add a jsfiddle showing the problem if not.

**Comment by nagyf** [comment]
> Load highcharts.js before you load highcharts-ng.js. Let me know if this fixes your issue.

I had the same problem, this fixed it.
