### ISSUE TITLE
Support the highcharts context menu (export menu) through angular

### ISSUE THREAD

**Issue by ventralnet** [pablojim/highcharts-ng#579]
**Feature Request**

It would be nice if there was some 'Angular way' to configure and include the highcharts context-menu items (mainly used for the export module http://www.highcharts.com/docs/export-module/export-module-overview).

Currently, you configure this context menu through your chart configuration object
```
const menuItems = Highcharts.getOptions().exporting.buttons.contextButton.menuItems;
menuItems.push({
    text: "Change to Pie Chart",
    onclick() {
       //change to pie chart will require a $scope $digest
    }
});
exporting: {
   enabled: true,
   buttons: {
      contextButton: {
          menuItems: myMenuItems
      }
   }
}
```

Since the onclick handler you provide to highcharts is outside of Angular you must inject $scope into your component as well as manually trigger a $digest which is unfortunate.

Maybe the ability to add 
```<context-menu-item>```
elements as transcluded content to the highcharts component/directive

Thoughts?

**Comment by pablojim** [comment]
Sounds like a worthwhile feature. But unlikely I'll get anytime to work on it. Happy to assist with a PR though.
