### ISSUE TITLE
Please expose way to manually call reflow

### ISSUE THREAD

**Issue by nawlbergs** [pablojim/highcharts-ng#582]
## Link to jsfiddle showing the issue.

The issue with highcharts inside a table is discussed thoroughly here... and a css hack is described.. but it is still not always fixing the issue in my project:
https://github.com/highcharts/highcharts/issues/1157

I have a table that is displaying columns of data with a chart at the top.. when 1 column of data is drawn, everything seems fine.. but when the user adds a second column.. the 1st column does not resize.

I can NOT use a table for this particular page.. but i imagine there are a lot of cases where a chart inside a table will be needed. 

## Expected Behaviour

Chart inside a table should resize itself correctly.

## Current Behaviour

Chart will sometimes not resize correctly inside a table.

## Your Environment

* Version of highcharts-ng used: latest ("^1.0.0")
* Browser Name and version: latest chrome
* Operating System and version (desktop or mobile): desktop windows 10 and osx at work.
* Link to your project: its software behind a login sorry.

**Comment by pablojim** [comment]
you can call it using `config.getChartObj().reflow()` let me know if this doesn't work for you.

**Comment by dgreene1** [comment]
But how do I get a reference to config to use getChartObject() when config is one way bound. From what I can see, my config never gets modified due to the one way binding. From the angular documentation:
> "One-way binding is useful if you do not plan to propagate changes to your isolated scope bindings back to the parent. However, it does not make this completely impossible."

So by that description, I can not use config.getChartObj because my config is not modified.

**Comment by mathiasconradt** [comment]
@dgreene1 I also had issues with resizing (not with tables though) when I upgraded from Highcharts 4.x to 5.x (and highcharts-ng accordingly) but solved it with the css fix as mentioned here: https://github.com/pablojim/highcharts-ng/issues/550#issuecomment-275768761
Not sure if you already looked at this css fix as well, cause I think it's a different one than the one you mentioned in your description. Maybe it helps.
