### ISSUE TITLE
Drill down not working

### ISSUE THREAD

**Issue by wiggitamoo** [pablojim/highcharts-ng#585]
There is a bug when trying to dynamically add drill-down data to a chart. 
There is a bug when trying to dynamically delete the title of a chart.

## Link to jsfiddle showing the issue.
http://jsfiddle.net/Wiggitamoo/m1mw2ada/

## Expected Behaviour
* The chart should update when the drill-down series data changes.
* The chart series should remain on the x-axis when the title is deleted

## Current Behaviour
* Adding drill-down data after the chart loads doesn't update the chart.

* An additional, but less important bug I found is that deleting a dynamically added title leaves the chart floating above the x-axis.

## Your Environment
* Version of highcharts-ng used:
    * "highcharts": "^5.0.10",
    * "highcharts-ng": "^1.1.0",
* Browser Chrome Version 57.0.2987.133 (64-bit)
* Operating System MacOS Sierra 10.12.4 (16E195)

**Comment by pablojim** [comment]
Thanks, the Highcharts update function doesn't handle drilldown so we would need to add functionality to watch this property in the directive. When a changed in drilldown was detected we'd need to reinitialise the whole chart. 

Happy to help with a PR or I'll try get to this next time I'm working on a batch of changes.

**Comment by wiggitamoo** [comment]
I appreciate your feedback, and will watch for a fix in the future. We implemented a quick fix with an ng-if to reinitialize the chart after the drill-down  data updates.

Thanks!

**Comment by hugsbrugs** [comment]
Yes you would have to call `Chart.addSeriesAsDrilldown` method from [this page](https://www.highcharts.com/docs/chart-concepts/drilldown)
