### ISSUE TITLE
I am having trouble on scatter chart's tooltip . And When I check my config on jsfiddle with both native and ng highchart module it works nice. I feel  really confused.

### ISSUE THREAD

**Issue by furkankatman** [pablojim/highcharts-ng#586]
This is the jsfiddle http://jsfiddle.net/cmykvns4/ 
And my config :
{"chart":{"type":"scatter","width":null,"height":null,"zoomType":"xy","polar":false,"animation":false},"plotOptions":{"series":{"marker":{"enabled":true,"radius":3}}},"tooltip":{"headerFormat":null,"pointFormat":null,"footerFormat":null,"shared":false,"useHTML":true},"title":{"text":"Teklifler","useHTML":true,"identifier":0,"style":"color:#d1d1d1;fontWeight:bold;fontSize:12px;"},"xAxis":{"categories":["19.04.2017"],"crosshair":false},"yAxis":{"min":0,"title":null,"crosshair":false},"series":[{"id":"series-421","data":[{"x":500,"name":null,"y":629,"sliced":false,"selected":false,"DiscountRate":0,"userEmail":"xxx@gmail.com"}],"name":"Price Offers","colorByPoint":false,"color":null,"type":"scatter","marker":{"enabled":true,"radius":3,"symbol":"circle"},"groupPadding":0,"pointWidth":0,"pointPadding":0,"showInLegend":false}],"size":null,"credits":{"enabled":false}}

And the other problem is that I cant even produce same error on fiddle this config works fine on fiddle but not on my local computer. I can see that It is very difficult to identify the problem .
as I stated on the title if I change series type to line my tooltip works fine otherwise it doesnt work.
I am handling the problem but I dont feel clear about this and cant find where this problem comes from.
Please help :)

**Comment by furkankatman** [comment]
I found the reason caused this trouble.It is the set config method ```
Highcharts.setOptions({
        plotOptions: {
            area: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            arearange: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            areaspline: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            areasplinerange: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            bar: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            boxplot: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            bubble: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            column: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            columnrange: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            errorbar: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            funnel: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            gauge: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            heatmap: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            //line: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            pie: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            polygon: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            pyramid: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            scatter: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            //series: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            solidgauge: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            spline: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            treemap: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
            waterfall: { animation: false, enableMouseTracking: false, stickyTracking: true, shadow: false, dataLabels: { style: { textShadow: false } } },
        },
        chart: {
            reflow: false,
            events: {
                redraw: function () {
                }
            },
            animation: false
        },
        exporting: {
            enabled: false
        },
        credits: {
            enabled: false
        },
        lang: {
            decimalPoint: ',',
            thousandsSep: '.'
        },
        tooltip: {
            yDecimals: 2 // If you want to add 2 decimals
        }
        ,
        colors: ['rgb(124, 181, 236)']
    }); 
``` 
I am really sorry to make here busy about this stupid issue .
I hope I can help anybody having the same problem .

**Comment by pablojim** [comment]
@furkankatman no problem, glad you got it fixed
