### ISSUE TITLE
How to know when config.getChartObj() is available?

### ISSUE THREAD

**Issue by mathiasconradt** [pablojim/highcharts-ng#588]
## Link to jsfiddle showing the issue.
http://jsfiddle.net/j950np50/7/

-> line 61 throws an error in the dev console

## Expected Behaviour
I have a `<highchart id="ng-chart" config="chart"></highchart>` tag in my view and adding the chart config in my controller and assigning it accordingly. 

`$scope.chart = chartData;`

Afterwards I would like to get the chart object right away via

`console.log('$scope.chart.getChartObj(): ' + $scope.chart.getChartObj());`

but it's `undefined`. It seems that the generation of the chart object happens asynchronously (angular doing its binding job). How can I get notified when the chart object is ready? Is there an event triggered that I can listen to?

The only way I can get a hold of the chart object is using a timeout, which is usually not the best option.

```
  // it only works if I do it with a delay/timeout 
  setTimeout(function() {
    console.log('$scope.chart.getChartObj(): ' + $scope.chart.getChartObj());
  }, 1000)
```

## Current Behaviour
`$scope.chart.getChartObj()` is `undefined` when called without a timeout.

**Comment by pablojim** [comment]
you could try using: http://api.highcharts.com/highcharts/chart.events.render to fire a angular event?

**Comment by mathiasconradt** [comment]
Right, good idea. Haven't tested it but that should work as well.
