### ISSUE TITLE
Can't load highstock before higcharts-ng loads.

### ISSUE THREAD

**Issue by vsimonovski** [pablojim/highcharts-ng#590]
I'm using highcharts-ng 1.1.0, and constantly getting an error when trying to import highstock before highcharts-ng. Downgrading to 1.0.1 solved this issue so I think there is a problem with this particular part of 1.1.0 update.

> Added module loader support https://github.com/pablojim/highcharts-ng/commit/508df111886c4be8b26e82cb6d3e2303f17efed8 Thanks to @houssemba and others for the contributions.

For more relevance I'm using Webpack 2 as bundle loader and ES6 import features.

**Comment by houssemba** [comment]
#587 Fix the problem

**Comment by vsimonovski** [comment]
Thanks for the reply, I can't close issue yet since your commit isn't merged into master branch. Please notify me when pull request is done so I can test this out.

**Comment by pablojim** [comment]
@vsimonovski PR is now merged - can you confirm this fixes your issue?

**Comment by dhodgin** [comment]
I filed a similar bug to this today in #624 using webpack and importing highcharts first before highcharts-ng and having similar issues.

highcharts end up being injected into the bundle twice. both versions and you can't use highstock or version 6 as a result. the patch in #587 seems like it will at least allow highstock to be used but if a user doesn't have a license for highstock they are violating the license agreement by using this package.

I downgraded to v1.0.1 for now so I can import the product I have a license for and conform to the highcharts license.

**Comment by ngehlert** [comment]
@dhodgin @vsimonovski can you test your issues with the latest 1.2.0 version? should now work as expected

**Comment by vsimonovski** [comment]
Just tested, everything working as expected. Thanks.
