### ISSUE TITLE
“Pie chart” without animation

### ISSUE THREAD

**Issue by lengfo** [pablojim/highcharts-ng#591]
## Current Behaviour

1、Pie chart show animation 

   $scope.chartConfig = {
    chart: {
      type: 'pie'
    },
    series=[ { "data": [1, 2, 4, 7, 3], id: 's1'}
  }

2、Pie chart without animation ( fetch data by ajax )

  $scope.chartConfig = {
    chart: {
      type: 'pie'
    }
  }

  $timeout( function() {
          $scope.chartConfig.series=[ { "data": [1, 2, 4, 7, 3], id: 's1'}] ;
  } , 300 );

3、Same Issue in ‘Line ’ ，But ‘Bar’ is OK  

## Your Environment
Highcharts version is 5.0.11 
Highcharts-ng version is 1.1.0
Angular version is 1.5.8

**Comment by pablojim** [comment]
jsfiddle please
