### ISSUE TITLE
DataLabels not displayed when data are set dynamically

### ISSUE THREAD

**Issue by Getz85** [pablojim/highcharts-ng#598]
Hi

I tried to migrate Highcharts ( and so highcharts-ng) to their latest version (from Higcharts 4.x to 5.x) and I have some issues with dataLabels.

If the data are set when the chart is initializing, the dataLabels are correctly displayed.
(In the fiddle, uncomment the line `$scope.setSeries(`) at the end of the controller's code)

But if the data are set after the initialization (`$scope.setSeries()` commented) , the labels are never displayed (try clicking the "Set Series" button to display the chart on the fiddle)

http://jsfiddle.net/y09ycawd/4/

* Version of highcharts-ng used: 1.1.0
* Version of highcharts: 5.0.12
* Browser Name and version: All browsers

Any Idea?

**Comment by xavhan** [comment]
Highcharts 5.0.12 introduced this behaviour. I forced the installation of 5.0.11 in the meantime.
