### ISSUE TITLE
Missing Highcharts dependency in bower.json

### ISSUE THREAD

**Issue by dackmin** [pablojim/highcharts-ng#599]
As you mentioned in your last release (1.1.0), you explicitly added highcharts as a dependency in the `package.json` file but I think it is also necessary to add it to the `bower.json` file.

For those who might need it (for example if you are using `wiredep`), you can also use bower `overrides` property and add it yourself manually : 

```json
{
  "name": "",
  ...
  "overrides": {
    "highcharts-ng": {
      "dependencies": {
        "highcharts": "^5.0.12"
      }
    }
  }
}
```

**Comment by xavhan** [comment]
Highcharts 5.0.13 introduced this behaviour

**Comment by pablojim** [comment]
Any chance of a PR?

**Comment by dackmin** [comment]
done 😄
