### ISSUE TITLE
Question: how do I access the Highcharts api from within a controller?

### ISSUE THREAD

**Issue by johncade** [pablojim/highcharts-ng#600]
I am using highcharts within a grid that contains dragable and resizable divs. This allows users when editing to customize the layout of the dashboard. I cannot for the life of me figure out how to access the Highchats API from within my controller. The config object does not have a function attached to it. Looking at all the plunkers, and searching for the last hour, I have yet to come up with a solid example of how to access the chart object from within my controller. Using the basic example plunkr as a reference, how can I construct  the chart object in order to access the api in `myctrl`?

Any help with this would be greatly appreciated. I know Im missing something, but I feel like I keep going in circles. 

http://jsfiddle.net/gh/get/jquery/3.1.1/pablojim/highcharts-ng/tree/master/jsfiddles/basic/

**Comment by pablojim** [comment]
See faq and http://jsfiddle.net/pablojim/78ub008z/
