### ISSUE TITLE
Fail to load, error: o.setTitle is not a function

### ISSUE THREAD

**Issue by heavyrick** [pablojim/highcharts-ng#601]
It's not working for me. When i try to load, i get these errors and i got blank screen in the chart area.

![error](https://user-images.githubusercontent.com/8201411/26994038-3e2f0f02-4d3c-11e7-8378-af93d6b3188e.png)

HTML
```
<div ng-app="myapp">
  <div ng-controller="myctrl">
    <p>{{chart}}</p>
    <highchart id="chart1" series="chart.series" title="chart.title" options="chart.options"></highchart>
</div>
```

JS
```
var myapp = angular.module('myapp', ["highcharts-ng"]);

myapp.controller('myctrl', function($scope) {

  $scope.chart = {
    options: {
      chart: {
        type: 'bar'
      }
    },
    series: [{
      data: [10, 15, 12, 8, 7]
    }],
    title: {
      text: 'Hello'
    }
  }
});
```

Versions:
"angular": "^1.6.1",
"highcharts": "^5.0.12"
"highcharts-ng": "^0.0.13",

Files (in that order):
'bower_components/highcharts/highcharts.src.js',
'bower_components/highcharts-ng/dist/highcharts-ng.js'

**Comment by pablojim** [comment]
jsfiddle please.
