### ISSUE TITLE
Data labels won't show up when using highcharts-ng

### ISSUE THREAD

**Issue by noumamarouan** [pablojim/highcharts-ng#603]
Im facing an issue with highcharts-ng directive when using some of my hightcharts graphes:

$scope.chartRonConfig = {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: 0,
        plotShadow: false
    },
    title: {
        text: 'Browser<br>skjdfhsjdkf<br>2019',
        align: 'center',
        verticalAlign: 'middle',
        y: 40
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
        pie: {
            dataLabels: {
                enabled: true,
                distance: -50,
                style: {
                    fontWeight: 'bold',
                    color: 'white'
                }
            },
            startAngle: -90,
            endAngle: 90,
            center: ['50%', '75%']
        }
    },
    series: [{
        type: 'pie',
        name: 'Browser share',
        innerSize: '50%',
        data: [
            ['Firefox', 10.38],
            ['IE', 56.33],
            ['Chrome', 24.03],
            ['Safari', 4.77],
            ['Opera', 0.91],
            {
                name: 'Proprietary or Undetectable',
                y: 0.2,
                dataLabels: {
                    enabled: false
                }
            }
        ]
    }]
};

and on my view i put: <highchart id="RonContainer" config="chartRonConfig"></highchart>

If i use $scope.chartRonConfig = Highcharts.chart('RonContainer', { // same config } it shows the data labels but dosn't allow me to update my chartConfig when posting data to server. Any help pls thank you

**Comment by Cyric297** [comment]
I have the same issue.  Appears to be caused by an update highcharts main codebase.

**Comment by noumamarouan** [comment]
i actually downgrade the version using the 5.0.11 and it solved my problem you where right Cyric297, you can use the 5.0.11 version without any problem hope that @pablojim upgrade the version of he's directive. Nice work keep going.

Regards,
Marouan

**Comment by pablojim** [comment]
jsfiddle please. Also try construct a similar example with highcharts only as it's probably a highcharts bug.

**Comment by Cyric297** [comment]
I believe this is a highcharts bug as the downgrade works as @noumamarouan said.  I'll see if I can create a JS fiddle to show the error.
