### ISSUE TITLE
Cannot access chart object

### ISSUE THREAD

**Issue by jessicahur** [pablojim/highcharts-ng#605]
Hi all,
Is there any way that we can get the chart object out from highcharts-ng? I want to show loading feature on my chart and according to highcharts API reference, I have to call chart.showLoading() explicitly. I found a similar issue posted here in 2014 and at the time it wasn't possible to get the chart object out. What about now?
Thank you

**Comment by sdgluck** [comment]
I also am interested in how to access the underlying Highcarts chart objects in order to force redraws.

**Comment by sdgluck** [comment]
Ah, so you can access all the charts on a page via `Highcharts.charts`. Maybe this is useful to other people- it's exactly what I needed. Docs here: http://api.highcharts.com/highcharts/Highcharts.charts

**Comment by pablojim** [comment]
use `config.getChartObj()`

See the FAQ and http://jsfiddle.net/pablojim/78ub008z/
