### ISSUE TITLE
Highcharts-ng with Highchart Indicator plugin not working

### ISSUE THREAD

**Issue by seb999** [pablojim/highcharts-ng#607]
Hello,
Is it possible to use Highchart-ng with the highchart indicator plugin to display SMA, EMA, ATR, RSI on a highstock candelstick chart ? 
I didn't manage to make it working until now.

Highchart indicators plugin :
https://www.highcharts.com/plugin-registry/single/24/Indicators/
http://demo.blacklabel.pl/
https://jsfiddle.net/BlackLabel/RE7sS/?utm_source=website&utm_medium=embed&utm_campaign=RE7sS

Best regards

**Comment by pablojim** [comment]
make a broken jsfiddle and I can have a look

**Comment by seb999** [comment]
Hi Pablo, sorry for the late reply. I built up my own directive to solved this issue.
Thanks a lot
Sebastien
