### ISSUE TITLE
Highcharts Dependency problem

### ISSUE THREAD

**Issue by LandonSchropp** [pablojim/highcharts-ng#611]
We recently upgraded highcharts-ng from 1.0.1 to 1.1.0, which caused many of our charts to break. I believe the problem is this change mentioned in the readme:

> Now has explicit dependency on highcharts.js.

We're running Highcharts in [styled mode](https://www.highcharts.com/docs/chart-design-and-style/style-by-css), meaning we configure Highcharts via CSS. To use Highcharts in styled mode, we import the `node_modules/highcharts/js/highcharts-more.js` file. By explicity including a dependency on `highcharts.js`, highcharts-ng is swapping out our `highcharts-more.js` file for the non-styled build.

I'm not the best way to fix this, but it's definitely pretty broken as it is. Here's an example of the before and after for a couple of our charts:

Before:

<img width="884" alt="screen shot 2017-07-20 at 3 02 40 pm" src="https://user-images.githubusercontent.com/361591/28440760-889e274a-6d5c-11e7-9dab-e8086c2e0648.png">

<img width="882" alt="screen shot 2017-07-20 at 2 56 23 pm" src="https://user-images.githubusercontent.com/361591/28440768-932508aa-6d5c-11e7-8b0c-dc690ada5496.png">

After:

<img width="882" alt="screen shot 2017-07-20 at 3 02 33 pm" src="https://user-images.githubusercontent.com/361591/28440755-8599c522-6d5c-11e7-86ee-2ca65fd253c2.png">

<img width="884" alt="screen shot 2017-07-20 at 3 02 18 pm" src="https://user-images.githubusercontent.com/361591/28440777-9b439682-6d5c-11e7-95fb-a40cd69a4807.png">

Thanks!

**Comment by pablojim** [comment]
Resolved in 1.2.0 release
