### ISSUE TITLE
Does highcharts-ng v. 1.0.1 not allow the use of the options object?

### ISSUE THREAD

**Issue by lakeboy93** [pablojim/highcharts-ng#618]
I am using the 1.0.1 version of highcharts-ng with highcharts v5.0.14 and I am unable to use the options object to successfully display my charts.  For example, heatmap displays a line chart.  My main issue honestly is that I am unable to use colorAxis with the  1.0.1 version of highcharts-ng, but is there no way to use the options object with this version of highcharts-ng.  I'm unable to get highcharts v1.1.0 using bower.json as a dependency.

**Comment by lakeboy93** [comment]
Does the current version of highcharts-ng work with highcharts 5.0.14 ?

**Comment by pablojim** [comment]
Create a jsfiddle showing the problem and what you expect

**Comment by lakeboy93** [comment]
I asked a yes or no question and I would like a yes or no answer please

On Fri, Sep 29, 2017 at 12:09 PM, Barry Fitzgerald <notifications@github.com

**Comment by pablojim** [comment]
@lakeboy93 I'm not aware it of any problems in with specific versions of highcharts. If you make a jsfiddle showing a problem I'm happy to have a look.
