### ISSUE TITLE
Support for Highcharts/Highstock 6?

### ISSUE THREAD

**Issue by dpaquette** [pablojim/highcharts-ng#619]
Any plans to support Highstock / Highcharts 6.0.x?

**Comment by pablojim** [comment]
Hi - are you seeing any specific problems with the new version?

**Comment by dpaquette** [comment]
Not anymore no. I was previously on a very old version of highcharts-ng which mean my config objects didn't work anymore. I just had to make some minor changes and it all seems to be working now.
