### ISSUE TITLE
Highchart license issue

### ISSUE THREAD

**Issue by Nek-** [pablojim/highcharts-ng#623]
Hello

Highcharts have a commercial license. However, you include it by default in the `packages.json` as a dependency. This is a serious conflict of license. Many developers may think they can use your library to make charts as it.

Please consider to remove that dependency or add a huge warning on the readme. Please also be careful because I'm not a lawyer but I'm not sure you're in right to put an MIT license on top of the license of Highcharts.

**Comment by dhodgin** [comment]
By including highcharts in the package as well it forces everyone to use highcharts only. You cannot make use of highstock or highmaps when using ES6 import it seems.

Filing a separate issue for that though

**Comment by pablojim** [comment]
@Nek @dhodgin I think this is an issue. On balance it's best to remove the dependency on highcharts and flag this clearly in the docs.

PRs gladly accepted or else wait for me to get around to it.

**Comment by pablojim** [comment]
Resolved in 1.2.0 release
