### ISSUE TITLE
Does this library get use of Jquery?

### ISSUE THREAD

**Issue by Zerokk** [pablojim/highcharts-ng#631]
Easy question: does this library use JQuery? 

I mean, the original HighCharts uses JQuery, and JQuery breaks my project always that gets imported, for absolutely no reason (in fact I've got a big issue complain in Angular's repo because this may be a deep, core problem of their framework).

Anyways... I can't get your library working because it breaks my project in the same way JQuery does, so I guess it's still using it even if it's not in an obvious way. I see [there are some js files which can substitute the use of JQuery by plain JS](http://code.stephenmorley.org/javascript/using-highcharts-without-jquery/), but... where do I have to put that file? 

Thank you for your help!

**Comment by pablojim** [comment]
There is a development dependency on jquery for some tests but the plugin has no further dependencies on jquery.
