### ISSUE TITLE
How to highlight series if I click it?

### ISSUE THREAD

**Issue by Deimos620** [pablojim/highcharts-ng#632]
Sorry, this error is something I couldn't show via jsfiddle, because its working on jsfiddle, doesn't work in my application. But I will provide a detailed instruction.

I see, highcharts provides, a useful functionality - if you hover the symbol of one series on legend, then that series are highlighted in the graph.
Here is a image.

![screen shot 2017-12-07 at 10 40 02 am](https://user-images.githubusercontent.com/20041972/33720684-1e499ed6-db3b-11e7-954a-da77d0c3065f.png)

I want to do this when I click one series on the graph. So, if I click one series, then only that series should be highlighted on that graph, and others are dimmer.
How I can do this? Is there any solution to do this?

Thanks.

**Comment by pablojim** [comment]
Post the working jsfiddle then and give some details about your app.
