### ISSUE TITLE
How to add listener to addSeries event?

### ISSUE THREAD

**Issue by donli1210** [pablojim/highcharts-ng#637]
Hi,

Please see this [JsFiddle](http://jsfiddle.net/p8g9u5v3/). I want to add a listener for [ addSeries event](https://api.highcharts.com/highcharts/chart.events.addSeries) using the [plugin way](https://www.highcharts.com/docs/extending-highcharts/extending-highcharts).

I can get the mouse hover event by `$(chart.container).bind('mousemove', function() {}`. But 

```
 $(chart.container).bind('addSeries', function() {

          console.log('New series added.');

        });
```

does not work. Any suggestions? Thanks!

**Comment by pablojim** [comment]
I have never played with adding plugins. PRs accepted!
