### ISSUE TITLE
How to dynanically change chart to percentage change?

### ISSUE THREAD

**Issue by donli1210** [pablojim/highcharts-ng#640]
Please see this [fiddle](http://jsfiddle.net/wp7ftkmn/)

If I put the following settings in the `$scope.chartConfig`, it is working

```
plotOptions: {
  series: {
          compare: 'percent'
   }
}
```

If I put it to a function and change it dynamically
```
$scope.changePercentage = function() {
      $scope.chartConfig.plotOptions.series.compare = 'percent';
      $scope.chartConfig = angular.copy($scope.chartConfig);
    };
```
It is not working. Any suggestions? Thanks!

**Comment by pablojim** [comment]
There was an error in your jsfiddle- check the console of your jsfiddle for details. See here for an alternative approach. 

http://jsfiddle.net/upjb6rLh/

**Comment by donli1210** [comment]
Thanks!
