### ISSUE TITLE
有段数据在highstock里展示有问题，求解原因~why？

### ISSUE THREAD

**Issue by qiancj1022** [pablojim/highcharts-ng#642]
## Link to jsfiddle showing the issue.

数据：[[1513267200000,1431.3],[1512662400000,1425.47],[1512057600000,1426.68],[1511452800000,1438.21],[1510848000000,1448.18],[1510243200000,1462.44],[1509638400000,1437.26],[1509033600000,1449.74],[1508428800000,1435.18],[1507824000000,1438.45],[1506614400000,1418.93],[1506009600000,1413.48],[1505404800000,1409.44],[1504800000000,1405.54]]

可到官网demo里用线形图试验--type:"line"
情况：1.图表底部的滚动条不拉满的时候，不能展示图，但能展示X轴。
           2.图表底部的滚动条满的时候，可以展示图，却不能展示X轴上面的值。

## Your Environment

* Version of highcharts-ng used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by pablojim** [comment]
Please open a new issue with a jsfiddle. Also please use Google translate to enter the issues in English if possible.
