### ISSUE TITLE
Series data variable not updating/watching

### ISSUE THREAD

**Issue by cointilt** [pablojim/highcharts-ng#66]
### Problem

I have a angular $timeout function being called that updates the chartOptions value and adds a data point but it does not update the chart.

When console logging the data, it is adding a new point to the options each time. So I know the actual function of adding the point is working.
### File Versions

jQuery 2.0.3
AngularJS 1.2.9
HighCharts 3.0.9
highcharts-ng 0.0.3
### Code

html

``` html
<highchart id="default-chart-1" config="chartOptions"></highchart>
```

javascript

``` javascript
$scope.chartOptions = {
    useHighStocks: false,
    options: {
        chart: {
            type: 'spline',
            zoomType: 'x'
        }
    },
    series: [{
         data: [10, 15, 12, 8, 7]
     }],
    title: {
        text: 'First Chart'
    },
    xAxis: {currentMin: 0, currentMax: 10, minRange: 1},
    loading: false
};

function addPoint() {
    var randomPoint = Math.floor((Math.random()*10)+1) + 8;
    console.log('Random Point: ' + randomPoint, $scope.chartOptions);
    $scope.chartOptions.series[0].data.push(randomPoint);


    $timeout(addPoint, 1000);
};

addPoint();
```

**Comment by wasifjahangir** [comment]
Facing the same issue now. even above mentioned jsFiddle is no more working. can someone guide ?
