### ISSUE TITLE
Autoscale charts

### ISSUE THREAD

**Issue by brayniverse** [pablojim/highcharts-ng#70]
Is there a way to autoscale charts to their container, more specifically automatically scale when the container resizes `(without window.resize())`?

**Comment by oriko** [comment]
Hi

Why when I am using the "highchartsng.reflow" event I get a link to highcharts.com on chart right side?

Thanks,

**Comment by seadour** [comment]
Have you disabled the credits explicitly in your graph's config object?

    $scope.graphConfig = {
      options: {
        credits: {
          enabled: false
        }
      }
    };

**Comment by DezrtRose** [comment]
thank you, @pderksen

**Comment by nawlbergs** [comment]
The "highchartsng.reflow" event seems has disappeared in the .component version.
How do we trigger a ctrl.chart.reflow(); with the .component version?
