### ISSUE TITLE
How can I create multiple Y Axes chart ?

### ISSUE THREAD

**Issue by hiteshpatwari** [pablojim/highcharts-ng#82]
I am facing a requirement, where I need to use multiple axes in the chart, I see that highcharts already supports this : 

http://www.highcharts.com/demo/combo-multi-axes

JSFIddle : 
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/combo-multi-axes/

Is this functionality being developed ?

**Comment by pscanlon1** [comment]
I cant even get this to work with angular. Your fiddle suggestion makes complete sense.

Highcharts error #18: www.highcharts.com/errors/18

**Comment by benelliott** [comment]
I got this working by putting my y-axis properties at configObj.options.yAxis rather than configObj.yAxis.
