### ISSUE TITLE
Clicking events (via plotOptions) not working

### ISSUE THREAD

**Issue by mdedetrich** [pablojim/highcharts-ng#83]
I am attempting to use `plotOptions` to add an event when someone clicks on a bar for a column type chart, however events in the `plotOptions` doesn't appear to work

Here is an example of it working when using highcharts normally

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-point-events-click-column/

However when attempting to use the exact same options code in highcharts-ng, it doesn't work. Here is an example of what I am using currently http://jsfiddle.net/7cAq3/47/

**Comment by sajumani** [comment]
inside the plot point click event, i count call $scope functions;

 point: {
                        events: {

                            click: function () {
								$scope.addTab();
                            }
                        }
                    }

$scope.addTab(); // this not seem works

**Comment by pablojim** [comment]
Please don't comment on closed issues. Could you create a new issue with a jsfiddle?
