### ISSUE TITLE
Getting chart object back to do custom rendering

### ISSUE THREAD

**Issue by mdedetrich** [pablojim/highcharts-ng#97]
As per this fiddle
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/renderer-text-on-chart/

Is it possible to get the `chart` object back so you can do stuff like custom rendering on the graph?

**Comment by gonglei** [comment]
This can be done with current version, while documentation is not clear.
In source code, highcharts constructor is called:
```javascript
new Highcharts.Chart(mergedOptions, func)
```
The second parameter is a callback when highcharts initialization is finished:
http://api.highcharts.com/highcharts#Highcharts.Chart (it does not explain its arguments)
We can get the chart object from the 1st argument of this function. Add following code to your chart config object:
```javascript
func: function(chart) {
      $scope.chartObj = chart;
}
```
Then you can use it in your view or code (for any API calls):
```html
<span>{{chartObj.renderer.height}}</span>
```
```javascript
$scope.chartObj.renderer.circle(...);
$scope.chartObj.getSelectedPoints();
```
As an example I forked the plunk mentioned by **melanker** earlier in this thread:
http://plnkr.co/edit/6WvHEjJfr4pGqd2OvPKF?p=preview

**Comment by jonathanwoahn** [comment]
@gonglei Thanks, your suggestion works perfectly! That's exactly what I needed

**Comment by HermanBovens** [comment]
Getting the chart object is possible directly from the chart config object.
For example if in your template you have:

`<highchart config="ctrl.chartConfig">`

Then in your directive controller, assuming `bindToController: true`, you should be able to do

`this.chartConfig.getHighcharts()' to get the actual chart object.

**Comment by inoxbuttons** [comment]
When I try to use this.chartConfig.getHighcharts()  I get he error "getHighcharts is not a function"

**Comment by manatarms** [comment]
I tried this method of getting a local reference to the chart object, but I'm getting a weird result
func: function(chart) {
      $scope.chartObj = chart;
}

When I invoke a function eg. `moveLine()`, that uses the object in the same controller it says `$scope.chartObj is undefined` but when I invoke it from the view like `ng-click="moveLine()"` it works.

Any ideas on why this is happening. 
Cheers.

**Comment by Anj21** [comment]
<highcharts-chart [Highcharts]="highcharts" [options]="chartOptions"></highcharts-chart>

console.log("highcharts charts => ", Highcharts); 
//This one give highchart object as output in console.
console.log("highcharts charts => ", Highcharts.charts); 
//Highcharts.charts give charts object as output in console. Array(0) =>
0: a.Chart {renderTo: highcharts-chart, exporting: {…}, navigation: {…}, userOptions: {…}, margin: Array(4), …}
length: 1
__proto__: Array(0)

console.log("highcharts charts[0] => ", Highcharts.charts.length, Highcharts.charts[0]);
Now in this, when i am trying to access Highcharts.charts[0] it give undefined why? Can Anyone please help me to figure out this, i want to get Highcharts.charts[0].series to re-render the chart for live polling.

In AngularJs we can do like that, but i am not finding any lead for Angular7.
var chart = $('#theChart').highcharts();
chart.series[0].update({ color: '#d14242' });
This is how, we can do in AngularJs, but In angular7, I am not getting. Can anyone Please help.

**Comment by lecollage** [comment]
> <highcharts-chart [Highcharts]="highcharts" [options]="chartOptions">
> 
> console.log("highcharts charts => ", Highcharts);
> //This one give highchart object as output in console.
> console.log("highcharts charts => ", Highcharts.charts);
> //Highcharts.charts give charts object as output in console. Array(0) =>
> 0: a.Chart {renderTo: highcharts-chart, exporting: {…}, navigation: {…}, userOptions: {…}, margin: Array(4), …}
> length: 1
> **proto**: Array(0)
> 
> console.log("highcharts charts[0] => ", Highcharts.charts.length, Highcharts.charts[0]);
> Now in this, when i am trying to access Highcharts.charts[0] it give undefined why? Can Anyone please help me to figure out this, i want to get Highcharts.charts[0].series to re-render the chart for live polling.
> 
> In AngularJs we can do like that, but i am not finding any lead for Angular7.
> var chart = $('#theChart').highcharts();
> chart.series[0].update({ color: '#d14242' });
> This is how, we can do in AngularJs, but In angular7, I am not getting. Can anyone Please help.

Man, I faced the same issue and I found your question only now.
Please, look carefully to their doc and especcially to their Demo app.
In the component <highcharts-chart> there is output property (chartInstance). Use it for getting the instance of the chart.
